// Kinetic: recreational-flying page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "recreational-flying",
    v1: "Physics: nailed it 🎈",
    b1: "You've got the physics of flight. Skim the chapters for anything you missed, then scroll to “Where to go” for clubs, schools and balloon flights at your level. Knowing the science is a great start; it is not the same as training, a licence, or being current and safe in the air.",
    b2: "You have the basics. Fill the gaps below before your first lesson, especially the weather and stall chapters: they're the ones instructors care about most.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to fly at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, a pilot licence, a rating, a medical clearance or an exam pass, and a high score does not make you ready to fly any aircraft. Learn only with qualified instructors at an approved school or club, follow DGCA rules and your operator's briefing, and let the pilot or instructor decide whether the weather is flyable."
  };
  const CHAPTERS = {
    "ch-lift":    "Ch 1 · Lift, drag & glide",
    "ch-soar":    "Ch 2 · Thermals, ridges & soaring",
    "ch-balloon": "Ch 3 · Hot air: buoyancy you can calculate",
    "ch-power":   "Ch 4 · Powered vs unpowered flight",
    "ch-weather": "Ch 5 · Weather & density altitude",
    "ch-stall":   "Ch 6 · Stalls, turns & control"
  };
  const QUESTIONS = [
    { ch: "ch-lift",
      q: "A sailplane with a glide ratio of 40 is 1,000 m above flat ground in still air. Roughly how far can it glide?",
      o: ["About 4 km", "About 40 km", "About 400 m", "About 400 km"], a: 1,
      e: "Glide ratio = metres forward per metre of height lost, so 1,000 m × 40 = 40 km in still air. A headwind shortens that distance over the ground, a tailwind stretches it, and sinking air can cut it dramatically." },
    { ch: "ch-lift",
      q: "Lift = ½ × air density × speed² × wing area × lift coefficient. On a hot day at a high airfield the air is thinner. To make the same lift, a wing must…",
      o: ["Fly faster through the air (or at a higher angle of attack)", "Fly slower", "Nothing changes: lift doesn't depend on air density", "Carry more fuel"], a: 0,
      e: "Lower density means less lift at the same true airspeed, so the wing must fly faster or at a higher angle of attack. That's why take-off runs get longer, and climbs weaker, on hot days at high places (Ch 5)." },
    { ch: "ch-soar",
      q: "A glider sinks at 0.8 m/s through the air while circling. The thermal around it is rising at 2.5 m/s. What's the glider's climb rate?",
      o: ["3.3 m/s", "2.5 m/s", "1.7 m/s", "0.8 m/s"], a: 2,
      e: "The glider always sinks through the air around it; if that air is rising faster, the glider goes up. 2.5 − 0.8 = 1.7 m/s, about 1,000 m in 10 minutes. Soaring pilots look for air rising faster than their sink rate." },
    { ch: "ch-soar",
      q: "What creates ridge (slope) lift?",
      o: ["Wind blowing onto a hillside is deflected upward", "The sun heats only the ridge top", "Air sinking down the back of a hill", "Clouds pushing air down onto the ridge"], a: 0,
      e: "When wind meets a slope, air is forced up and over it. On the windward side, that rising band can keep a glider, hang glider or paraglider aloft for as long as the wind blows steadily onto the ridge. The lee side is the opposite: sinking air and turbulence." },
    { ch: "ch-soar",
      q: "Why are thermals usually strongest from late morning into the afternoon on sunny days?",
      o: ["The air is coldest then", "The wind always stops at noon", "Clouds trap heat overnight", "The sun has heated the ground, which warms the air above until bubbles of it rise"], a: 3,
      e: "Sunlight heats the ground, the ground heats the air touching it, and warm, less dense air rises in bubbles or columns. That needs a few hours of sun. It's also why balloon flights go at sunrise: before the thermals start (Ch 3, Ch 5)." },
    { ch: "ch-balloon",
      q: "Why does a hot-air balloon rise?",
      o: ["The hot air inside is less dense than the cooler air outside, so the envelope weighs less than the air it displaces", "Hot air contains helium", "The burner pushes it up like a rocket", "Hot air is attracted to the sky"], a: 0,
      e: "Archimedes: the upthrust equals the weight of air displaced. Heating air at constant pressure lowers its density (ρ = P ÷ RT), so 2,800 m³ of air at 100 °C weighs about 780 kg less than the same volume at 15 °C. That difference is the lift." },
    { ch: "ch-balloon",
      q: "A 2,800 m³ balloon at 100 °C inside has about 781 kg of gross lift on a 15 °C morning at sea level. On a 35 °C afternoon, with the same inside temperature, it has…",
      o: ["More lift, about 900 kg", "Exactly the same lift", "Less lift, about 560 kg", "No lift at all"], a: 2,
      e: "Warmer outside air is less dense, so the difference between inside and outside shrinks: 1.146 − 0.946 = 0.20 kg/m³, × 2,800 m³ ≈ 559 kg. That's over 200 kg less lift: two or three fewer passengers. Try it in the Balloon Lab." },
    { ch: "ch-balloon",
      q: "Why do commercial balloon flights in India go up around sunrise or late afternoon?",
      o: ["Burners only work in the dark", "Ticket rules", "Birds are asleep", "Winds near the ground are usually lighter and the air steadier, and cooler air gives more lift"], a: 3,
      e: "Balloons can't steer against the wind and land wherever the wind takes them, so pilots want light, steady winds. Thermals and gusty winds build as the sun heats the ground; early mornings also give cooler outside air, which means more lift for the same envelope temperature." },
    { ch: "ch-power",
      q: "In steady, level cruise, a microlight's engine thrust mainly balances…",
      o: ["Weight", "Drag", "Lift", "Buoyancy"], a: 1,
      e: "In level flight, lift balances weight, and thrust balances drag. Extra thrust beyond the drag is what lets an aircraft climb or accelerate. A glider has no thrust, so it trades height for the energy to overcome drag." },
    { ch: "ch-power",
      q: "A 450 kg microlight cruises at 25 m/s (90 km/h) with a lift-to-drag ratio of 10. About how much power does it need just to overcome drag?",
      o: ["About 1.1 kW", "About 11 kW", "About 110 kW", "About 1.1 MW"], a: 1,
      e: "Weight = 450 × 9.81 ≈ 4,400 N. Drag = weight ÷ L/D ≈ 440 N. Power = drag × speed ≈ 440 × 25 ≈ 11 kW. The propeller isn't perfect, so the engine must deliver more, plus extra for climbing and hot days." },
    { ch: "ch-power",
      q: "What does a paramotor's motor change compared with flying a paraglider?",
      o: ["It replaces the wing", "It makes the wing impossible to stall", "It gives thrust, so you can take off from flat ground and climb without rising air; the wing still makes the lift", "It means wind no longer matters"], a: 2,
      e: "The fabric wing above you is still doing the lifting. The motor on your back supplies thrust to overcome drag and climb, which frees you from needing a hill or a thermal. Wind, turbulence and stalls still matter exactly as they do on a paraglider." },
    { ch: "ch-weather",
      q: "At the ground it's 30 °C with a dew point of 18 °C. Using the rule of thumb of about 125 m per °C of spread, roughly where is the base of the cumulus clouds?",
      o: ["About 150 m", "About 1,500 m", "About 15 km", "At ground level"], a: 1,
      e: "Spread = 30 − 18 = 12 °C; 12 × 125 ≈ 1,500 m above the ground. Rising air cools as it expands, and once it cools to its dew point, water vapour condenses into cloud. Thermals are usually strongest under the cloud base." },
    { ch: "ch-weather",
      q: "Why is a towering cumulonimbus (thunderstorm cloud) a no-go for light aircraft, gliders and balloons?",
      o: ["It's only dangerous to jets", "It makes the air too dense to fly", "It is always far away", "Violent up- and downdrafts, gust fronts that can spread many kilometres from the storm, hail and lightning"], a: 3,
      e: "Storm updrafts and downdrafts can overpower a light aircraft or a balloon, and the outflow (gust front) can hit well before the rain arrives. Pilots stay well clear and land early when storms build, especially in pre-monsoon and monsoon weather." },
    { ch: "ch-stall",
      q: "In a level turn with 60° of bank, the wing must carry 2 g. What happens to the stall speed?",
      o: ["It doesn't change", "It doubles", "It rises by about 41% (√2 ≈ 1.41)", "It falls"], a: 2,
      e: "Stall speed rises with the square root of the load factor: √2 ≈ 1.41. A wing that stalls at 50 km/h in level flight stalls at about 71 km/h in a 60° turn. That's why steep turns close to the ground at low speed are so dangerous." },
    { ch: "ch-stall",
      q: "Hang gliders and microlight 'trikes' are weight-shift aircraft. That means the pilot steers mainly by…",
      o: ["Moving their body relative to the wing, shifting the centre of mass", "Moving ailerons with a control stick", "Changing the burner flame", "Pulling a reserve parachute handle"], a: 0,
      e: "On a weight-shift aircraft the pilot pushes or pulls a control bar, moving their weight relative to the wing so it rolls and pitches. Three-axis microlights and gliders use ailerons, elevator and rudder instead. A balloon pilot only controls up and down." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- BALLOON LAB ----------
  // Ideal gas: rho = P / (287.05 * T). ISA pressure: P(h) = 101325 * (1 - 2.25577e-5 h)^5.25588.
  // Gross lift = V * (rho_out - rho_in). Equipment mass is an illustrative 0.14 kg per m³ of envelope
  // (envelope, basket, burners, fuel); passengers 80 kg each, pilot included. Teaching model only.
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("bl-vol")) return;
    let elev = 0;
    const R = 287.05, EQUIP = 0.14, PERSON = 80;
    const P = h => 101325 * Math.pow(1 - 2.25577e-5 * h, 5.25588);
    const fmt = n => Math.round(n).toLocaleString("en-IN");
    function lift(V, h, to, ti) { const p = P(h); return V * (p / (R * (to + 273.15)) - p / (R * (ti + 273.15))); }
    function update() {
      const V = +$("bl-vol").value, to = +$("bl-out").value, ti = +$("bl-in").value;
      $("bl-vol-o").textContent = fmt(V) + " m³";
      $("bl-out-o").textContent = to + " °C";
      $("bl-in-o").textContent = ti + " °C";
      const p = P(elev), ro = p / (R * (to + 273.15)), ri = p / (R * (ti + 273.15));
      $("bl-rho-out").textContent = ro.toFixed(3);
      $("bl-rho-in").textContent = ri.toFixed(3);
      const gross = V * (ro - ri), equip = EQUIP * V, pay = gross - equip;
      $("bl-gross").textContent = fmt(gross) + " kg";
      $("bl-equip").textContent = fmt(equip) + " kg";
      $("bl-pay").textContent = (pay < 0 ? "−" + fmt(-pay) : fmt(pay)) + " kg";
      $("bl-pay").style.color = pay < 0 ? "#ff8a70" : "#fff";
      const people = Math.max(0, Math.floor(pay / PERSON));
      $("bl-people").textContent = pay < PERSON ? "none" : people + (people === 1 ? " person" : " people");
      $("bl-deg").textContent = "+" + (lift(V, elev, to, ti + 1) - gross).toFixed(1) + " kg";
      // inside temperature needed to carry equipment + 4 people
      const need = equip + 4 * PERSON, riNeed = ro - need / V;
      let txt;
      if (riNeed <= 0) txt = "not possible";
      else { const t = p / (R * riNeed) - 273.15; txt = t > 120 ? "above 120 °C" : Math.round(t) + " °C"; }
      $("bl-need").textContent = txt;
      $("bl-sphere").textContent = (2 * Math.cbrt(3 * V / (4 * Math.PI))).toFixed(1) + " m";
      $("bl-bar").style.width = Math.max(0, Math.min(100, pay / 1000 * 100)).toFixed(0) + "%";
    }
    ["bl-vol", "bl-out", "bl-in"].forEach(id => $(id).addEventListener("input", update));
    document.querySelectorAll("#bl-elev button").forEach(b => b.addEventListener("click", () => {
      elev = +b.dataset.elev;
      document.querySelectorAll("#bl-elev button").forEach(x => x.setAttribute("aria-pressed", x === b ? "true" : "false"));
      update();
    }));
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
