// Kinetic: cycling-mtb page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "cycling-mtb",
    v1: "Physics: nailed it 🚴",
    b1: "You've got the physics of the bike. Skim the chapters for anything you missed, then scroll to “Where to ride” for rides, brevets, courses and races at your level. Knowing the science is a great start; it isn't the same as fitness, bike handling or road sense.",
    b2: "You have the basics. Fill the gaps below before your next big ride, especially braking and climbing: they're the chapters that keep you safe and get you home.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to ride at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, a coaching assessment or a judgement of which roads or trails you can ride. Wear a helmet, obey traffic rules and be visible on the road, keep your bike maintained, and ride trails within your ability, ideally after learning skills from a qualified coach or course."
  };
  const CHAPTERS = {
    "ch-power": "Ch 1 · Power & the three resistances",
    "ch-drag":  "Ch 2 · Air drag, position & drafting",
    "ch-climb": "Ch 3 · Climbing & watts per kilo",
    "ch-gears": "Ch 4 · Gears & cadence",
    "ch-brake": "Ch 5 · Cornering & braking",
    "ch-trail": "Ch 6 · Trails, tyres & suspension"
  };
  const QUESTIONS = [
    { ch: "ch-power",
      q: "On a flat road at about 34 km/h, where does most of a cyclist's power go?",
      o: ["Rolling resistance of the tyres", "Pushing air out of the way (air drag)", "Lifting the bike against gravity", "Friction in the bearings"], a: 1,
      e: "In our Power Lab, an 85 kg rider and bike on the flat at 200 W spends about 80% of the power on air drag and about 20% on rolling resistance. On flat roads, the air is your main enemy." },
    { ch: "ch-power",
      q: "Power = force × speed. To push against 30 N of total resistance at 10 m/s (36 km/h), how much power do you need?",
      o: ["300 W", "3 W", "30 W", "3,000 W"], a: 0,
      e: "P = F × v = 30 × 10 = 300 W, about what a fit amateur can hold for a while. Every watt you produce goes into rolling, climbing or pushing air." },
    { ch: "ch-drag",
      q: "The power needed to beat air drag grows with speed cubed. Going from 20 km/h to 40 km/h multiplies the drag power by about:",
      o: ["2", "4", "8", "16"], a: 2,
      e: "Drag force grows with v², and power = force × speed, so drag power grows with v³: 2³ = 8. With a typical 0.32 m² drag area, that's about 33 W at 20 km/h and about 263 W at 40 km/h." },
    { ch: "ch-drag",
      q: "Why does riding close behind another rider make pedalling easier?",
      o: ["They pull you along with a magnetic effect", "It increases your tyre grip", "It lowers your weight", "You ride in their slower-moving wake, so the air pushes on you less"], a: 3,
      e: "The rider in front pushes the air aside and leaves a wake of slower air behind them. In it, your drag is lower for the same speed. It also means you have less time to react: ride close only with riders you trust." },
    { ch: "ch-climb",
      q: "On a long, steep climb, which number best predicts how fast you'll go?",
      o: ["Power-to-weight ratio (watts per kilo)", "How aero your helmet is", "Tyre width", "Frame colour"], a: 0,
      e: "Climbing slowly, drag is small and most of your power lifts your weight. In our Power Lab, at 200 W on an 8% grade about 92% of the power goes into climbing, so watts per kilo decide your speed." },
    { ch: "ch-climb",
      q: "An 85 kg rider and bike on an 8% grade: about how much of their weight pulls them back down the slope?",
      o: ["About 6.6 N", "About 660 N", "About 66 N", "About 6,600 N"], a: 2,
      e: "Force = m g sin θ, where tan θ = 0.08: 85 × 9.81 × 0.08 ≈ 66 N, on top of rolling resistance. At 10 km/h (2.8 m/s), that's about 184 W just to lift yourself." },
    { ch: "ch-climb",
      q: "At a steady 200 W, roughly how fast does an 85 kg rider and bike go up an 8% road climb?",
      o: ["About 30 km/h", "About 10 km/h", "About 2 km/h", "About 20 km/h"], a: 1,
      e: "Solving 200 W = climbing + rolling + drag gives about 2.8 m/s ≈ 10 km/h, gaining about 800 m of height per hour. Drop 10 kg and the same 200 W gives about 11 km/h." },
    { ch: "ch-gears",
      q: "With a 50-tooth chainring and an 11-tooth rear cog, how many times does the rear wheel turn for each pedal revolution?",
      o: ["About 0.22", "Exactly 1", "11", "About 4.5"], a: 3,
      e: "Gear ratio = chainring ÷ cog = 50 ÷ 11 ≈ 4.5. With a road wheel about 2.1 m round, one pedal stroke moves you about 9.5 m; at 90 rpm that's about 51 km/h." },
    { ch: "ch-gears",
      q: "Why shift into an easier (lower) gear on a climb?",
      o: ["It lets you keep a comfortable cadence with less force on each pedal stroke, at a lower speed", "It makes the bike lighter", "It reduces air drag", "It gives you more power for free"], a: 0,
      e: "Gears don't create power; they trade force for pedalling speed. A low gear lets you keep spinning at a sustainable cadence instead of grinding big forces through your knees." },
    { ch: "ch-brake",
      q: "Under hard braking, which brake can stop you faster, and what's the catch?",
      o: ["The rear brake; there's no catch", "The front brake, because weight shifts forward onto the front wheel; too much, too suddenly, can pitch you over the bars", "Neither brake matters", "Both are equal in every situation"], a: 1,
      e: "Braking shifts weight forward, giving the front tyre more grip and the rear less. Most stopping power is at the front, so learn to squeeze it progressively, with your weight back and low." },
    { ch: "ch-brake",
      q: "From 30 km/h, braking at half of gravity's acceleration (0.5 g), about how far do you travel after the brakes bite?",
      o: ["About 0.7 m", "About 70 m", "About 7 m", "About 700 m"], a: 2,
      e: "d = v² ÷ (2a) = 8.33² ÷ (2 × 4.9) ≈ 7.1 m. Add your reaction time: in one second at 30 km/h you cover another 8.3 m before you even start braking." },
    { ch: "ch-brake",
      q: "Cornering at 10 m/s (36 km/h) on a 20 m radius bend, about how far must you and the bike lean?",
      o: ["About 27°", "About 5°", "About 60°", "About 80°"], a: 0,
      e: "tan φ = v² ÷ (g r) = 100 ÷ (9.81 × 20) ≈ 0.51, so φ ≈ 27°. The tyres must supply that sideways grip: on gravel or a wet road, slow down before the bend." },
    { ch: "ch-trail",
      q: "Why do mountain bikers run lower tyre pressures than road cyclists?",
      o: ["Low pressure is always faster on tarmac", "It makes the bike lighter", "A softer tyre spreads over rocks and roots, giving a bigger contact patch for grip and absorbing small bumps", "It prevents every puncture"], a: 2,
      e: "On rough ground, a tyre that conforms to the surface keeps more rubber in contact and bounces less. Too low and the rim can hit rocks, so riders balance grip against rim and puncture protection." },
    { ch: "ch-trail",
      q: "Landing a 1 m drop, your legs and suspension slow you to a stop over about 0.25 m. Roughly what average deceleration is that?",
      o: ["About 1 g", "About 4 g", "About 40 g", "About 0.4 g"], a: 1,
      e: "Falling 1 m, you land at √(2 × 9.81 × 1) ≈ 4.4 m/s. Stopping over 0.25 m means average deceleration = height ÷ stopping distance × g = 4 g. More travel and bent legs spread it out." },
    { ch: "ch-trail",
      q: "How does a knobbly tyre on a dirt trail compare with a slick tyre on smooth road for rolling resistance?",
      o: ["About the same", "The trail tyre rolls easier", "There's no rolling resistance off-road", "Much higher: in our lab about five times the road value"], a: 3,
      e: "Soft ground deforms and knobs squirm, wasting energy. In our Power Lab, an upright rider on a trail at 200 W goes about 21 km/h, against about 28 km/h on the road in the same position." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- POWER LAB ----------
  // P = v·(Crr·m·g·cosθ + m·g·sinθ) + ½·ρ·CdA·v³, solved for v by bisection. ρ = 1.2 kg/m³ (near sea level).
  // No drivetrain losses or wind. CdA and Crr values are illustrative.
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("cy-p")) return;
    const g = 9.81, rho = 1.2;
    let cda = 0.32, crr = 0.005;
    function solve(P, th, m) {
      let lo = 0, hi = 40;
      for (let i = 0; i < 80; i++) {
        const v = (lo + hi) / 2;
        const need = v * (crr * m * g * Math.cos(th) + m * g * Math.sin(th)) + 0.5 * rho * cda * v * v * v;
        if (need > P) hi = v; else lo = v;
      }
      return lo;
    }
    function update() {
      const P = +$("cy-p").value, gr = +$("cy-g").value, m = +$("cy-m").value, th = Math.atan(gr / 100);
      $("cy-p-o").textContent = P + " W";
      $("cy-g-o").textContent = gr + "%";
      $("cy-m-o").textContent = m + " kg";
      const v = solve(P, th, m);
      const roll = v * crr * m * g * Math.cos(th), climb = v * m * g * Math.sin(th), drag = 0.5 * rho * cda * v * v * v, tot = roll + climb + drag;
      $("cy-v").textContent = (v * 3.6).toFixed(1) + " km/h";
      $("cy-wkg").textContent = (P / m).toFixed(2) + " W/kg";
      $("cy-drag").textContent = Math.round(drag / tot * 100) + "%";
      $("cy-climb").textContent = Math.round(climb / tot * 100) + "%";
      $("cy-roll").textContent = Math.round(roll / tot * 100) + "%";
      $("cy-t").textContent = (10000 / v / 60).toFixed(1) + " min";
      $("cy-vam").textContent = Math.round(v * Math.sin(th) * 3600).toLocaleString("en-IN") + " m/h";
      $("cy-bar").style.width = Math.min(100, v * 3.6 / 50 * 100).toFixed(0) + "%";
    }
    ["cy-p", "cy-g", "cy-m"].forEach(id => $(id).addEventListener("input", update));
    function seg(id, fn) {
      document.querySelectorAll("#" + id + " button").forEach(b => b.addEventListener("click", () => {
        fn(b);
        document.querySelectorAll("#" + id + " button").forEach(x => x.setAttribute("aria-pressed", x === b ? "true" : "false"));
        update();
      }));
    }
    seg("cy-pos", b => { cda = +b.dataset.cda; });
    seg("cy-surf", b => { crr = +b.dataset.crr; });
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
