// Kinetic: skydiving page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "skydiving",
    v1: "Physics: nailed it 🪂",
    b1: "You've got the physics of skydiving. Skim the chapters for anything you missed, then scroll to “Where to jump” for dropzones, courses and licences at your level. Knowing the science is a great start; it isn't the same as the training, emergency drills and canopy skills a dropzone teaches.",
    b2: "You have the basics. Fill the gaps below before your first jump, especially openings and canopy flight: they're the chapters that bring you down safely.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to jump at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, a skydiving licence or a substitute for a dropzone's training. Jump only with a currently authorised operator and qualified instructors, complete the full ground school and emergency drills, and follow the dropzone's medical and weather rules."
  };
  const CHAPTERS = {
    "ch-freefall": "Ch 1 · Free fall & terminal velocity",
    "ch-body":     "Ch 2 · Body position & fall rate",
    "ch-canopy":   "Ch 3 · Deployment & opening forces",
    "ch-glide":    "Ch 4 · Canopy flight: glide & flare",
    "ch-altitude": "Ch 5 · Altitude, air & oxygen",
    "ch-spot":     "Ch 6 · Wind drift, spotting & the rules"
  };
  const QUESTIONS = [
    { ch: "ch-freefall",
      q: "What is terminal velocity?",
      o: ["The speed at which air drag equals your weight, so you stop accelerating", "The speed of the aircraft at exit", "The speed you land at", "The speed of sound"], a: 0,
      e: "Drag ½ ρ CdA v² grows with speed until it equals m g. Then the net force is zero and your speed stays steady." },
    { ch: "ch-freefall",
      q: "About how fast is a typical belly-to-earth terminal velocity?",
      o: ["About 50 km/h", "About 193 km/h (120 mph)", "About 1,000 km/h", "About 20 km/h"], a: 1,
      e: "USPA's freefall table uses 120 mph (about 193 km/h) for belly-to-earth and 160 mph for faster positions; many factors affect the real figure." },
    { ch: "ch-freefall",
      q: "Using USPA's table, about how long does 10,000 ft of freefall take at 120 mph?",
      o: ["About 10 s", "About 5 minutes", "About 57 s", "About 2 s"], a: 2,
      e: "10,000 ft = 3,048 m; at 53.6 m/s that's about 57 s. The first few seconds after exit are slower while you speed up." },
    { ch: "ch-body",
      q: "Why does a head-down skydiver fall faster than a belly-to-earth one?",
      o: ["Gravity is stronger head-down", "The air is thinner", "They weigh more", "Their drag area (CdA) is smaller, so drag balances weight at a higher speed"], a: 3,
      e: "v_t = √(2 m g ÷ (ρ CdA)). Halve CdA and v_t rises by √2: in our lab, 0.56 → 0.31 m² takes you from about 193 to 257 km/h." },
    { ch: "ch-body",
      q: "Two skydivers in the same position: one 70 kg, one 110 kg (with gear). Who falls faster?",
      o: ["The 110 kg one: terminal velocity grows with √mass", "The 70 kg one", "Both the same", "Whoever exits first"], a: 0,
      e: "v_t ∝ √m. 193 km/h at 90 kg becomes about 170 km/h at 70 kg and 213 km/h at 110 kg. Groups match fall rates with jumpsuits and position." },
    { ch: "ch-body",
      q: "Why does a good arch keep you stable belly-down?",
      o: ["It makes you heavier", "It puts your centre of mass below your centre of drag, like a shuttlecock", "It reduces gravity", "It isn't needed"], a: 1,
      e: "With mass leading and drag trailing, any tilt makes a restoring turn. Moving arms and legs then lets you steer." },
    { ch: "ch-canopy",
      q: "What does the slider on a canopy's lines do?",
      o: ["Steers the canopy", "Holds the reserve", "Slows the inflation so the opening is spread over a few seconds", "Measures altitude"], a: 2,
      e: "A slower opening means a smaller deceleration and a lower force on you: F = m (Δv ÷ Δt + g)." },
    { ch: "ch-canopy",
      q: "Slowing a 90 kg jumper from 53.6 m/s to 5 m/s over 3 s: what's the average deceleration?",
      o: ["About 16 g", "About 0.1 g", "About 50 g", "About 1.65 g"], a: 3,
      e: "(53.6 − 5) ÷ 3 ≈ 16.2 m/s² ≈ 1.65 g. Add 1 g for gravity: an average harness load of about 2.65 g." },
    { ch: "ch-canopy",
      q: "What does an AAD (automatic activation device) do?",
      o: ["Opens the reserve automatically if you're still falling fast at a set low altitude", "Plays an altitude alarm only", "Steers the canopy to the landing area", "Releases the main canopy on landing"], a: 0,
      e: "It's a backup to the jumper's own actions. Rigs carry a main canopy, a reserve and often an AAD." },
    { ch: "ch-glide",
      q: "A canopy flies 12 m/s forward and sinks 5 m/s. What's its glide ratio in still air?",
      o: ["5 : 12", "2.4 : 1", "60 : 1", "1 : 1"], a: 1,
      e: "Glide ratio = forward speed ÷ sink rate = 12 ÷ 5 = 2.4 : 1." },
    { ch: "ch-glide",
      q: "Why do skydivers land into the wind?",
      o: ["It's prettier", "The canopy can't turn", "Wind pushes the canopy down", "It lowers groundspeed: 43 km/h airspeed into a 15 km/h wind gives about 28 km/h over the ground"], a: 3,
      e: "Downwind the same canopy would touch down at about 58 km/h, with about 4.3 times the kinetic energy." },
    { ch: "ch-altitude",
      q: "At 10,000 ft, about what share of sea-level air pressure is there?",
      o: ["About 69%", "100%", "About 20%", "About 95%"], a: 0,
      e: "Standard atmosphere: about 69.7 kPa, 68.8% of sea level. Oxygen's partial pressure falls in proportion, to about 14.6 kPa." },
    { ch: "ch-altitude",
      q: "Oxygen is still about 21% of the air at 13,000 ft. Why is there less for your body?",
      o: ["Oxygen turns into nitrogen", "The partial pressure of oxygen falls with total pressure, so each breath carries less", "Lungs shrink with altitude", "There's no less"], a: 1,
      e: "At 13,000 ft total pressure is about 61% of sea level, so oxygen's partial pressure falls to about 13 kPa." },
    { ch: "ch-spot",
      q: "Opening at 5,000 ft (1,524 m) and descending at 5 m/s in a 20 km/h wind, about how far will you drift?",
      o: ["About 17 m", "About 17 km", "About 1.7 km", "No drift at all"], a: 2,
      e: "1,524 ÷ 5 ≈ 305 s ≈ 0.085 h; × 20 km/h ≈ 1.7 km. That's why the aircraft drops you upwind of the landing area (spotting)." },
    { ch: "ch-spot",
      q: "How many jumps does a USPA A licence require?",
      o: ["1", "500", "25", "200"], a: 2,
      e: "25 freefall jumps, a completed A-licence progression card and exams. B needs 50, C 200 and D 500." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- FREEFALL LAB ----------
  // v_t = √(2 m g ÷ (ρ CdA)), ρ 1.1 (illustrative). From rest with quadratic drag:
  // fall h in t = (v_t/g)·acosh(exp(h g / v_t²)); 95% of v_t after (v_t/g)·atanh(0.95).
  // Canopy 5 m/s down; drift = wind × canopy time; pressure from the standard atmosphere.
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("sd-open")) return;
    const g = 9.81, rho = 1.1, FT = 0.3048;
    let exit = 10000, cda = 0.559;
    const fmt = n => Math.round(n).toLocaleString("en-US");
    function update() {
      const open = +$("sd-open").value, m = +$("sd-m").value, w = +$("sd-w").value;
      $("sd-open-o").textContent = fmt(open) + " ft";
      $("sd-m-o").textContent = m + " kg";
      $("sd-w-o").textContent = w + " km/h";
      const vt = Math.sqrt(2 * m * g / (rho * cda));
      const h = (exit - open) * FT, tff = vt / g * Math.acosh(Math.exp(h * g / (vt * vt)));
      const p = Math.pow(1 - 2.25577e-5 * exit * FT, 5.25588);
      const tcan = open * FT / 5;
      $("sd-vt").textContent = Math.round(vt * 3.6) + " km/h";
      $("sd-t95").textContent = (vt / g * Math.atanh(0.95)).toFixed(1) + " s";
      $("sd-ff").textContent = Math.round(tff) + " s";
      $("sd-p").textContent = (p * 100).toFixed(1) + "%";
      $("sd-can").textContent = (tcan / 60).toFixed(1) + " min";
      $("sd-drift").textContent = (w * tcan / 3600).toFixed(2) + " km";
      $("sd-bar").style.width = Math.min(100, tff / 75 * 100) + "%";
    }
    ["sd-open", "sd-m", "sd-w"].forEach(id => $(id).addEventListener("input", update));
    [["sd-exit", "ft"], ["sd-pos", "cda"]].forEach(([grp, key]) => document.querySelectorAll("#" + grp + " button").forEach(b => b.addEventListener("click", () => {
      if (key === "ft") exit = +b.dataset.ft; else cda = +b.dataset.cda;
      document.querySelectorAll("#" + grp + " button").forEach(x => x.setAttribute("aria-pressed", x === b ? "true" : "false"));
      update();
    })));
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
