// Kinetic: kayaking-rafting page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "kayaking-rafting",
    v1: "Physics: nailed it 🛶",
    b1: "You've got the physics of moving water. Skim the chapters for anything you missed, then scroll to “Where to go” for rafting runs, kayak courses and guide training at your level. Knowing the science is a great start; it isn't the same as reading a real rapid.",
    b2: "You have the basics. Fill the gaps below before your next trip, especially the chapters on the force of moving water and on holes and strainers: they're the ones that keep you safe if you swim.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to paddle at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, a river-guide or safety-kayaker qualification, or a judgement of which grade of river you can handle. Raft only with a licensed operator and certified guides, always wear the life jacket and helmet they give you, follow the safety briefing, and learn kayaking from a certified instructor on easy water first."
  };
  const CHAPTERS = {
    "ch-flow":    "Ch 1 · How rivers flow",
    "ch-force":   "Ch 2 · The force of moving water",
    "ch-float":   "Ch 3 · Buoyancy & life jackets",
    "ch-ferry":   "Ch 4 · Ferry glides & eddies",
    "ch-hazards": "Ch 5 · Holes, strainers & swimming",
    "ch-boats":   "Ch 6 · Boats, balance & the roll"
  };
  const QUESTIONS = [
    { ch: "ch-flow",
      q: "A river 40 m wide and 2 m deep flows at 1.5 m/s. It squeezes through a gap 20 m wide, still 2 m deep. Roughly how fast does it flow there?",
      o: ["0.75 m/s", "1.5 m/s", "3 m/s", "6 m/s"], a: 2,
      e: "The same volume per second (discharge, Q = width × depth × speed = 120 m³/s) must get through. Halve the width at the same depth and the speed doubles, to 3 m/s. Narrow, steep sections are where rapids form." },
    { ch: "ch-flow",
      q: "On the International Scale of River Difficulty, what does Class (Grade) VI mean?",
      o: ["Runs of extreme difficulty and danger, rarely attempted", "The easiest flat water", "A grade for children", "A lake"], a: 0,
      e: "The scale runs from Class I (easy, moving water with small waves) to Class VI (extreme and exploratory). American Whitewater warns that ratings are not exact and that difficulty changes with water level, cold water and remoteness." },
    { ch: "ch-flow",
      q: "Why does Kundalika rafting at Kolad depend on the time of day?",
      o: ["The river only flows at night", "Water released from the upstream Bhira dam raises the flow for rafting", "Tides from the sea", "The rapids are switched on by the operators"], a: 1,
      e: "Kolad's rafting runs on water released from the Bhira (Tata Power) dam, usually in the morning. More water means more discharge, so faster flow and bigger waves through the rapids." },
    { ch: "ch-force",
      q: "Water pushing on a swimmer pinned against a rock: the force grows with speed squared (F = ½ρC<sub>d</sub>Av²). What happens if the current doubles from 1.5 m/s to 3 m/s?",
      o: ["The force doubles", "The force stays the same", "The force halves", "The force roughly quadruples"], a: 3,
      e: "Speed squared: 2² = 4. In our worked example, the push on a swimmer's body rises from about 560 N to about 2,250 N, more than a large adult's weight. Water that looks only 'twice as fast' is four times as strong." },
    { ch: "ch-force",
      q: "Why should you never try to stand up in fast-moving water deeper than your knees?",
      o: ["Your foot can get trapped between rocks and the current can push you over and hold you under", "It's against the rules of rafting only", "Standing makes you float higher", "It scares the fish"], a: 0,
      e: "Foot entrapment is one of the most dangerous river accidents. The current's force (Ch 2) can fold you over a trapped foot and hold you down. Float on your back, feet up and pointing downstream, until you reach slow or shallow water." },
    { ch: "ch-float",
      q: "Whitewater full of air bubbles is less dense than clear water. What does that do to the buoyancy a life jacket and your body get?",
      o: ["It increases it", "It reduces it, so you float lower in aerated water", "No change at all", "It makes you sink like a stone even with a life jacket"], a: 1,
      e: "Buoyancy equals the weight of fluid displaced. If foamy water is, say, 30% air, it weighs 30% less per litre and gives about 30% less lift. That's why you sit lower in the foam below a rapid, and why a well-fitted life jacket matters." },
    { ch: "ch-float",
      q: "Why must a life jacket be fastened snugly, not worn loose?",
      o: ["It looks neater", "A loose jacket weighs more", "If it's loose, the buoyancy pushes the jacket up around your face or pulls it off, instead of lifting you", "Loose jackets float better"], a: 2,
      e: "The jacket's buoyancy pushes it upward. If it isn't snug, it rides up over your chin (or comes off) and your head sits lower. Guides check the fit by pulling up on the shoulder straps: it shouldn't lift past your ears." },
    { ch: "ch-ferry",
      q: "You paddle a kayak at 2 m/s through the water. The current is 1.5 m/s. To cross straight to the opposite bank, how should you point the boat?",
      o: ["Straight across", "Downstream", "Angled upstream, at about 49° from straight across", "Straight upstream"], a: 2,
      e: "To cancel the current, the upstream part of your velocity must equal 1.5 m/s: sin θ = 1.5 ÷ 2, so θ ≈ 49°. What's left, √(2² − 1.5²) ≈ 1.3 m/s, carries you across. This is a ferry glide." },
    { ch: "ch-ferry",
      q: "What is an eddy?",
      o: ["A type of paddle", "The fastest part of a rapid", "A grade of river", "A slower area behind a rock or bend where water can flow back upstream, useful for resting and stopping"], a: 3,
      e: "Water flowing past an obstacle leaves a sheltered zone behind it where the current is slow or circulates upstream. Paddlers 'catch' eddies to stop, scout and regroup. The boundary, the eddy line, has strong shear and can tip a careless boat." },
    { ch: "ch-ferry",
      q: "You point your kayak straight across a 40 m river flowing at 1.5 m/s and paddle at 2 m/s. How far downstream do you land?",
      o: ["None", "About 30 m", "About 3 m", "About 300 m"], a: 1,
      e: "It takes 40 ÷ 2 = 20 s to cross, and in that time the current carries you 1.5 × 20 = 30 m downstream. If there's a rapid below, that's a big difference." },
    { ch: "ch-hazards",
      q: "What is a 'hole' (or hydraulic) on a river?",
      o: ["A place where water pours over a drop and recirculates back upstream at the surface, which can hold a swimmer or boat", "A gap in a raft", "A calm pool", "A sign on the riverbank"], a: 0,
      e: "Water falling over a rock or ledge plunges down, then part of it flows back upstream on the surface. A boat or swimmer can be held in that recirculation. Uniform weirs and low-head dams create especially dangerous, even holes." },
    { ch: "ch-hazards",
      q: "What is a 'strainer', and why is it so dangerous?",
      o: ["A fallen tree or debris that lets water through but stops people and boats, pinning them under the current's force", "A water filter carried on rafts", "A fast but harmless wave", "A shallow sandbank"], a: 0,
      e: "Water flows through branches; you don't. The current's force (Ch 2) pins you against the obstacle. Swim aggressively away from strainers, and if you can't avoid one, approach it head-first and try to climb over it." },
    { ch: "ch-hazards",
      q: "Water falls over a 2 m drop. About how fast is it moving at the bottom, ignoring friction?",
      o: ["About 1 m/s", "About 6 m/s", "About 20 m/s", "About 60 m/s"], a: 1,
      e: "v = √(2gh) = √(2 × 9.81 × 2) ≈ 6.3 m/s. With drag growing with speed squared, that's why the base of even a modest drop is powerful." },
    { ch: "ch-boats",
      q: "Why do rafters 'high-side' (throw their weight to the downstream tube) when a raft is pinned against a rock?",
      o: ["To make the raft lighter", "To slow the river", "To keep warm", "To stop the upstream tube being pulled down by the current, which could flip or wrap the raft"], a: 3,
      e: "When a raft hits a rock sideways, the current piles onto the upstream tube and drags it under. Moving weight to the downstream (rock) side lifts the upstream tube so water flows under it rather than into the boat. Follow your guide's commands." },
    { ch: "ch-boats",
      q: "In a kayak roll, what mainly turns the boat upright again?",
      o: ["Pulling hard on the paddle alone", "Waiting for the current", "A 'hip snap': twisting the hips to rotate the boat while the body stays low and the head comes up last", "Getting out and climbing back in"], a: 2,
      e: "Your hips rotate the boat while the paddle provides a brief support on the surface. Keeping the head down and body close to the water keeps the centre of mass low, so very little lift is needed. Rolls are learned on flat water with an instructor first." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- RIVER LAB ----------
  // Discharge Q = width × depth × speed (rectangular channel). Drag on a pinned swimmer F = ½ρCdAv², ρ = 1000, Cd·A = 0.5 m² (illustrative).
  // Ferry glide: aim angle asin(v/b) upstream, crossing speed √(b² − v²); pointing straight across drifts v × width ÷ b.
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("kr-v")) return;
    let boat = 2.0;
    function update() {
      const v = +$("kr-v").value, w = +$("kr-w").value, d = +$("kr-d").value;
      $("kr-v-o").textContent = v.toFixed(1) + " m/s";
      $("kr-w-o").textContent = w + " m";
      $("kr-d-o").textContent = d.toFixed(1) + " m";
      $("kr-q").textContent = Math.round(w * d * v).toLocaleString("en-IN") + " m³/s";
      const F = 0.5 * 1000 * 0.5 * v * v;
      $("kr-f").textContent = Math.round(F).toLocaleString("en-IN") + " N";
      $("kr-f").style.color = F >= 1500 ? "#ff8a70" : (F >= 700 ? "#ffd27a" : "#fff");
      $("kr-x").textContent = (v * v).toFixed(2) + " ×";
      $("kr-drift").textContent = Math.round(v * w / boat) + " m";
      $("kr-tst").textContent = (w / boat).toFixed(1) + " s";
      if (v < boat) {
        const th = Math.asin(v / boat) * 180 / Math.PI, gs = Math.sqrt(boat * boat - v * v);
        $("kr-ang").textContent = th.toFixed(0) + "° upstream";
        $("kr-ang-s").textContent = "Ch 4 · sin θ = current ÷ boat speed";
        $("kr-tf").textContent = (w / gs).toFixed(1) + " s";
      } else {
        $("kr-ang").textContent = "can't hold a line";
        $("kr-ang-s").textContent = "current ≥ boat speed: you'll drift downstream";
        $("kr-tf").textContent = "—";
      }
      $("kr-bar").style.width = Math.min(100, F / 3000 * 100).toFixed(0) + "%";
    }
    ["kr-v", "kr-w", "kr-d"].forEach(id => $(id).addEventListener("input", update));
    document.querySelectorAll("#kr-boat button").forEach(b => b.addEventListener("click", () => {
      boat = +b.dataset.b;
      document.querySelectorAll("#kr-boat button").forEach(x => x.setAttribute("aria-pressed", x === b ? "true" : "false"));
      update();
    }));
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
