// Kinetic: skiing-snowboarding page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "skiing-snowboarding",
    v1: "Physics: nailed it ⛷️",
    b1: "You've got the physics of sliding on snow. Skim the chapters for anything you missed, then scroll to “Where to go” for ski and snowboard courses at your level. Knowing the science is a great start; it isn't the same as skill, fitness or reading a mountain.",
    b2: "You have the basics. Fill the gaps below before your next trip, especially speed control and avalanches: they're the chapters that keep you and other skiers safe.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to ski at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, a course grade or a judgement of which slopes you can ski, and a high score does not prepare you for off-piste terrain. Learn on a course with qualified instructors, wear a helmet, ski in control, and never go off-piste or into avalanche terrain without avalanche training, the right equipment and a qualified guide."
  };
  const CHAPTERS = {
    "ch-slope":   "Ch 1 · Gravity on a slope",
    "ch-snow":    "Ch 2 · Friction & the snow",
    "ch-drag":    "Ch 3 · Air drag & top speed",
    "ch-turns":   "Ch 4 · Edges, turns & speed control",
    "ch-falls":   "Ch 5 · Falls, collisions & avalanches",
    "ch-cold":    "Ch 6 · Cold, altitude & sun"
  };
  const QUESTIONS = [
    { ch: "ch-slope",
      q: "On a slope at angle θ, which part of your weight pulls you down the hill?",
      o: ["mg cos θ", "mg sin θ", "mg tan θ", "All of it, mg"], a: 1,
      e: "Gravity splits into mg sin θ along the slope (pulling you down it) and mg cos θ into the slope (pressing you onto the snow). On a 15° slope, sin 15° ≈ 0.26, so about a quarter of your weight pulls you downhill." },
    { ch: "ch-slope",
      q: "A slope is described as 27% steep. What does that mean?",
      o: ["It drops 27 m for every 100 m you move horizontally (about 15°)", "It's 27° steep", "27% of skiers fall on it", "It's 27% covered in snow"], a: 0,
      e: "Percent gradient = rise ÷ run × 100 = tan θ × 100. tan 15° ≈ 0.27, so 27% ≈ 15°. A 100% slope is 45°: much steeper than most people think." },
    { ch: "ch-slope",
      q: "Ignoring air drag, a skier on a 15° slope (friction coefficient 0.05) accelerates at about 2.1 m/s². How fast would they be going after 50 m, if they didn't turn?",
      o: ["About 5 km/h", "About 15 km/h", "About 52 km/h", "About 200 km/h"], a: 2,
      e: "v = √(2as) = √(2 × 2.07 × 50) ≈ 14.4 m/s ≈ 52 km/h. On even a moderate slope, speed builds very quickly. Turning is how you control it." },
    { ch: "ch-snow",
      q: "Why do skis slide so easily on snow?",
      o: ["Snow is perfectly smooth", "Skis are magnetic", "The snow pushes them along", "A very thin film of meltwater from frictional heating lubricates the base"], a: 3,
      e: "Friction heats the contact and melts a microscopic water layer that lubricates the base; wax and a smooth base help. Very cold, dry snow gives less melt and feels slower; wet spring snow can feel sticky because of suction." },
    { ch: "ch-snow",
      q: "Why does a 'snow plough' (pizza) slow a beginner down?",
      o: ["Pushing the ski tails apart puts the skis on their inside edges at an angle to the direction of travel, so they scrape snow and brake", "It makes the skier lighter", "It lowers air pressure", "It lifts the skis off the snow"], a: 0,
      e: "Each ski points across the fall line a little and digs in on its inside edge, so it pushes snow sideways and creates braking force. It's day 3 of IISM Gulmarg's basic syllabus: snow plough, then snow plough turns." },
    { ch: "ch-drag",
      q: "Air drag grows with speed squared. Why does tucking into a crouch let a skier go faster?",
      o: ["It increases friction", "It increases gravity", "It shrinks the frontal area and drag, so gravity is balanced at a higher speed", "It makes the slope steeper"], a: 2,
      e: "Top speed is reached when gravity along the slope equals friction plus drag (½ρC<sub>d</sub>Av²). Halve the C<sub>d</sub>A and the top speed rises by about √2. In our Slope Lab, tucking on a 15° slope raises top speed from about 86 to about 133 km/h." },
    { ch: "ch-drag",
      q: "Gulmarg's gondola top station is at 3,980 m. The air there is about 61% of sea-level pressure. How does that affect drag?",
      o: ["Drag is higher", "Thinner air means less drag at the same speed", "Drag doesn't depend on air", "Drag doubles"], a: 1,
      e: "Drag is proportional to air density. Thinner, high-altitude air gives less drag, so you can go a little faster for the same slope. It also holds less oxygen, which is why you tire faster (Ch 6)." },
    { ch: "ch-turns",
      q: "Making a turn of radius 15 m at 10 m/s (36 km/h), about how far must you lean into the turn?",
      o: ["About 5°", "About 15°", "About 75°", "About 34°"], a: 3,
      e: "Lean angle: tan φ = v² ÷ (g r) = 100 ÷ (9.81 × 15) ≈ 0.68, so φ ≈ 34°. Faster or tighter turns need more lean and more edge grip." },
    { ch: "ch-turns",
      q: "How do linked turns control your speed on a steep slope?",
      o: ["Each turn takes you across the fall line, where gravity's pull along your path is smaller, and edging scrubs off speed", "Turns make gravity weaker", "Turning makes the slope flatter", "They don't; only stopping does"], a: 0,
      e: "Skiing across the slope means a much gentler effective gradient along your path, and edging through the turn converts kinetic energy into friction heat. Turn shape is your speed controller." },
    { ch: "ch-turns",
      q: "What does a ski's edge do in a carved turn?",
      o: ["Nothing; the base does all the work", "It cuts into the snow so the ski grips sideways and follows its curved sidecut, providing the inward force for the turn", "It melts the snow", "It slows the ski only"], a: 1,
      e: "Tilt a ski on edge and the sidecut (narrower waist, wider tip and tail) makes it bend into an arc. The edge grips, supplying the centripetal force mv²/r that curves your path." },
    { ch: "ch-falls",
      q: "A 75 kg skier moving at 15 m/s (54 km/h) has how much kinetic energy?",
      o: ["About 84 J", "About 840 J", "About 8.4 kJ", "About 84 kJ"], a: 2,
      e: "½ × 75 × 15² ≈ 8,400 J. A collision has to absorb all of that: about the same energy as falling from 11 m. That's why speed control and helmets matter." },
    { ch: "ch-falls",
      q: "Slab avalanches most commonly release on slopes of roughly what steepness?",
      o: ["About 30°–45°", "Under 10°", "Exactly 90°", "Only on flat ground"], a: 0,
      e: "Most slab avalanches start on slopes of about 30°–45°: steep enough for snow to slide, not so steep that it sloughs off constantly. Gulmarg's high terrain is avalanche country; go off-piste only with training, equipment and a guide." },
    { ch: "ch-falls",
      q: "Who has priority on a ski slope?",
      o: ["The fastest skier", "The skier behind", "The skier ahead and below you: the uphill skier must avoid them", "Snowboarders only"], a: 2,
      e: "The skier below can't see you, so it's your job to give them room. Stop where you're visible from above, and look uphill before setting off." },
    { ch: "ch-cold",
      q: "At Gulmarg's top station (3,980 m), air pressure is about 61% of sea level. What does that mean for each breath?",
      o: ["More oxygen", "About 39% less oxygen per breath than at sea level", "No change", "The air has no oxygen"], a: 1,
      e: "Oxygen is still 21% of the air, but at 61% of the pressure there's about 39% less oxygen in each breath. Expect to tire faster, climb gently, and watch for altitude sickness." },
    { ch: "ch-cold",
      q: "Why do skiers get sunburnt so easily even when it's freezing?",
      o: ["Cold air burns skin", "Ski jackets attract sunlight", "Snow absorbs all the sunlight", "Snow reflects much of the sunlight back up, and UV is stronger at altitude"], a: 3,
      e: "Fresh snow reflects most of the sunlight, so you get UV from above and below, and thinner air at altitude filters less of it. Sunglasses or goggles prevent snow blindness; use sunscreen on your face." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- SLOPE LAB ----------
  // Along the slope: mg sinθ − μ mg cosθ − ½ρCdA v² = m a. Air density 0.909 kg/m³ (ISA, ≈ 3,000 m).
  // Speed after 50 m ignores drag; top speed balances gravity, friction and drag. μ and CdA values are illustrative.
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("sn-angle")) return;
    const g = 9.81, rho = 0.909;
    let mu = 0.05, cda = 0.6;
    function update() {
      const th = +$("sn-angle").value, m = +$("sn-mass").value, t = th * Math.PI / 180;
      $("sn-angle-o").textContent = th + "°";
      $("sn-mass-o").textContent = m + " kg";
      $("sn-pct").textContent = Math.round(Math.tan(t) * 100) + "%";
      const G = m * g * Math.sin(t), Fr = mu * m * g * Math.cos(t), a = g * (Math.sin(t) - mu * Math.cos(t));
      $("sn-grav").textContent = Math.round(G) + " N";
      $("sn-fric").textContent = Math.round(Fr) + " N";
      if (a > 0) {
        $("sn-acc").textContent = a.toFixed(2) + " m/s²";
        $("sn-v50").textContent = (Math.sqrt(2 * a * 50) * 3.6).toFixed(1) + " km/h";
        const vt = Math.sqrt(2 * (G - Fr) / (rho * cda)) * 3.6;
        $("sn-vt").textContent = vt.toFixed(1) + " km/h";
        $("sn-vt").style.color = vt >= 100 ? "#ff8a70" : (vt >= 60 ? "#ffd27a" : "#fff");
        $("sn-bar").style.width = Math.min(100, vt / 140 * 100).toFixed(0) + "%";
      } else {
        $("sn-acc").textContent = "won't slide";
        $("sn-v50").textContent = "0 km/h";
        $("sn-vt").textContent = "0 km/h";
        $("sn-vt").style.color = "#fff";
        $("sn-bar").style.width = "0%";
      }
    }
    ["sn-angle", "sn-mass"].forEach(id => $(id).addEventListener("input", update));
    function seg(id, fn) {
      document.querySelectorAll("#" + id + " button").forEach(b => b.addEventListener("click", () => {
        fn(b);
        document.querySelectorAll("#" + id + " button").forEach(x => x.setAttribute("aria-pressed", x === b ? "true" : "false"));
        update();
      }));
    }
    seg("sn-snow", b => { mu = +b.dataset.mu; });
    seg("sn-pos", b => { cda = +b.dataset.cda; });
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
