// Kinetic: ice-skating page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "ice-skating",
    v1: "Physics: nailed it ⛸️",
    b1: "You've got the physics. Skim the chapters for what you missed, then scroll to “Where to skate” to find a rink and lessons at your level. Knowing the physics is a great start; it is not the same as having the skill on the ice.",
    b2: "You have the basics. Fill the gaps below before your next session, and every glide, edge and spin will make a lot more sense.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to skate at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, a skating level or test, or a fitness assessment, and a high score says nothing about how well you can skate. Learn on the ice from a qualified coach at a supervised rink, follow the rink's rules, and on natural ice follow local safety advice and the people who manage it."
  };
  const CHAPTERS = {
    "ch-slippery": "Ch 1 · Why is ice slippery?",
    "ch-edges":    "Ch 2 · Edges, lean & curves",
    "ch-glide":    "Ch 3 · Push, glide & drag",
    "ch-spins":    "Ch 4 · Spins & angular momentum",
    "ch-jumps":    "Ch 5 · Jumps & landings",
    "ch-stop":     "Ch 6 · Stopping, falling & the ice itself"
  };
  const QUESTIONS = [
    { ch: "ch-slippery",
      q: "The classic textbook story says blade pressure melts the ice. For a 70 kg skater on about 200 mm² of blade contact, how much does that pressure lower the melting point?",
      o: ["About 10 °C, enough to skate down to −10 °C", "About 5 °C", "Only about 0.25 °C: far too little to explain skating on ice at −10 °C", "It raises the melting point instead"], a: 2,
      e: "Pressure = 686 N ÷ 0.0002 m² ≈ 3.4 MPa (34 bar). Ice's melting point drops by only about 0.0074 °C per bar, so ≈ 0.25 °C. Even a tiny 50 mm² contact gives only ≈ 1 °C. Pressure melting cannot be the main reason ice is slippery." },
    { ch: "ch-slippery",
      q: "So what do physicists currently say makes ice slippery?",
      o: ["It's still debated. A thin, liquid-like 'premelted' surface layer, heat from friction, and the sliding itself disordering the surface all compete as explanations", "It's settled: pressure melting alone", "Humidity in the air condenses into a water film", "Ice has exactly zero friction"], a: 0,
      e: "Ice surfaces carry a nanometres-thin, mobile layer even below 0 °C (premelting). Sliding generates heat that can make more meltwater. Recent experiments and simulations argue over how much of the low friction is liquid water versus a mobile or amorphous (disordered) solid surface. Chapter 1 sets out the debate honestly." },
    { ch: "ch-slippery",
      q: "Lab tests (Weber, Bonn and colleagues, 2018) found ice friction is lowest at about −7 °C, the temperature used for speed-skating rinks. Why does it get worse closer to 0 °C?",
      o: ["Warmer ice has fewer mobile surface molecules", "The ice gets softer, so the blade digs in deeper and ploughs", "Water freezes onto the blade", "Air is denser"], a: 1,
      e: "In their study, surface mobility kept rising toward 0 °C, but between −7 °C and 0 °C the ice softens and the slider sinks in more, so friction rises. Colder than −7 °C, fewer mobile surface molecules means more friction." },
    { ch: "ch-edges",
      q: "Why does a skater lean into a curve?",
      o: ["To look graceful", "To lower air drag", "So the ice's push on the blade points both up and sideways. The sideways part supplies the centripetal force that bends the path", "To stop the blade melting"], a: 2,
      e: "To travel in a circle you need a net force toward the centre (m·v²/r). Leaning tilts the blade's contact force so it has an inward component, and the blade's edge grips sideways. The lean angle satisfies tan θ = v² / (g·r)." },
    { ch: "ch-edges",
      q: "Skating a 3 m-radius circle at 4 m/s (14.4 km/h), roughly what centripetal acceleration and lean angle are needed?",
      o: ["≈ 5.3 m/s², leaning ≈ 28° from vertical", "≈ 1.3 m/s², leaning ≈ 7°", "≈ 12 m/s², leaning ≈ 50°", "None: on ice you don't need to lean"], a: 0,
      e: "a = v²/r = 16/3 ≈ 5.3 m/s² (more than half of g). tan θ = 5.3/9.81 ≈ 0.54 → θ ≈ 28°. For a 70 kg skater the blade carries ≈ 70 × √(9.81² + 5.3²) ≈ 780 N, about 1.14× body weight." },
    { ch: "ch-edges",
      q: "What are the 'edges' on a figure-skating blade?",
      o: ["The toe picks at the front", "The front and back ends of the blade", "Plastic guards that protect the blade", "The two sides of a hollow ground groove along the blade (inside and outside edge), which bite sideways into the ice"], a: 3,
      e: "Blades are ground with a shallow concave 'hollow' along their length, leaving two sharp edges. Tilt onto one and it cuts a curved groove; the ice then pushes sideways on it. This is how you steer, push and turn." },
    { ch: "ch-glide",
      q: "Ice friction for a skate is tiny: a coefficient of roughly 0.005. For a 70 kg skater, about how big is the friction force?",
      o: ["About 34 N", "About 340 N", "About 0.34 N", "About 3.4 N, roughly the weight of a 350 g bottle of water"], a: 3,
      e: "Friction = μ × weight = 0.005 × 686 N ≈ 3.4 N. That alone would only decelerate you at ≈ 0.05 m/s², so from 5 m/s you'd coast about 250 m if nothing else slowed you." },
    { ch: "ch-glide",
      q: "A recreational skater glides upright at 5 m/s (18 km/h). What slows them down the most?",
      o: ["Ice friction", "Air drag: roughly twice the ice friction at this speed, and it grows with speed squared", "Gravity", "The cold"], a: 1,
      e: "Drag = ½ × 1.2 × 5² × (CdA ≈ 0.5 m² upright) ≈ 7.5 N, about twice the 3.4 N of ice friction. That's why speed skaters crouch: tucking roughly halves the frontal area." },
    { ch: "ch-spins",
      q: "A skater spinning at 2 revolutions per second pulls in their arms, cutting their moment of inertia from 3.0 to 1.0 kg·m². Roughly how fast do they spin now?",
      o: ["Still 2 rev/s", "About 6 rev/s", "About 4 rev/s", "About 18 rev/s"], a: 1,
      e: "With almost no outside torque, angular momentum L = I × ω is conserved. I falls 3×, so ω rises 3×: 2 → 6 rev/s." },
    { ch: "ch-spins",
      q: "In that spin, rotational kinetic energy triples (from ≈ 237 J to ≈ 711 J). Where does the extra energy come from?",
      o: ["The skater's muscles: they do work pulling their arms and legs inward against the 'outward' pull of the spin", "Heat from the ice", "The air around them", "Nowhere: energy doesn't actually change"], a: 0,
      e: "KE = ½Iω² = L²/(2I). With L fixed, smaller I means more energy. That energy is the work the skater's muscles do drawing mass inward. You can feel it on a spinning office chair with weights in your hands." },
    { ch: "ch-jumps",
      q: "A skater's centre of mass rises 0.5 m in a jump. Roughly how long are they in the air?",
      o: ["About 0.32 s", "About 1.0 s", "About 0.64 s", "About 2 s"], a: 2,
      e: "Time to rise h is √(2h/g) = √(1/9.81) ≈ 0.32 s; the fall takes the same again, so ≈ 0.64 s total. Airtime grows only with √height: doubling the height buys just 41% more time." },
    { ch: "ch-jumps",
      q: "Once a skater has left the ice, why can't they start rotating more?",
      o: ["Air resistance is too strong", "The blade is no longer sharp", "They can, by waving their arms in circles", "Angular momentum is conserved in the air. The only way to turn faster is to pull into a tighter position, lowering moment of inertia"], a: 3,
      e: "With no ice to push against, there is no external torque. Total angular momentum is fixed at take-off. Skaters 'wrap' tightly to spin fast, then open out before landing to slow the rotation." },
    { ch: "ch-jumps",
      q: "Landing from a 0.5 m jump, a skater bends the knee so their centre of mass stops over about 0.25 m. What's the average force on the landing leg?",
      o: ["About 3× body weight", "About the same as body weight", "About 10× body weight", "About half of body weight"], a: 0,
      e: "Landing speed = √(2 × 9.81 × 0.5) ≈ 3.1 m/s. Stopping over 0.25 m needs ≈ 19.6 m/s² (2 g) of deceleration, plus 1 g to hold you up: ≈ 3 g on average, with higher peaks. Bend less and the force climbs fast." },
    { ch: "ch-stop",
      q: "What is a hockey stop doing, physically?",
      o: ["Digging the toe picks in like an anchor", "Turning both blades sideways so they skid across the ice. Scraping friction turns kinetic energy into heat and ice shavings ('snow')", "Creating air drag with the arms", "Melting the ice by pressure"], a: 1,
      e: "Sideways, the blade no longer glides on its length; it scrapes. Friction rises enormously and the stop happens within a few metres. That spray of 'snow' is the shaved ice carrying away some of that energy." },
    { ch: "ch-stop",
      q: "Coaches teach beginners to bend their knees and 'sit' slightly to the side when they feel a fall coming. What's the physics?",
      o: ["It looks less embarrassing", "The ice is softer near the boards", "Lowering the centre of mass shortens the drop and lands you on the padded hip and thigh over a longer distance, instead of the wrist or head", "It increases friction so you stop sliding"], a: 2,
      e: "Impact speed depends on drop height (v = √(2gh)): from 1 m it's ≈ 4.4 m/s, from 0.5 m it's ≈ 3.1 m/s. Landing on larger, padded areas spreads force over time and area. Many rinks and coaches also recommend helmets for beginners." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- SPIN & JUMP LAB ----------
  // Illustrative model: angular momentum conserved (no friction torque); jump = vertical projectile of the centre of mass.
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("sj-w0")) return;
    const g = 9.81;
    function fmt(x, d) { return x.toFixed(d); }
    function update() {
      const w0 = +$("sj-w0").value, I0 = +$("sj-i0").value, I1 = Math.min(+$("sj-i1").value, I0);
      const h = +$("sj-h").value, m = +$("sj-m").value, bend = +$("sj-bend").value;
      $("sj-w0-o").textContent = fmt(w0, 1) + " rev/s";
      $("sj-i0-o").textContent = fmt(I0, 1) + " kg·m²";
      $("sj-i1-o").textContent = fmt(+$("sj-i1").value, 1) + " kg·m²";
      $("sj-h-o").textContent = fmt(h, 2) + " m";
      $("sj-m-o").textContent = m + " kg";
      $("sj-bend-o").textContent = fmt(bend, 2) + " m";
      const w1 = w0 * I0 / I1;
      const ke0 = 0.5 * I0 * Math.pow(2 * Math.PI * w0, 2), ke1 = 0.5 * I1 * Math.pow(2 * Math.PI * w1, 2);
      const vUp = Math.sqrt(2 * g * h), air = 2 * vUp / g;
      const revs = w1 * air;
      const landG = 1 + h / bend;
      $("sj-w1").textContent = fmt(w1, 1) + " rev/s";
      $("sj-rpm").textContent = Math.round(w1 * 60) + " rpm";
      $("sj-ke").textContent = Math.round(ke0) + " → " + Math.round(ke1) + " J";
      $("sj-work").textContent = Math.round(ke1 - ke0) + " J";
      $("sj-vup").textContent = fmt(vUp, 2) + " m/s";
      $("sj-air").textContent = fmt(air, 2) + " s";
      $("sj-revs").textContent = fmt(revs, 1) + " rev";
      $("sj-land").textContent = "≈ " + fmt(landG, 1) + "× body weight";
      $("sj-energy").textContent = Math.round(m * g * h) + " J";
      $("sj-bar").style.width = Math.min(100, revs / 4.5 * 100) + "%";
    }
    ["sj-w0", "sj-i0", "sj-i1", "sj-h", "sj-m", "sj-bend"].forEach(id => $(id).addEventListener("input", update));
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
