// Kinetic: motorsport-karting page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "motorsport-karting",
    v1: "Physics: nailed it 🏁",
    b1: "You've got the physics of grip, corners, braking and downforce. Skim the chapters for anything you missed, then scroll to “Where to drive” for your next step. Knowing the science is a great start; on track, the marshals' flags, the briefing and your licence grade still set the limits.",
    b2: "You have the basics. Fill the gaps below before your first session, especially grip and braking: they're the chapters that explain why the limit arrives so suddenly.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to drive at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification and not a racing licence: competition licences in India are issued by FMSCI. Drive only on closed tracks, follow the briefing and the marshals' flags, wear the safety gear the track requires, and never race on public roads."
  };
  const CHAPTERS = {
    "ch-grip":     "Ch 1 · Tyre grip, slip angle & the friction circle",
    "ch-corner":   "Ch 2 · Cornering force: m v² ÷ r",
    "ch-transfer": "Ch 3 · Weight transfer",
    "ch-line":     "Ch 4 · The racing line & the apex",
    "ch-brake":    "Ch 5 · Braking distance & g-forces on the driver",
    "ch-aero":     "Ch 6 · Downforce & tyre temperature"
  };
  const QUESTIONS = [
    { ch: "ch-grip",
      q: "A tyre's total grip is shared between braking and cornering (the friction circle). If you use 80% of it for braking, about how much is left for cornering?",
      o: ["About 60%", "About 20%", "About 80%", "None at all"], a: 0,
      e: "The forces add like the sides of a right-angled triangle: √(1 − 0.8²) = 0.6, so about 60% is left, not 20%." },
    { ch: "ch-grip",
      q: "What is a tyre's slip angle?",
      o: ["The banking angle of the track", "The tilt (camber) of the wheel", "The angle between the way the wheel points and the way the tyre is actually travelling", "How far the steering wheel is turned"], a: 2,
      e: "A cornering tyre runs a few degrees off the direction it points. The rubber twists in the contact patch, and that twist is what makes the sideways force." },
    { ch: "ch-corner",
      q: "What force keeps a kart going round a corner of radius r?",
      o: ["Engine thrust", "A sideways tyre force of m v² ÷ r, towards the centre of the corner", "Air drag", "Gravity pulling it down the track"], a: 1,
      e: "To follow a curve you need a centripetal force m v² ÷ r. On a flat track only the tyres can supply it." },
    { ch: "ch-corner",
      q: "With tyre grip μ = 1.2 and no downforce, about how fast can you take a corner of 30 m radius?",
      o: ["About 25 km/h", "About 140 km/h", "About 300 km/h", "About 68 km/h"], a: 3,
      e: "v = √(μ g r) = √(1.2 × 9.81 × 30) ≈ 18.8 m/s, about 68 km/h." },
    { ch: "ch-corner",
      q: "In the simple friction model with no downforce, does a heavier kart have a lower limit speed in a corner?",
      o: ["Yes, much lower", "No: mass cancels out, so v = √(μ g r) either way", "Yes: heavy karts can't corner", "Only on a wet track"], a: 1,
      e: "More mass needs more cornering force, but it also presses the tyres down harder, so the two cancel. Real tyres lose a little grip per kilo at high loads, so weight still costs a bit." },
    { ch: "ch-transfer",
      q: "A 1,000 kg car with its centre of mass 0.5 m high and a 2.5 m wheelbase brakes at 1 g. About how much load moves onto the front tyres?",
      o: ["About 2 kN, like 200 kg moving forwards", "About 20 kg", "All 1,000 kg", "None: weight doesn't move"], a: 0,
      e: "ΔF = m a h ÷ L = 1,000 × 9.81 × 0.5 ÷ 2.5 ≈ 1,960 N, the weight of about 200 kg." },
    { ch: "ch-transfer",
      q: "Why do drivers do most of their braking in a straight line, before turning in?",
      o: ["To save fuel", "It looks smoother", "The rules require it", "Braking alone can use all the tyres' grip; turning at the same time has to share it (Ch 1)"], a: 3,
      e: "On the friction circle, hard braking and hard cornering can't both be at 100%. Brake first, then ease off the brake as you add steering." },
    { ch: "ch-line",
      q: "Why do racing drivers take the outside–inside–outside line through a corner?",
      o: ["It's the shortest way round", "It keeps them away from other drivers", "It makes the arc's radius bigger, so the same grip allows more speed", "It cools the tyres"], a: 2,
      e: "v = √(μ g r): a bigger radius means a higher limit speed, even if the path is a little longer." },
    { ch: "ch-line",
      q: "An 8 m-wide track turns 90° around a 5 m inside radius. The centreline's radius is 9 m; the ideal arc's is about 32 m. With μ = 1.2, how do their limit speeds compare?",
      o: ["About 37 km/h vs 70 km/h", "The same", "About 70 km/h on the centreline vs 37 km/h on the arc", "About 10 km/h vs 20 km/h"], a: 0,
      e: "√(1.2 × 9.81 × 9) ≈ 10.3 m/s (37 km/h) against √(1.2 × 9.81 × 32.3) ≈ 19.5 m/s (70 km/h)." },
    { ch: "ch-line",
      q: "What's the point of a late apex?",
      o: ["Nothing: it's always slower", "Doing the tightest turning early, so you can straighten up and accelerate sooner onto the next straight", "Saving fuel", "Avoiding the kerbs"], a: 1,
      e: "Exit speed carries all the way down the next straight, so it's often worth a slightly slower entry." },
    { ch: "ch-brake",
      q: "Double your speed from 100 to 200 km/h. With the same grip, your braking distance…",
      o: ["Doubles", "Halves", "Stays the same", "Becomes four times as long"], a: 3,
      e: "d = v² ÷ (2 μ g): the distance grows with the square of the speed. At μ = 1.2 it's 32.8 m from 100 km/h and 131 m from 200 km/h." },
    { ch: "ch-brake",
      q: "With μ = 1.2 and no downforce, about how far does it take to stop from 100 km/h (not counting reaction time)?",
      o: ["About 3 m", "About 300 m", "About 33 m", "About 100 m"], a: 2,
      e: "27.8² ÷ (2 × 1.2 × 9.81) ≈ 32.8 m, taking about 2.4 s." },
    { ch: "ch-brake",
      q: "Cornering at 1.2 g, about how much sideways force does a driver's neck need for a head and helmet of roughly 6 kg?",
      o: ["Less than 1 kg-force", "About 7 kg-force, as if holding a 7 kg weight sideways", "About 60 kg-force", "None: the helmet does it"], a: 1,
      e: "F = m a = 6 × 1.2 g ≈ 7.2 kg-force, sideways, at every corner of every lap. That's why racers train their necks." },
    { ch: "ch-aero",
      q: "Downforce grows as F = ½ ρ C_L A v². Going from 100 to 200 km/h multiplies it by…",
      o: ["4", "2", "1", "8"], a: 0,
      e: "It grows with v², so twice the speed gives four times the downforce: about 1.4 kN to 5.6 kN for our illustrative winged car." },
    { ch: "ch-aero",
      q: "Why do drivers start with a gentler warm-up or out lap before pushing?",
      o: ["To save fuel", "To read the signboards", "To let the engine cool down", "Rubber's grip depends on its temperature: cold tyres slide earlier, so they're warmed into their working range first"], a: 3,
      e: "Grip rises as the rubber warms into its working range, then falls off if it overheats." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- GRIP & CORNER LAB ----------
  // Corner on a flat track: m v² ÷ r = μ (m g + ½ ρ ClA v²)  →  v² = μ g r ÷ (1 − μ ρ ClA r ÷ (2 m)); lateral g = v² ÷ (g r).
  // Time through a 90° bend = (π r ÷ 2) ÷ v. Braking on the flat with constant μ (downforce ignored): d = v² ÷ (2 μ g), t = v ÷ (μ g).
  // Downforce at the straight-line speed: ½ ρ ClA v² ÷ (m g), with ρ = 1.2 kg/m³ (illustrative).
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("mk-r")) return;
    const G = 9.81, RHO = 1.2;
    function update() {
      const r = +$("mk-r").value, mu = +$("mk-mu").value, v = +$("mk-v").value, cla = +$("mk-cl").value, m = +$("mk-m").value;
      $("mk-r-o").textContent = r + " m";
      $("mk-mu-o").textContent = mu.toFixed(1);
      $("mk-v-o").textContent = v + " km/h";
      $("mk-cl-o").textContent = cla === 0 ? "0 (no wings)" : cla.toFixed(1) + " m²";
      $("mk-m-o").textContent = m + " kg";
      const V = v / 3.6, den = 1 - mu * RHO * cla * r / (2 * m), vc = den > 0 ? Math.sqrt(mu * G * r / den) : 0;
      $("mk-vc").textContent = vc ? Math.round(vc * 3.6) + " km/h" : "no limit in this model";
      $("mk-lat").textContent = vc ? (vc * vc / (G * r)).toFixed(2) + " g" : "—";
      $("mk-t90").textContent = vc ? (Math.PI * r / 2 / vc).toFixed(2) + " s" : "—";
      $("mk-bd").textContent = (V * V / (2 * mu * G)).toFixed(1) + " m";
      $("mk-bt").textContent = (V / (mu * G)).toFixed(2) + " s";
      $("mk-df").textContent = cla > 0 ? (0.5 * RHO * cla * V * V / (m * G)).toFixed(2) + " × weight" : "none (no wings)";
      $("mk-bar").style.width = vc ? Math.min(100, Math.round(100 * (vc * vc / (G * r)) / 3)) + "%" : "100%";
    }
    ["mk-r", "mk-mu", "mk-v", "mk-cl", "mk-m"].forEach(id => $(id).addEventListener("input", update));
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
