// Kinetic: running page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "running",
    v1: "Physics: nailed it 🏃",
    b1: "You've got the physiology. Skim the chapters for anything you missed, then scroll to “Where to go” for races at your level, from 5K to the high passes of Ladakh. Knowing the science is a great start; it is not the same as being trained, acclimatised or medically fit for a race.",
    b2: "You have the basics. Fill the gaps below before your next race, especially the altitude and heat chapters if you're heading somewhere high or humid.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to run at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, a race qualification, a medical clearance or a fitness assessment, and a high score does not make you ready for any distance or altitude. Build up gradually, talk to a doctor before hard training or high-altitude travel (especially with a heart, lung or blood-pressure condition), and meet each race's own eligibility, acclimatisation and medical rules."
  };
  const CHAPTERS = {
    "ch-economy":  "Ch 1 · Running economy & energy cost",
    "ch-forces":   "Ch 2 · Ground forces, cadence & stride",
    "ch-vo2":      "Ch 3 · VO₂ max, thresholds & pacing",
    "ch-fuel":     "Ch 4 · Energy systems & the wall",
    "ch-altitude": "Ch 5 · Altitude: thin air, acclimatisation & AMS",
    "ch-heat":     "Ch 6 · Heat, sweat & hydration"
  };
  const QUESTIONS = [
    { ch: "ch-economy",
      q: "A handy rule says running costs about 1 kcal per kg of body mass per kilometre. Roughly how much energy does a 70 kg runner use in a full marathon (42.2 km)?",
      o: ["About 300 kcal", "About 1,000 kcal", "About 3,000 kcal", "About 10,000 kcal"], a: 2,
      e: "70 kg × 42.2 km × 1 kcal ≈ 2,950 kcal. The rule is approximate (real costs vary by roughly ±10–20% between runners), but it's surprisingly independent of speed: a kilometre costs about the same whether you jog it or race it; racing just spends it faster." },
    { ch: "ch-economy",
      q: "What does 'running economy' mean?",
      o: ["How much oxygen (energy) you need to hold a given pace; better economy means less oxygen at the same speed", "How cheap your shoes were", "Your top sprinting speed", "Your resting heart rate"], a: 0,
      e: "Two runners with the same VO₂ max can race very differently if one uses less oxygen per kilometre. Economy improves with training volume, strength work and good technique, and is one reason experienced runners make fast running look easy." },
    { ch: "ch-forces",
      q: "At each footstrike in steady running, the peak vertical force from the ground is typically about…",
      o: ["Half your body weight", "Exactly your body weight", "About 10 times your body weight", "About 2–3 times your body weight"], a: 3,
      e: "You're airborne for part of every stride, so the ground has to make up for it during the short contact: average force during contact is well above body weight, and the peak is typically around 2–3 times body weight in running, against roughly 1.2 times in walking." },
    { ch: "ch-forces",
      q: "Averaged over a whole stride, including flight, the vertical force from the ground equals your body weight. Why?",
      o: ["Because shoes absorb the rest", "Because on average you're not accelerating up or down, so the ground's push has to balance gravity overall", "Because of air resistance", "It doesn't: it's always double body weight"], a: 1,
      e: "Newton's second law: if your average vertical velocity doesn't change, the average vertical force is zero, so the ground's average push equals your weight. Shorter ground contact means a bigger force during contact, not more total impulse." },
    { ch: "ch-forces",
      q: "You run at 5:00 per km (200 m per minute) with a cadence of 170 steps per minute. Your step length is about…",
      o: ["1.2 m", "0.6 m", "2.4 m", "3.5 m"], a: 0,
      e: "Speed = cadence × step length, so step length = 200 ÷ 170 ≈ 1.18 m. Run faster and you lengthen your stride and quicken your cadence. Over a marathon at this rhythm, that's about 36,000 steps." },
    { ch: "ch-vo2",
      q: "What is VO₂ max?",
      o: ["The most oxygen your body can take up and use per minute, usually given per kg of body mass", "Your total lung volume", "Your blood's oxygen saturation", "The amount of oxygen in a litre of air"], a: 0,
      e: "VO₂ max (mL of oxygen per kg per minute) is your aerobic ceiling. It depends on how much blood your heart can pump and how well muscles extract oxygen. Untrained adults are often in the 30s–40s; elite endurance runners can exceed 70." },
    { ch: "ch-vo2",
      q: "If running costs about 200 mL of oxygen per kg per km, what oxygen uptake does a 6:00/km pace need?",
      o: ["≈ 12 mL/kg/min", "≈ 20 mL/kg/min", "≈ 33 mL/kg/min", "≈ 60 mL/kg/min"], a: 2,
      e: "6:00/km is 1/6 km per minute. 200 × 1/6 ≈ 33 mL/kg/min. For a runner with a VO₂ max of 45, that's about 74% of their ceiling: comfortable for a half marathon for many trained runners, hard to hold all day." },
    { ch: "ch-fuel",
      q: "Why do many marathoners 'hit the wall' at around 30–35 km?",
      o: ["Their shoes wear out", "Stored carbohydrate (glycogen) runs low, forcing more reliance on fat, which can't release energy as fast", "Lactic acid crystallises in the legs", "The air gets thinner late in the race"], a: 1,
      e: "Muscles and liver store very roughly 2,000 kcal of glycogen in a well-fed runner, less than a marathon costs. Fat stores are huge but release energy more slowly, so pace has to drop. Carbohydrate before and during the race delays the wall." },
    { ch: "ch-fuel",
      q: "Which energy system powers most of a marathon?",
      o: ["Phosphocreatine (the 10-second system)", "Anaerobic glycolysis only", "Aerobic metabolism of carbohydrate and fat, using oxygen", "Muscles run on stored oxygen"], a: 2,
      e: "Phosphocreatine covers the first seconds of a sprint and anaerobic glycolysis dominates efforts of tens of seconds to a couple of minutes. Anything longer is mostly aerobic. A marathon is overwhelmingly aerobic, which is why VO₂ max, economy and fuel matter so much." },
    { ch: "ch-altitude",
      q: "At Leh (about 3,500 m), air is still about 21% oxygen. So why is every breath harder work?",
      o: ["The oxygen share drops to around 10%", "Total air pressure is only about 65% of sea level, so each breath carries about a third fewer oxygen molecules", "The air is colder", "There's more carbon dioxide in the air"], a: 1,
      e: "What matters is the partial pressure of oxygen: 21% of a lower total pressure. At about 3,500 m, pressure is roughly 65 kPa against 101 kPa at sea level, so oxygen's partial pressure falls from about 21 kPa to about 14 kPa. Less oxygen diffuses into your blood with each breath." },
    { ch: "ch-altitude",
      q: "The Ladakh Marathon advises full and half marathon runners to arrive in Leh at least how many days before race day?",
      o: ["1 day", "3 days", "30 days", "10 days"], a: 3,
      e: "The organisers advise at least 10 days for the full and half marathon, 7 days for the 5 km and 11.2 km, and 15 days for the two ultras (mandatory for the ultras). Acclimatisation takes time, and the organisers stress it is not determined by fitness." },
    { ch: "ch-altitude",
      q: "Early signs of acute mountain sickness (AMS) typically include…",
      o: ["Headache plus nausea, fatigue, dizziness or poor sleep after arriving at altitude", "Only a runny nose", "Unusually deep, restful sleep", "Sharper eyesight"], a: 0,
      e: "AMS usually starts within hours to a day of arriving high: headache with nausea, tiredness, dizziness or poor sleep. Rest, don't go higher and get medical help if it worsens. Breathlessness at rest, confusion or poor coordination can mean HAPE or HACE, which are emergencies: descend and seek care immediately." },
    { ch: "ch-altitude",
      q: "The Khardung La pass is about 5,370 m (17,618 ft). Roughly what is the air pressure there, compared with sea level?",
      o: ["About 90%", "About 75%", "About half", "About 10%"], a: 2,
      e: "The standard-atmosphere formula gives about 51 kPa at 5,370 m, roughly 51% of sea level. The organisers put it simply: oxygen drops to about 50% at Khardung La top. That's why the two ultras require 15 days in Leh and ban supplementary oxygen." },
    { ch: "ch-heat",
      q: "A runner produces about 650 W of heat. Evaporating 1 kg of sweat removes about 2.4 MJ. Roughly how much sweat per hour must evaporate to remove all of it?",
      o: ["About 0.1 kg", "About 5 kg", "About 20 kg", "About 1 kg"], a: 3,
      e: "650 W × 3,600 s ≈ 2.3 MJ per hour, and 2.3 ÷ 2.4 ≈ 1 kg of sweat per hour, if every drop evaporates. In practice some drips off without cooling you, so real sweat rates can be higher, which is why long races in heat need a hydration plan." },
    { ch: "ch-heat",
      q: "Why is a humid Mumbai morning harder to run in than a dry day at the same temperature?",
      o: ["Humid air is heavier to push through", "Sweat evaporates more slowly into humid air, so less heat is removed and more sweat drips off uselessly", "Humidity lowers the oxygen percentage", "It isn't: only temperature matters"], a: 1,
      e: "Evaporation needs a gradient: dry air can take up water vapour, saturated air can't. In humid heat you sweat just as much but cool less, so your core temperature and heart rate climb. Slow down, start early and drink to a plan (overdrinking plain water is also risky)." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- PACE & ALTITUDE LAB ----------
  // Illustrative model: energy ≈ 1 kcal/kg/km; oxygen cost ≈ 200 mL/kg/km; cadence 170 spm; peak force ≈ 2.5 × body weight;
  // VO2 max falls ≈ 7% per 1,000 m above 1,000 m (rule of thumb); ISA pressure; 80% of metabolic energy as heat; 2.43 MJ/kg sweat.
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("rn-pace")) return;
    let dist = 21.0975, alt = 0;
    function hms(t) {
      t = Math.round(t);
      const h = Math.floor(t / 3600), m = Math.floor((t % 3600) / 60), s = t % 60;
      return (h ? h + ":" + String(m).padStart(2, "0") : m) + ":" + String(s).padStart(2, "0");
    }
    function update() {
      const pace = +$("rn-pace").value, mass = +$("rn-mass").value, vo2 = +$("rn-vo2").value;
      $("rn-pace-o").textContent = Math.floor(pace / 60) + ":" + String(pace % 60).padStart(2, "0") + " /km";
      $("rn-mass-o").textContent = mass + " kg";
      $("rn-vo2-o").textContent = vo2 + "";
      const t = pace * dist;
      $("rn-time").textContent = hms(t);
      $("rn-energy").textContent = Math.round(mass * dist).toLocaleString("en-IN") + " kcal";
      $("rn-steps").textContent = "≈ " + (Math.round(170 * t / 60 / 100) * 100).toLocaleString("en-IN");
      $("rn-grf").textContent = Math.round(mass * 9.81 * 2.5).toLocaleString("en-IN") + " N";
      const need = 200 * (60 / pace);
      $("rn-need").textContent = need.toFixed(1);
      const P = 101.325 * Math.pow(1 - 2.25577e-5 * alt, 5.25588);
      $("rn-press").textContent = (P / 101.325 * 100).toFixed(1) + "%";
      $("rn-po2").textContent = (0.2095 * P).toFixed(1) + " kPa";
      const vmax = vo2 * (1 - 0.07 * Math.max(0, (alt - 1000) / 1000));
      $("rn-vmax").textContent = vmax.toFixed(1);
      const pct = need / vmax * 100;
      $("rn-pct").textContent = pct >= 100 ? "over 100%" : pct.toFixed(0) + "%";
      $("rn-pct").style.color = pct >= 90 ? "#ff8a70" : "#fff";
      $("rn-pct-s").textContent = pct >= 100 ? "not sustainable · slow down" : (pct >= 85 ? "very hard to hold for long" : "Ch 3 · need ÷ ceiling");
      const watts = mass * (3600 / pace) * 4184 / 3600;
      $("rn-sweat").textContent = (watts * 0.8 * 3600 / 2.43e6).toFixed(2) + " kg/h";
      $("rn-bar").style.width = Math.min(100, pct / 110 * 100).toFixed(0) + "%";
    }
    ["rn-pace", "rn-mass", "rn-vo2"].forEach(id => $(id).addEventListener("input", update));
    function seg(id, fn) {
      document.querySelectorAll("#" + id + " button").forEach(b => b.addEventListener("click", () => {
        fn(b);
        document.querySelectorAll("#" + id + " button").forEach(x => x.setAttribute("aria-pressed", x === b ? "true" : "false"));
        update();
      }));
    }
    seg("rn-dist", b => { dist = +b.dataset.km; });
    seg("rn-alt", b => { alt = +b.dataset.alt; });
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
