// Kinetic: paramotoring page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "paramotoring",
    v1: "Physics: nailed it 🪂",
    b1: "You've got the physics of paramotoring. Skim the chapters for anything you missed, then scroll to “Where to train” for paramotor courses, rating systems and the rules at your level. Knowing the science is a great start; it isn't the same as wing handling, engine management or the judgement a school builds.",
    b2: "You have the basics. Fill the gaps below before you fly, especially torque, launching and the engine-off glide: they're the chapters that matter close to the ground.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to train at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, a pilot rating or legal advice. Learn to paraglide first, train for powered flight at a school with qualified instructors, keep a logbook, always fly with a landing field within glide, and confirm site permissions (NOC, AAI clearance and NOTAM, daily ATC permission) before you fly."
  };
  const CHAPTERS = {
    "ch-thrust":  "Ch 1 · Thrust vs drag",
    "ch-wing":    "Ch 2 · The PPG wing",
    "ch-torque":  "Ch 3 · Thrust line & torque",
    "ch-launch":  "Ch 4 · Forward & reverse launch",
    "ch-fuel":    "Ch 5 · Fuel, endurance & weight-shift",
    "ch-weather": "Ch 6 · Wind, weather & the rules"
  };
  const QUESTIONS = [
    { ch: "ch-thrust",
      q: "In steady level flight, how big is the thrust a paramotor needs?",
      o: ["Equal to the weight", "Zero", "Equal to the drag", "Twice the lift"], a: 2,
      e: "Lift balances weight and thrust balances drag. Any extra thrust makes you climb." },
    { ch: "ch-thrust",
      q: "A 110 kg all-up paramotor (1,079 N) flies a wing with a 6 : 1 glide ratio. About how much drag must the thrust overcome?",
      o: ["About 180 N", "About 1,079 N", "About 6,500 N", "About 18 N"], a: 0,
      e: "Drag = weight ÷ (L/D) = 1,079 ÷ 6 ≈ 180 N. At 10 m/s that's about 1.8 kW of power." },
    { ch: "ch-thrust",
      q: "Same paramotor, 400 N of thrust at 10 m/s airspeed. Roughly what climb rate?",
      o: ["About 20 m/s", "About 0.2 m/s", "It can't climb", "About 2 m/s"], a: 3,
      e: "Climb = (thrust − drag) × airspeed ÷ weight = (400 − 180) × 10 ÷ 1,079 ≈ 2.0 m/s." },
    { ch: "ch-wing",
      q: "Adding weight to a PPG wing (within its certified range) makes it trim…",
      o: ["Faster: speed rises with the square root of wing loading", "Slower", "At exactly the same speed", "Backwards"], a: 0,
      e: "Lift must equal weight, and lift grows with v², so v ∝ √(loading). 110 → 125 kg on our wing: 36 → 38.4 km/h." },
    { ch: "ch-wing",
      q: "Which wings does the Version E5 safety guideline say should be used for powered flying?",
      o: ["Any home-made wing", "EN, LTF, DHV or DGAC certified wings recommended for powered flying", "Only hang-glider wings", "Wings older than 10 years"], a: 1,
      e: "It also asks for annual airworthiness checks with documented records." },
    { ch: "ch-torque",
      q: "Why does a paramotor tend to twist the pilot when power is added?",
      o: ["The wind changes direction", "The wing is asymmetric", "The propeller's reaction torque pushes the motor and pilot the opposite way to the propeller", "Fuel sloshes in the tank"], a: 2,
      e: "Newton's third law for rotation. Torque = power ÷ angular speed, so it's strongest at full power, during take-off and climb." },
    { ch: "ch-torque",
      q: "15 kW at a propeller speed of 3,200 rpm (335 rad/s). About how much reaction torque?",
      o: ["About 4.5 N·m", "About 450 N·m", "About 4,800 N·m", "About 45 N·m"], a: 3,
      e: "Torque = 15,000 ÷ 335 ≈ 45 N·m: like 4.5 kg hanging on a 1 m lever." },
    { ch: "ch-launch",
      q: "The wing needs 32 km/h of airspeed to fly, and there's a 12 km/h headwind. What groundspeed do you need at lift-off?",
      o: ["44 km/h", "20 km/h", "32 km/h", "12 km/h"], a: 1,
      e: "Groundspeed = airspeed − headwind = 32 − 12 = 20 km/h. That's why you launch into the wind." },
    { ch: "ch-launch",
      q: "What's a reverse launch?",
      o: ["Facing the wing to inflate and check it, then turning round to take off", "Taking off downwind", "Taking off backwards", "Launching from a trike in reverse gear"], a: 0,
      e: "Facing the wing lets you see and control it while it inflates; pilots often use it in stronger wind. A forward launch faces the direction of flight." },
    { ch: "ch-launch",
      q: "Take-off run = v² ÷ (2a). If a headwind halves the groundspeed you need, the run becomes…",
      o: ["Half as long", "Twice as long", "About a quarter as long", "The same"], a: 2,
      e: "Distance goes with v²: (½)² = ¼. In our example, 26 m in calm air drops to about 4 m with a 20 km/h headwind." },
    { ch: "ch-fuel",
      q: "Airspeed 36 km/h, wind 15 km/h. Which way should you fly first on a there-and-back trip?",
      o: ["Upwind, so the slow, fuel-hungry leg comes first and the fast leg brings you home", "Downwind, to go further", "It makes no difference", "Across the wind only"], a: 0,
      e: "Upwind you make 21 km/h, downwind 51 km/h. Fly the slow leg while you have the most fuel." },
    { ch: "ch-fuel",
      q: "In a 60° banked turn, what load factor does the wing carry?",
      o: ["1 g", "1.15 g", "0.5 g", "2 g"], a: 3,
      e: "n = 1 ÷ cos(bank) = 1 ÷ 0.5 = 2 g. The USPPA's PPG2 novice limits bank to 30° (1.15 g)." },
    { ch: "ch-weather",
      q: "From 300 m with the engine off, 6 : 1 wing, 36 km/h airspeed, 15 km/h headwind: about how far can you glide over the ground?",
      o: ["1.8 km", "About 1.05 km", "About 4 km", "300 m"], a: 1,
      e: "300 × 6 × (36 − 15) ÷ 36 ≈ 1,050 m. Always keep a landing field within that distance." },
    { ch: "ch-weather",
      q: "According to the Version E5 safety guideline, what's the maximum wind for tandem PPG?",
      o: ["Any wind", "50 km/h", "18 km/h", "5 km/h"], a: 2,
      e: "Not in more than 18 km/h of wind; and no aerobatic manoeuvres below 600 ft." },
    { ch: "ch-weather",
      q: "Which of these did the Ministry of Civil Aviation list in 2026 as regulated by DGCA for safety and licensing?",
      o: ["Powered paragliders", "Kites", "Paper planes", "Powered hang gliders"], a: 3,
      e: "Gliders, microlights, light sport aircraft, gyroplanes, balloons and powered hang gliders. Powered paragliders weren't on the list; NASG 2023 sets the wider framework through ASFI." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- THRUST LAB ----------
  // Level flight: D = m g ÷ (L/D); P = D v; climb = (T − D) v ÷ (m g).
  // Groundspeed = airspeed ∓ wind; engine-off glide from 300 m into wind = 300 × L/D × (v − w) ÷ v.
  // Wing loading on a 22 m² wing. All illustrative.
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("pm-m")) return;
    const g = 9.81, AREA = 22, H = 300;
    let ld = 6;
    function update() {
      const m = +$("pm-m").value, vk = +$("pm-v").value, T = +$("pm-t").value, w = +$("pm-w").value;
      $("pm-m-o").textContent = m + " kg";
      $("pm-v-o").textContent = vk + " km/h";
      $("pm-t-o").textContent = T + " N";
      $("pm-w-o").textContent = w + " km/h";
      const W = m * g, D = W / ld, v = vk / 3.6, climb = (T - D) * v / W;
      $("pm-drag").textContent = Math.round(D) + " N";
      $("pm-pow").textContent = (D * v / 1000).toFixed(2) + " kW";
      $("pm-climb").textContent = climb > 0 ? climb.toFixed(1) + " m/s" : "can't climb";
      $("pm-gs").textContent = (vk - w) + " / " + (vk + w) + " km/h";
      $("pm-glide").textContent = vk > w ? (H * ld * (vk - w) / vk / 1000).toFixed(2) + " km" : "drifts backwards";
      $("pm-load").textContent = (m / AREA).toFixed(1) + " kg/m²";
      $("pm-bar").style.width = Math.min(100, D / T * 100) + "%";
    }
    ["pm-m", "pm-v", "pm-t", "pm-w"].forEach(id => $(id).addEventListener("input", update));
    document.querySelectorAll("#pm-ld button").forEach(b => b.addEventListener("click", () => {
      ld = +b.dataset.ld;
      document.querySelectorAll("#pm-ld button").forEach(x => x.setAttribute("aria-pressed", x === b ? "true" : "false"));
      update();
    }));
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
