// Kinetic: windsurfing page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "windsurfing",
    v1: "Physics: nailed it 🏄",
    b1: "You've got the physics of windsurfing. Skim the chapters for anything you missed, then scroll to “Where to learn” for schools, championships and instructor courses at your level. Knowing the science is a great start; it isn't the same as balance, rig handling or self-rescue on real water.",
    b2: "You have the basics. Fill the gaps below before your next session, especially apparent wind and steering with the rig: they're the chapters that get you back to where you started.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to learn at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, a course level or a replacement for lessons. Learn at a recognised centre with a qualified instructor and rescue cover, wear a buoyancy aid while learning, be able to swim, and check the wind direction before you go out."
  };
  const CHAPTERS = {
    "ch-apparent": "Ch 1 · Apparent wind",
    "ch-sail":     "Ch 2 · Sail force & the harness",
    "ch-steer":    "Ch 3 · Steering with the rig",
    "ch-plane":    "Ch 4 · Hull speed, planing & foiling",
    "ch-upwind":   "Ch 5 · Tacking, gybing & VMG",
    "ch-safety":   "Ch 6 · Wind, weather & self-rescue"
  };
  const QUESTIONS = [
    { ch: "ch-apparent",
      q: "True wind is 15 kn on your beam (from the side) and you sail at 10 kn. What apparent wind does the sail feel?",
      o: ["5 kn", "25 kn", "About 18 kn", "15 kn"], a: 2,
      e: "√(15² + 10²) ≈ 18.0 kn, coming from about 56° off your nose instead of 90°." },
    { ch: "ch-apparent",
      q: "Same wind and board speed: on which heading does the sail feel the strongest apparent wind?",
      o: ["Sailing upwind (about 45° off the wind)", "Beam reach", "Broad reach", "It's the same on every heading"], a: 0,
      e: "Upwind, your headwind adds to the true wind: about 23.2 kn at 45°, versus 18.0 kn on a beam reach and 10.6 kn on a broad reach." },
    { ch: "ch-sail",
      q: "The apparent wind rises from 12 kn to 18 kn. How much does the sail force grow?",
      o: ["1.5 times", "2.25 times", "6 times", "It stays the same"], a: 1,
      e: "Sail force goes with v²: (18 ÷ 12)² = 2.25." },
    { ch: "ch-sail",
      q: "What does a harness do?",
      o: ["Makes the sail bigger", "Keeps you from falling in", "Steers the board", "Lets your body weight hold the sail's pull instead of your arms"], a: 3,
      e: "The harness hooks into lines on the boom, so you lean back against the force with your body weight." },
    { ch: "ch-sail",
      q: "Why do windsurfers own sails of different sizes?",
      o: ["Bigger sails are only for racing", "Small sails are faster in light wind", "Force grows with sail area and with v², so a smaller sail keeps strong wind manageable", "Sail size doesn't change the force"], a: 2,
      e: "F = ½ ρ v² A C_L. In light wind you need area; in strong wind the v² makes a big sail uncontrollable." },
    { ch: "ch-steer",
      q: "You tilt the rig forward, towards the nose. What does the board do?",
      o: ["Turns away from the wind (bears away)", "Turns into the wind", "Goes straight", "Stops"], a: 0,
      e: "The centre of effort moves ahead of the centre of lateral resistance, so the sail's force swings the nose downwind." },
    { ch: "ch-steer",
      q: "A 300 N sail force acts 0.3 m behind the centre of lateral resistance. What turning moment does it make?",
      o: ["1,000 N·m", "90 N·m, turning you into the wind", "0.3 N·m", "300 N·m"], a: 1,
      e: "Moment = force × lever arm = 300 × 0.3 = 90 N·m. With the rig tilted back, the nose turns into the wind." },
    { ch: "ch-plane",
      q: "Why does a displacement board struggle to go faster than its hull speed?",
      o: ["The fin stalls", "The sail gets smaller", "Water gets thicker", "It's climbing its own bow wave, whose speed depends on its length"], a: 3,
      e: "Wave speed is √(g L ÷ 2π): about 3.8 kn for a 2.5 m board. Planing (skimming on top) or foiling breaks out of that limit." },
    { ch: "ch-plane",
      q: "Why can a hydrofoil wing of only about 0.1 m² lift a rider and board?",
      o: ["Foils use magnets", "The board floats it up", "Water is about 800 times denser than air, and lift grows with density and speed²", "The sail lifts the board"], a: 2,
      e: "Lift = ½ ρ v² A C_L with ρ ≈ 1,025 kg/m³. In our lab the foil lifts an 85 kg rider and board at about 13 kn." },
    { ch: "ch-plane",
      q: "If a foil just lifts you at 13 kn, about how much of that lift does it make at 6.5 kn?",
      o: ["25%", "50%", "100%", "200%"], a: 0,
      e: "Lift goes with speed squared: (6.5 ÷ 13)² = 0.25." },
    { ch: "ch-upwind",
      q: "You sail at 8 kn, 45° off the wind. How fast are you making progress upwind (VMG)?",
      o: ["8 kn", "About 5.7 kn", "0 kn", "About 11 kn"], a: 1,
      e: "VMG = 8 × cos 45° ≈ 5.7 kn." },
    { ch: "ch-upwind",
      q: "What is a tack?",
      o: ["A turn with the wind behind you", "A kind of fin", "A sail size", "Turning the nose through the wind to sail upwind on the other side"], a: 3,
      e: "A tack turns through the wind; a gybe turns with the wind behind you. Zig-zagging with tacks is how you get upwind." },
    { ch: "ch-safety",
      q: "Why is an offshore wind (blowing from the land out to sea) dangerous for a beginner?",
      o: ["It's always too strong", "If you can't sail back, it carries you away from the beach", "It makes the water colder", "It isn't dangerous"], a: 1,
      e: "If you tire, fall repeatedly or the wind changes, offshore wind blows you out to sea. Learn in steady, cross-shore wind with rescue cover." },
    { ch: "ch-safety",
      q: "You can't sail back to the beach. What's the safest thing to do?",
      o: ["Stay with the board: drop or de-rig the sail and paddle in, or signal for help", "Leave the board and swim", "Stand up and wait", "Try a bigger sail"], a: 0,
      e: "The board floats and is easier to see than a swimmer. Self-rescue drills are part of beginner courses such as Quest's Level 1." },
    { ch: "ch-safety",
      q: "A gust takes the wind from 15 to 21 kn. About how much more sail force?",
      o: ["About 1.4 times", "No change", "About 1.96 times: nearly double", "6 times"], a: 2,
      e: "(21 ÷ 15)² ≈ 1.96. A 40% gust nearly doubles the force." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- SAIL LAB ----------
  // Apparent wind = |true wind vector (from heading angle θ) + board-speed headwind|; angle from the nose.
  // Sail force = ½ ρ v² A CL (ρ 1.225, CL 1.0, illustrative). VMG = B cos θ.
  // Foil lift = ½ ρw v² A CL (ρw 1,025, A 0.1 m², CL 0.4, illustrative) vs 85 kg × g.
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("ws-w")) return;
    const rho = 1.225, rhow = 1025, KN = 0.514444, g = 9.81, W85 = 85 * g;
    let th = 90;
    const fmt = n => Math.round(n).toLocaleString("en-US");
    function update() {
      const W = +$("ws-w").value, B = +$("ws-b").value, A = +$("ws-a").value;
      $("ws-w-o").textContent = W + " kn";
      $("ws-b-o").textContent = B + " kn";
      $("ws-a-o").textContent = A.toFixed(1) + " m²";
      const t = th * Math.PI / 180, x = W * Math.cos(t) + B, y = W * Math.sin(t);
      const aw = Math.hypot(x, y), ang = Math.atan2(y, x) * 180 / Math.PI;
      const F = 0.5 * rho * Math.pow(aw * KN, 2) * A;
      const vmg = B * Math.cos(t), foil = 0.5 * rhow * Math.pow(B * KN, 2) * 0.1 * 0.4;
      $("ws-aw").textContent = aw.toFixed(1) + " kn";
      $("ws-ang").textContent = Math.round(ang) + "°";
      $("ws-f").textContent = fmt(F) + " N";
      const vm = Math.abs(vmg) < 0.05 ? 0 : vmg;
      $("ws-vmg").textContent = (vm < 0 ? "−" + Math.abs(vm).toFixed(1) : vm.toFixed(1)) + " kn";
      $("ws-foil").textContent = fmt(foil) + " N";
      $("ws-fly").textContent = Math.round(foil / W85 * 100) + "%";
      $("ws-bar").style.width = Math.min(100, foil / W85 * 100) + "%";
    }
    ["ws-w", "ws-b", "ws-a"].forEach(id => $(id).addEventListener("input", update));
    document.querySelectorAll("#ws-hd button").forEach(b => b.addEventListener("click", () => {
      th = +b.dataset.th;
      document.querySelectorAll("#ws-hd button").forEach(x => x.setAttribute("aria-pressed", x === b ? "true" : "false"));
      update();
    }));
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
