// Kinetic: triathlon page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "triathlon",
    v1: "Physics: nailed it 🏊",
    b1: "You've got the physics of a triathlon. Skim the chapters for anything you missed, then scroll to “Where to race” for real federations and races at your distance. Knowing the science is a great start; it isn't the same as the training, the fuelling practice or the open-water experience a long race needs.",
    b2: "You have the basics. Fill the gaps below before your next race, especially fuelling and drafting: they're the chapters that decide long races and keep you out of the penalty tent.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to race at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, a coaching plan or medical advice. Get a medical check before training for a long-distance race, build up gradually, swim open water only with water-safety cover, and follow your race's rules and athlete guide."
  };
  const CHAPTERS = {
    "ch-fuel": "Ch 1 · Energy systems & fuelling",
    "ch-pace": "Ch 2 · Pacing & power",
    "ch-swim": "Ch 3 · Swim drag & wetsuit buoyancy",
    "ch-aero": "Ch 4 · Drafting rules & bike aerodynamics",
    "ch-run":  "Ch 5 · Running economy on tired legs",
    "ch-heat": "Ch 6 · Heat, hydration & transitions"
  };
  const QUESTIONS = [
    { ch: "ch-fuel",
      q: "Why does carbohydrate, not fat, usually limit a hard long-distance race?",
      o: ["Fat can't be burned during exercise", "The body stores only a few hundred grams of carbohydrate as glycogen, and harder efforts burn more of it", "Carbohydrate has more energy per gram than fat", "Glycogen is stored only in the brain"], a: 1,
      e: "Fat stores are huge, but glycogen in muscle and liver is limited to a few hundred grams, and the harder you go, the larger the share of energy that comes from carbohydrate." },
    { ch: "ch-fuel",
      q: "Your muscles turn about 23% of food energy into pedal power (illustrative). Riding at 180 W, about how much food energy do you burn per hour?",
      o: ["About 155 kcal", "About 6,700 kcal", "About 673 kcal", "About 180 kcal"], a: 2,
      e: "180 ÷ 0.23 ≈ 783 W of food energy; × 3,600 s ÷ 4,184 J/kcal ≈ 673 kcal per hour. The other 77% becomes heat (Ch 6)." },
    { ch: "ch-fuel",
      q: "For ultra-endurance exercise longer than about 2.5–3 hours, what carbohydrate intake does the 2016 ACSM/AND/Dietitians of Canada position statement suggest?",
      o: ["None: eating slows you down", "Exactly 30 g per race", "At least 200 g per hour", "Up to 90 g per hour, ideally as glucose-fructose mixtures"], a: 3,
      e: "It suggests 30–60 g/h for 1–2.5 h and up to 90 g/h beyond 2.5–3 h, using multiple transportable carbohydrates the gut absorbs faster. Practise it in training first." },
    { ch: "ch-pace",
      q: "On a flat road, air-drag power grows with the cube of speed. Ignoring rolling resistance, how much more power does 10% more speed need?",
      o: ["About 33% more", "10% more", "Exactly double", "About 3% more"], a: 0,
      e: "1.1³ ≈ 1.33: about a third more power for a tenth more speed. That's why steady pacing beats surges." },
    { ch: "ch-pace",
      q: "In our lab, going from 150 W to 200 W over 90 km in the hoods saves about 18 minutes. What's the catch?",
      o: ["None: more power is always free", "You burn roughly a third more carbohydrate every hour, and you still have to run", "Your bike gets heavier", "The draft zone gets longer"], a: 1,
      e: "Carbohydrate burn rises from about 84 to 112 g/h. Spend too much on the bike and the run pays for it (Ch 1, Ch 5)." },
    { ch: "ch-swim",
      q: "Why does body position matter so much more in the swim than on the bike?",
      o: ["Water is about 800 times denser than air, so drag from sinking legs is large", "Water has no drag", "Swimmers are heavier in water", "Air is denser than water"], a: 0,
      e: "Drag = ½ ρ CdA v², and ρ for water is about 1,000 kg/m³ versus 1.2 for air. Sinking hips and legs add frontal area, and that costs a lot." },
    { ch: "ch-swim",
      q: "How does a wetsuit make most swimmers faster?",
      o: ["It pushes water backwards like a fin", "It makes you heavier so you sink less", "Its closed-cell foam adds buoyancy, lifting hips and legs and cutting drag", "It reduces the water's density"], a: 2,
      e: "The gas bubbles in neoprene displace water. In our illustrative example a suit gives about 4 kg of net lift, mostly where swimmers sink." },
    { ch: "ch-swim",
      q: "Under IRONMAN's 2026 rules, up to what water temperature may age-group athletes race in a wetsuit and stay eligible for awards?",
      o: ["Any temperature", "20.0 °C", "28.8 °C", "24.5 °C"], a: 3,
      e: "Up to and including 24.5 °C. Between 24.5 and 28.8 °C a race may offer a non-competitive wetsuit wave (no awards or slots); above 28.8 °C wetsuits are prohibited." },
    { ch: "ch-aero",
      q: "What does CdA describe?",
      o: ["Your cadence", "How much air drag you and your bike make: drag coefficient × frontal area", "The bike's weight", "Your heart rate"], a: 1,
      e: "Drag force is ½ ρ CdA v². Aero bars shrink your frontal area: in our lab, 180 W goes from about 30.6 km/h upright to 35.5 km/h on aero bars." },
    { ch: "ch-aero",
      q: "In World Triathlon's updated rules and IRONMAN's 2026 age-group rules, what is the draft zone?",
      o: ["5 m, with 15 s to pass", "There is no draft zone", "12 m, with 25 s to pass", "50 m, with 2 min to pass"], a: 2,
      e: "12 m measured from the front wheel (about six bike lengths of clear space), and a pass must be completed within 25 s. IRONMAN professionals have a 20 m zone." },
    { ch: "ch-aero",
      q: "To get through a 12 m draft zone in 25 s, at least how much faster than the rider ahead must you ride?",
      o: ["About 1.7 km/h (0.48 m/s)", "About 12 km/h", "About 0.1 km/h", "About 25 km/h"], a: 0,
      e: "12 m ÷ 25 s = 0.48 m/s ≈ 1.7 km/h. At about 33 km/h in the hoods that costs roughly 27 W extra for those 25 seconds (lab)." },
    { ch: "ch-run",
      q: "Using the rule of thumb of about 1 kcal per kg per km, roughly how much energy does a 70 kg athlete spend on a full-distance marathon (42.2 km)?",
      o: ["About 295 kcal", "About 2,954 kcal", "About 29,540 kcal", "About 70 kcal"], a: 1,
      e: "70 × 42.2 × 1 ≈ 2,954 kcal: more than the illustrative ~2,000 kcal of glycogen, which is why fuelling on the bike matters for the run." },
    { ch: "ch-run",
      q: "What is a \"brick\" session?",
      o: ["A strength session with weights", "A swim with a pull buoy", "A rest day", "A run straight after a ride, to train the switch between them"], a: 3,
      e: "Legs feel heavy and stiff off the bike. Bricks train that switch; short, quick steps first, then settle into your stride." },
    { ch: "ch-heat",
      q: "The 2016 position statement suggests keeping your total body-fluid deficit under what share of body mass?",
      o: ["2%", "10%", "0%: you must drink exactly what you sweat", "25%"], a: 0,
      e: "Deficits above about 2% can impair thinking and aerobic performance, especially in heat. Over-drinking is risky too; learn your sweat rate in training." },
    { ch: "ch-heat",
      q: "Under IRONMAN's 2026 rules, when must your bike helmet be fastened?",
      o: ["Only on descents", "Only when racing in the rain", "From taking your bike off the rack until you rack it again", "Only after the mount line"], a: 2,
      e: "The helmet must be securely fastened whenever you have the bike: from removing it from the rack at the start of the bike leg until it's back on the rack." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- RACE-DAY LAB ----------
  // Flat road, no wind: P·η = ½ρ CdA v³ + Crr m g v (m 80 kg, Crr 0.004, ρ 1.2, η 0.97).
  // Food energy = P ÷ 0.23 (illustrative efficiency); 60% from carbohydrate at 4 kcal/g (illustrative).
  // Pass: 12 m draft zone in 25 s → +0.48 m/s over the rider ahead.
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("tr-p")) return;
    const rho = 1.2, m = 80, g = 9.81, crr = 0.004, eta = 0.97, eff = 0.23;
    let km = 90, cda = 0.32;
    const need = v => (0.5 * rho * cda * v * v * v + crr * m * g * v) / eta;
    function speed(P) { let lo = 0.1, hi = 30; for (let i = 0; i < 80; i++) { const v = (lo + hi) / 2; if (need(v) > P) hi = v; else lo = v; } return (lo + hi) / 2; }
    const fmt = n => Math.round(n).toLocaleString("en-US");
    function hm(h) { const mins = Math.round(h * 60); return mins < 60 ? mins + " min" : Math.floor(mins / 60) + ":" + String(mins % 60).padStart(2, "0"); }
    function update() {
      const P = +$("tr-p").value, c = +$("tr-c").value;
      $("tr-p-o").textContent = P + " W";
      $("tr-c-o").textContent = c + " g/h";
      const v = speed(P), kmh = v * 3.6, h = km / kmh;
      const air = 0.5 * rho * cda * v * v * v / (P * eta);
      const kcalh = P / eff * 3600 / 4184, cho = kcalh * 0.6 / 4;
      $("tr-v").textContent = kmh.toFixed(1) + " km/h";
      $("tr-t").textContent = hm(h);
      $("tr-air").textContent = Math.round(air * 100) + "%";
      $("tr-kcal").textContent = fmt(kcalh * h) + " kcal";
      $("tr-cho").textContent = Math.round(cho) + " g/h";
      const gap = Math.round(cho) - c;
      $("tr-gap").textContent = gap > 0 ? gap + " g/h" : "none: intake covers it";
      $("tr-pass").textContent = "+" + Math.round(need(v + 12 / 25) - P) + " W";
      $("tr-bar").style.width = Math.min(100, c / cho * 100) + "%";
    }
    ["tr-p", "tr-c"].forEach(id => $(id).addEventListener("input", update));
    [["tr-dist", "km"], ["tr-pos", "cda"]].forEach(([grp, key]) => document.querySelectorAll("#" + grp + " button").forEach(b => b.addEventListener("click", () => {
      if (key === "km") km = +b.dataset.km; else cda = +b.dataset.cda;
      document.querySelectorAll("#" + grp + " button").forEach(x => x.setAttribute("aria-pressed", x === b ? "true" : "false"));
      update();
    })));
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
