// Kinetic: skateboarding page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "skateboarding",
    v1: "Physics: nailed it 🛹",
    b1: "You've got the physics of the board. Skim the chapters for anything you missed, then scroll to “Where to skate” for parks, competitions and courses at your level. Knowing the science is a great start; it isn't the same as balance, practice or knowing how to fall.",
    b2: "You have the basics. Fill the gaps below before your next session, especially ramps and falling: they're the chapters that keep you skating instead of healing.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to skate at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, a coaching assessment or a judgement of which ramps or tricks you're ready for. Wear a helmet (and wrist guards and pads while you learn), skate in parks or safe spaces away from traffic, learn to fall before you learn tricks, and build up slowly, ideally with an experienced coach or skater."
  };
  const CHAPTERS = {
    "ch-roll":   "Ch 1 · Pushing, rolling & coasting",
    "ch-balance":"Ch 2 · Balance, stance & turning",
    "ch-ollie":  "Ch 3 · The ollie",
    "ch-ramps":  "Ch 4 · Ramps, bowls & pumping",
    "ch-falls":  "Ch 5 · Falling safely",
    "ch-wheels": "Ch 6 · Wheels, bearings & contests"
  };
  const QUESTIONS = [
    { ch: "ch-roll",
      q: "You push off at 4 m/s (about 14 km/h) and coast on smooth concrete with a rolling-resistance coefficient of 0.02. Ignoring air drag, roughly how far do you roll before stopping?",
      o: ["About 4 m", "About 40 m", "About 400 m", "Forever"], a: 1,
      e: "Rolling resistance decelerates you at C<sub>rr</sub> × g ≈ 0.2 m/s², so distance = v² ÷ (2 C<sub>rr</sub> g) = 16 ÷ 0.39 ≈ 41 m. Rough ground (higher C<sub>rr</sub>) stops you much sooner." },
    { ch: "ch-roll",
      q: "Why do you keep your weight over the front foot when you push?",
      o: ["So the board stays under you and you can steer and balance while the back foot pushes", "To make the board heavier", "To reduce air drag", "It doesn't matter"], a: 0,
      e: "Your standing foot carries your weight and controls the board; the pushing foot only supplies short bursts of force along the ground. Keep pushes smooth and look where you're going." },
    { ch: "ch-balance",
      q: "To stay balanced on a rolling board, where must your centre of mass be?",
      o: ["Well behind the tail", "Anywhere you like", "Over the board, between the wheels", "Out in front of the nose"], a: 2,
      e: "If your centre of mass drifts outside the area between the wheels, gravity creates a turning moment that tips you off. Bent knees lower your centre of mass and give you room to correct." },
    { ch: "ch-balance",
      q: "How does a skateboard turn when you lean?",
      o: ["The wheels slide sideways", "The deck bends in half", "The bearings steer", "The trucks pivot so the axles angle, steering the wheels into a curve"], a: 3,
      e: "Skateboard trucks are built so that tilting the deck swings the axles: lean toe-side or heel-side and the board carves that way. Looser trucks turn more for the same lean." },
    { ch: "ch-ollie",
      q: "To ollie over a 30 cm obstacle, about how fast must your board and body be moving upwards at take-off?",
      o: ["About 2.4 m/s", "About 0.3 m/s", "About 24 m/s", "About 9.8 m/s"], a: 0,
      e: "v = √(2 g h) = √(2 × 9.81 × 0.3) ≈ 2.4 m/s. You'd be in the air for about 2v ÷ g ≈ 0.49 s; at a rolling speed of 4 m/s, you travel about 2 m forward while you're up." },
    { ch: "ch-ollie",
      q: "In an ollie, why does snapping the tail down make the board jump up?",
      o: ["The tail is springy", "Gravity reverses", "The tail hits the ground and the push back from the ground lifts and rotates the board up, while your front foot slides to level it", "The wheels bounce"], a: 2,
      e: "Snapping the tail pivots the board over the back wheels; the ground pushes back on the tail and the board pops upwards. Jumping and sliding your front foot forward drags the nose up and levels the board in the air." },
    { ch: "ch-ollie",
      q: "Doubling the height of an obstacle multiplies the take-off speed you need by about:",
      o: ["2", "1.4", "4", "It stays the same"], a: 1,
      e: "v = √(2 g h), so doubling h multiplies v by √2 ≈ 1.41. Going from 30 cm to 60 cm needs about 3.4 m/s instead of 2.4 m/s." },
    { ch: "ch-ramps",
      q: "Dropping in from the top of a 1.5 m ramp, about how fast are you going at the bottom (ignoring friction)?",
      o: ["About 5 km/h", "About 50 km/h", "About 100 km/h", "About 20 km/h"], a: 3,
      e: "Energy conservation: v = √(2 g h) = √(2 × 9.81 × 1.5) ≈ 5.4 m/s ≈ 19.5 km/h. Your height turns into speed, and back into height on the other side." },
    { ch: "ch-ramps",
      q: "Why do your legs feel heavier at the bottom of a curved ramp (the transition)?",
      o: ["The curve has to push you around it, so the ramp pushes up harder than your weight: you feel more than 1 g", "You lose speed", "Gravity is stronger at the bottom", "The board gets heavier"], a: 0,
      e: "Moving in a curve of radius r needs a centripetal force m v² ÷ r. At the bottom, the ramp supplies your weight plus that. Dropping 1.5 m into a 1.8 m-radius transition gives about 2.7 g: bend your knees and stay over the board." },
    { ch: "ch-ramps",
      q: "How does 'pumping' a bowl or ramp make you faster without pushing?",
      o: ["It doesn't; it's a myth", "You crouch on the way into the curve and stand up through it, doing work against the extra g-force to add energy", "The bowl is downhill all the way", "The wheels push you"], a: 1,
      e: "Standing up while the ramp is pushing hardest on you (in the curve) adds energy, like pumping a swing. Crouching where the push is smaller costs less. The difference becomes extra speed." },
    { ch: "ch-falls",
      q: "Falling from standing, your body reaches the ground at about 4.4 m/s. Why does rolling out of a fall hurt less than landing stiff-armed?",
      o: ["Rolling slows gravity", "Rolling makes you lighter", "Rolling spreads the stop over a longer distance and time, so the average force is much smaller", "There's no difference"], a: 2,
      e: "Stopping from 4.4 m/s in 5 cm means an average deceleration of about 20 g; spreading it over 0.5 m by rolling brings it down to about 2 g. That's why stiff arms break wrists." },
    { ch: "ch-falls",
      q: "Which rule does the RSFI skateboarding rulebook (2022, World Skate rules) set for helmets in park competitions?",
      o: ["All park athletes, of any age, must wear a helmet in practice and competition", "Helmets are optional", "Only under-12s must wear a helmet", "Helmets are banned"], a: 0,
      e: "In park, every athlete must wear a helmet in practice and competition; in street, athletes under 18 must. Outside competition, a helmet is just sensible: falls are part of learning." },
    { ch: "ch-wheels",
      q: "A 54 mm skateboard wheel rolling at 15 km/h spins at roughly what rate?",
      o: ["About 15 rpm", "About 150 rpm", "About 1,500 rpm", "About 150,000 rpm"], a: 2,
      e: "Circumference = π × 0.054 ≈ 0.17 m. 15 km/h = 4.17 m/s, so 4.17 ÷ 0.17 ≈ 24.6 turns per second ≈ 1,474 rpm. That's what the bearings must handle." },
    { ch: "ch-wheels",
      q: "Why do softer, bigger wheels suit rough streets better?",
      o: ["They're always faster on smooth ramps", "They deform over small stones and cracks and roll over them more easily, so you get less vibration and fewer sudden stops", "They make the board lighter", "They make tricks easier on every surface"], a: 1,
      e: "A bigger wheel meets a crack at a gentler angle, and softer urethane absorbs bumps. Harder, smaller wheels are lighter and slide more predictably on smooth park surfaces." },
    { ch: "ch-wheels",
      q: "In a park final, five judges score a run 82, 85, 80, 90 and 78. Using World Skate's method, what is the run score?",
      o: ["83.00", "90.00", "78.00", "82.33"], a: 3,
      e: "Drop the highest (90) and lowest (78), then average the remaining three: (82 + 85 + 80) ÷ 3 = 82.33. Each judge scores from 0 to 100; the best run counts." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- RAMP & OLLIE LAB ----------
  // Ramp: v = √(2gh) at the bottom (no friction); g-load at the bottom of a transition of radius r = 1 + v²/(g r) = 1 + 2h/r.
  // Ollie: take-off vertical speed √(2gH), airtime 2v/g, forward distance = rolling speed × airtime. Idealised; for learning only.
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("sb-h")) return;
    const g = 9.81;
    function update() {
      const h = +$("sb-h").value, r = +$("sb-r").value, m = +$("sb-m").value, H = +$("sb-o").value, s = +$("sb-s").value;
      $("sb-h-o").textContent = h.toFixed(1) + " m";
      $("sb-r-o").textContent = r.toFixed(1) + " m";
      $("sb-m-o").textContent = m + " kg";
      $("sb-o-o").textContent = Math.round(H * 100) + " cm";
      $("sb-s-o").textContent = s.toFixed(1) + " m/s";
      const v = Math.sqrt(2 * g * h), gl = 1 + 2 * h / r;
      $("sb-v").textContent = (v * 3.6).toFixed(1) + " km/h";
      $("sb-g").textContent = gl.toFixed(2) + " g";
      $("sb-g").style.color = gl >= 3.5 ? "#ff8a70" : (gl >= 2.5 ? "#ffd27a" : "#fff");
      $("sb-f").textContent = Math.round(m * g * gl).toLocaleString("en-IN") + " N";
      const vz = Math.sqrt(2 * g * H), t = 2 * vz / g;
      $("sb-vz").textContent = vz.toFixed(2) + " m/s";
      $("sb-air").textContent = t.toFixed(2) + " s";
      $("sb-dist").textContent = (s * t).toFixed(2) + " m";
      $("sb-bar").style.width = Math.min(100, gl / 5 * 100).toFixed(0) + "%";
    }
    ["sb-h", "sb-r", "sb-m", "sb-o", "sb-s"].forEach(id => $(id).addEventListener("input", update));
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
