// Kinetic: kitesurfing page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "kitesurfing",
    v1: "Physics: nailed it 🪁",
    b1: "You've got the physics of kitesurfing. Skim the chapters for anything you missed, then scroll to “Where to learn” for IKO-certified schools, championships and instructor courses at your level. Knowing the science is a great start; it isn't the same as kite control, self-rescue or reading a real spot.",
    b2: "You have the basics. Fill the gaps below before your next session, especially the wind window and gust safety: they're the chapters that keep the kite under control.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to learn at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, an IKO level or a replacement for lessons. Learn with an IKO-certified (or equivalent) instructor and a rescue boat, know your quick release, be able to swim, and check the wind and its direction before every session."
  };
  const CHAPTERS = {
    "ch-apparent": "Ch 1 · Apparent wind",
    "ch-lift":     "Ch 2 · Kite lift & power",
    "ch-window":   "Ch 3 · The wind window",
    "ch-board":    "Ch 4 · Edging, leaning & planing",
    "ch-upwind":   "Ch 5 · Riding upwind",
    "ch-safety":   "Ch 6 · Wind, weather & safety"
  };
  const QUESTIONS = [
    { ch: "ch-apparent",
      q: "True wind is 15 kn from your side and you ride at 20 kn. What wind do you feel (apparent wind)?",
      o: ["5 kn", "25 kn", "35 kn", "15 kn"], a: 1,
      e: "At right angles the two add like a right triangle: √(15² + 20²) = 25 kn, swung towards your nose (about 37° from it)." },
    { ch: "ch-apparent",
      q: "As you ride faster across the wind, what happens to the apparent wind's direction?",
      o: ["It swings round behind you", "It doesn't change", "It moves forward, towards your nose", "It always points straight down"], a: 2,
      e: "Your own motion adds a headwind, so the apparent wind gets stronger and comes from further forward: at 15 kn in 15 kn of side wind it's at 45°." },
    { ch: "ch-lift",
      q: "Kite pull is F = ½ ρ v² S C_L. If the wind the kite feels doubles, the pull…",
      o: ["doubles", "stays the same", "halves", "becomes four times bigger"], a: 3,
      e: "Pull goes with v², so 2² = 4 times. That's why small wind changes feel so big on the bar." },
    { ch: "ch-lift",
      q: "Why do riders use a smaller kite when the wind gets stronger?",
      o: ["Pull grows with kite area, so less area keeps the pull manageable", "Small kites fly higher", "Big kites can't fly in strong wind at all", "Small kites are heavier"], a: 0,
      e: "F is proportional to area S. In our model a 7 m² kite at 20 kn pulls about as hard as a 12 m² kite at 15 kn mid-window." },
    { ch: "ch-lift",
      q: "The energy flowing through each square metre of wind is ½ ρ v³. Going from 10 kn to 20 kn multiplies it by…",
      o: ["2", "8", "4", "16"], a: 1,
      e: "2³ = 8. In our lab that's from about 83 W to about 667 W per square metre." },
    { ch: "ch-window",
      q: "Where in the wind window does a kite pull hardest?",
      o: ["Deep in the middle, the power zone, where it flies fast across the wind", "Straight overhead", "At the very edge of the window", "On the ground"], a: 0,
      e: "In the power zone the kite moves quickly across the wind and feels far more apparent wind. At the edge (neutral zone) it barely moves and pulls gently." },
    { ch: "ch-window",
      q: "In our model a kite mid-window feels 1.3× the true wind, and in the power zone 1.6×. How much harder does it pull in the power zone than at the edge (1.0×)?",
      o: ["1.6 times", "About 1.3 times", "About 2.6 times", "10 times"], a: 2,
      e: "Pull follows the square: 1.6² = 2.56, about 2.6 times." },
    { ch: "ch-window",
      q: "What do you learn on the beach in IKO Level 1, before standing on a board?",
      o: ["Jumps and tricks", "Kite control at the edge of the window, launching and landing, and safety systems such as the quick release", "Racing starts", "Riding upwind"], a: 1,
      e: "Level 1 Discovery covers spot assessment, setup, safety systems, launching and landing, the wind window and the quick release." },
    { ch: "ch-board",
      q: "A 75 kg rider (736 N) feels 444 N of horizontal kite pull. About how far must they lean back from vertical?",
      o: ["About 5°", "About 85°", "About 60°", "About 31°"], a: 3,
      e: "tan θ ≈ pull ÷ weight = 444 ÷ 736 ≈ 0.60, so θ ≈ 31°. More pull means more lean, or more edge." },
    { ch: "ch-board",
      q: "If a board just planes at 8 kn, roughly how much of that water lift does it get at 6 kn?",
      o: ["About 56%: lift grows with speed squared", "75%: lift grows with speed", "100%: speed doesn't matter", "Twice as much"], a: 0,
      e: "(6 ÷ 8)² ≈ 0.56. Below planing speed the board sinks back into the water and drag rises." },
    { ch: "ch-upwind",
      q: "You ride at 15 kn, 50° off the wind. How fast are you making progress upwind (VMG)?",
      o: ["15 kn", "0 kn", "About 9.6 kn", "About 25 kn"], a: 2,
      e: "VMG = 15 × cos 50° ≈ 9.6 kn. At 90° off the wind your VMG is zero." },
    { ch: "ch-upwind",
      q: "Which IKO level includes riding upwind and is the one the IKO says lets you ride on your own?",
      o: ["Level 1 Discovery", "Level 3 Independent", "There is no such level", "Instructor Level 1"], a: 1,
      e: "Level 3 Independent covers edging, riding upwind, transitions, self-launch and deep-water self-rescue (minimum age 12)." },
    { ch: "ch-safety",
      q: "A gust takes the wind from 15 kn to 21 kn. About how much harder does the kite pull?",
      o: ["About 40% harder", "No change", "About 4 times", "Almost twice as hard"], a: 3,
      e: "(21 ÷ 15)² ≈ 1.96. A 40% gust nearly doubles the pull, which is how riders get dragged or lofted." },
    { ch: "ch-safety",
      q: "Why is an offshore wind (blowing from the land out to sea) dangerous for a kitesurfer?",
      o: ["It carries you away from the beach if anything goes wrong", "It's always too light to fly", "It makes the water colder", "It isn't dangerous at all"], a: 0,
      e: "If you crash, lose the board or the wind drops, offshore wind takes you out to sea. Beginners learn in steady cross-shore wind with a rescue boat." },
    { ch: "ch-safety",
      q: "1 knot is about…",
      o: ["1 km/h", "10 km/h", "1.85 km/h", "0.5 km/h"], a: 2,
      e: "1 kn = 1.852 km/h (one nautical mile per hour), so a 15 kn wind is about 28 km/h." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- KITE LAB ----------
  // Pull F = ½ ρ v² S CL (ρ 1.225, CL 0.6, illustrative). Wind at kite = true wind × position factor
  // (edge 1.0, mid 1.3, power zone 1.6, illustrative). Gust = 1.4 × wind → force × 1.96. Power flux = ½ ρ v³.
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("ks-w")) return;
    const rho = 1.225, CL = 0.6, KN = 0.514444, g = 9.81;
    let f = 1.3;
    const fmt = n => Math.round(n).toLocaleString("en-US");
    function update() {
      const W = +$("ks-w").value, S = +$("ks-s").value, m = +$("ks-m").value;
      $("ks-w-o").textContent = W + " kn";
      $("ks-s-o").textContent = S + " m²";
      $("ks-m-o").textContent = m + " kg";
      const v = W * KN * f, F = 0.5 * rho * v * v * S * CL, Fg = F * 1.96;
      $("ks-aw").textContent = (W * f).toFixed(1) + " kn";
      $("ks-f").textContent = fmt(F) + " N";
      $("ks-kg").textContent = fmt(F / g) + " kg";
      $("ks-bw").textContent = Math.round(F / (m * g) * 100) + "%";
      $("ks-gust").textContent = fmt(Fg) + " N";
      $("ks-pw").textContent = fmt(0.5 * rho * Math.pow(W * KN, 3)) + " W";
      $("ks-bar").style.width = Math.min(100, Fg / (m * g) * 100) + "%";
    }
    ["ks-w", "ks-s", "ks-m"].forEach(id => $(id).addEventListener("input", update));
    document.querySelectorAll("#ks-pos button").forEach(b => b.addEventListener("click", () => {
      f = +b.dataset.f;
      document.querySelectorAll("#ks-pos button").forEach(x => x.setAttribute("aria-pressed", x === b ? "true" : "false"));
      update();
    }));
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
