// Kinetic: swimming page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "swimming",
    v1: "Physics: nailed it 🏊",
    b1: "You've got the physics of the water. Skim the chapters for anything you missed, then scroll to “Where to go” for lessons, swimathons and open-water events at your level. Knowing the physics is a great start; it is not the same as being a safe, trained open-water swimmer.",
    b2: "You have the basics. Fill the gaps below before your next swim or event, and the race briefing will make a lot more sense.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to swim at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, a swimming grade, a lifesaving qualification or a fitness assessment, and a high score does not qualify you for open water or for any event. Learn and progress with a qualified coach, swim open water only where lifeguards or safety boats cover you, meet each event's own entry and medical requirements, and take a recognised lifesaving course (for example from the Rashtriya Life Saving Society (India)) before you rescue anyone."
  };
  const CHAPTERS = {
    "ch-drag":       "Ch 1 · Drag: form, friction & waves",
    "ch-float":      "Ch 2 · Buoyancy & body position",
    "ch-propulsion": "Ch 3 · Propulsion: lift vs drag, honestly",
    "ch-breath":     "Ch 4 · Breathing & energy",
    "ch-open":       "Ch 5 · Open water: currents & sighting",
    "ch-cold":       "Ch 6 · Cold, heat & staying safe"
  };
  const QUESTIONS = [
    { ch: "ch-drag",
      q: "You double your swimming speed. Roughly how much bigger does the water's drag on you become?",
      o: ["Twice as big", "The same", "About four times as big", "About eight times as big"], a: 2,
      e: "Drag grows with speed squared: 2² = 4. The power you need (drag × speed) grows with speed cubed, so doubling speed needs about 8× the power. That's why the last few tenths of a second cost so much." },
    { ch: "ch-drag",
      q: "Which three kinds of drag act on a swimmer at the surface?",
      o: ["Form (pressure) drag, skin-friction drag and wave drag", "Gravity drag, buoyancy drag and lift drag", "Only friction between skin and water", "Air drag on the arms, and nothing else"], a: 0,
      e: "Form drag comes from the shape you push through the water (a low, long, streamlined body makes less). Skin friction is the water dragging along your skin and costume. Wave drag is the energy you spend making waves at the surface; it grows steeply with speed." },
    { ch: "ch-drag",
      q: "Racers glide and kick underwater after the start, and World Aquatics rules make them surface by 15 m in freestyle, backstroke and butterfly. Why is underwater so fast?",
      o: ["The water is warmer underwater", "Below the surface you make almost no waves, so wave drag nearly disappears", "Goggles work better underwater", "There is less buoyancy underwater"], a: 1,
      e: "At the surface, part of your effort goes into making waves. A streamlined body a little below the surface makes far smaller waves, so for the same effort it goes faster. The 15 m limit stops races turning into underwater kicking contests." },
    { ch: "ch-float",
      q: "With full lungs most people just float; after breathing out completely, many sink. Why?",
      o: ["Exhaling makes your body heavier", "The water's density changes as you breathe out", "Your muscles tense when you breathe out", "Your lungs hold several litres of air, which adds volume (and upthrust) but almost no mass"], a: 3,
      e: "Upthrust equals the weight of water you displace (Archimedes). Taking a full breath adds roughly 4–5 litres of volume, about 4–5 kg of extra upthrust, for a few grams of air. Your average density drops just below water's, so you float." },
    { ch: "ch-float",
      q: "Why do many adult beginners' legs sink when they try to float flat?",
      o: ["Legs are hollow", "Because they kick too hard", "Your centre of buoyancy (near the chest) is closer to your head than your centre of mass (near the hips), so the pair of forces rotates your legs down", "The pool is deeper at one end"], a: 2,
      e: "Upthrust acts at the centre of buoyancy, around the air-filled chest. Weight acts at the centre of mass, nearer the hips. The two forces are a few centimetres apart, which makes a turning effect that swings the legs down. Pressing the chest down slightly, keeping the head neutral and a gentle kick level you out." },
    { ch: "ch-float",
      q: "Sea water is about 2.5% denser than pool water. For a 70 kg swimmer, that means…",
      o: ["Noticeably more buoyant: nearly 2 kg more upthrust", "No difference at all", "Less buoyant, because salt is heavy", "It only matters below 10 m depth"], a: 0,
      e: "A 70 kg swimmer with full lungs displaces about 72 litres. In sea water that's 72 × 1.025 ≈ 73.8 kg of upthrust instead of 72 kg: about 1.8 kg more. Most people feel it immediately; they sit higher and their legs drop less." },
    { ch: "ch-propulsion",
      q: "What does current research say about how your hand and arm push you forward?",
      o: ["It's all lift, like an aeroplane wing", "It's all drag, like a canoe paddle", "Both pushing water backwards (drag) and the hand's angle (lift) contribute, unsteady flow matters, and the exact split is still being studied", "Hands do almost nothing; the legs do all the work"], a: 2,
      e: "In the 1970s, lift-based 'sculling' explanations were popular. Later studies found that pushing water backwards (drag) does much of the work, with lift contributing depending on hand angle and stroke phase. Real strokes are unsteady (vortices, accelerating water), so simple models of either kind are incomplete." },
    { ch: "ch-propulsion",
      q: "Whatever the exact mechanism, swimming propulsion always comes down to…",
      o: ["Newton's third law: you push water backwards, the water pushes you forwards", "Boyle's law", "Ohm's law", "The Bernoulli effect alone"], a: 0,
      e: "Lift or drag, the only thing you can push against is water. Accelerate water backwards and you get an equal and opposite push forwards. Water that you only stir sideways or up and down is wasted effort." },
    { ch: "ch-breath",
      q: "Per kilometre, roughly how much energy does swimming cost compared with running, for the same person?",
      o: ["About the same", "About half as much", "About 100 times as much", "Several times as much"], a: 3,
      e: "Water is about 800 times denser than air, so drag is a much bigger deal than in running. Studies of front crawl put a good swimmer's cost at very roughly 0.7–1 kJ per metre, against about 0.3 kJ per metre for a 70 kg runner: around 2.5–3.5×, and beginners spend far more. That's why 1 km of open water feels like a big deal." },
    { ch: "ch-breath",
      q: "Why is hyperventilating (lots of fast deep breaths) before a long underwater swim dangerous?",
      o: ["It raises oxygen to toxic levels", "It flushes out carbon dioxide, which delays your urge to breathe, so oxygen can fall low enough to black out without warning", "It makes you sink", "It cools you down too fast"], a: 1,
      e: "The urge to breathe is driven mainly by rising CO₂, not falling oxygen. Over-breathing lowers CO₂ but adds little oxygen, so the warning comes late or not at all. Swimmers have drowned this way in calm pools. Never do breath-hold games alone or competitively." },
    { ch: "ch-open",
      q: "You swim at 1.0 m/s against a 0.5 m/s current. How long does 1 km take?",
      o: ["About 17 minutes", "About 25 minutes", "About 33 minutes", "About 50 minutes"], a: 2,
      e: "Your speed over the ground is 1.0 − 0.5 = 0.5 m/s. 1,000 m ÷ 0.5 m/s = 2,000 s ≈ 33 minutes, twice as long as in still water. With the current behind you, the same kilometre takes about 11 minutes." },
    { ch: "ch-open",
      q: "Open-water swimmers lift their eyes to a buoy or landmark every few strokes. Why does this matter so much?",
      o: ["Being only 10° off line over 1 km puts you about 170 m off course, and every extra metre is wasted effort", "To breathe more easily", "The referee requires it", "To warm up the neck muscles"], a: 0,
      e: "There's no black line in the sea. A 10° error over 1 km is 1,000 × sin 10° ≈ 174 m sideways. Short, regular sighting (eyes up just above the water, then breathe to the side) keeps your line straight. Goa's swimathon places sighting buoys every 150–200 m." },
    { ch: "ch-open",
      q: "You're caught in a rip current pulling you away from the beach. The standard advice is…",
      o: ["Swim hard straight back against it", "Dive to the bottom and crawl", "Take off your cap so lifeguards can see your hair", "Stay calm and float, signal for help, and swim parallel to the shore to get out of the narrow channel before heading in"], a: 3,
      e: "Rips are usually narrow channels of seaward flow, often faster than a swimmer. Fighting one head-on exhausts you. Float to conserve energy, raise an arm to signal, and swim across it (parallel to the beach) to escape, then swim in. Better still: swim only between the lifeguards' flags." },
    { ch: "ch-cold",
      q: "Water at the same temperature as air pulls heat from your body far faster, because water…",
      o: ["Is darker than air", "Conducts heat about 25 times better than air and stores far more heat per litre", "Contains salt", "Is always moving"], a: 1,
      e: "Water's thermal conductivity is about 0.6 W/m·K, roughly 25 times that of air, and it can absorb far more heat per litre. Air at 20 °C feels pleasant; water at 20 °C can chill a slim swimmer within an hour. World Aquatics makes wetsuits compulsory in races below 18 °C." },
    { ch: "ch-cold",
      q: "Goa's swimathon, in 26–28 °C sea water, doesn't allow wetsuits. What reason does the organiser give?",
      o: ["Wetsuits give an unfair advantage", "Jellyfish stick to neoprene", "Wetsuits stop the timing tags working", "In warm water a wetsuit makes you overheat and dehydrate quickly"], a: 3,
      e: "Your muscles make several hundred watts of heat while you swim. In warm tropical water there's little temperature difference to carry it away, and insulation makes it worse. In Indian seas, overheating, dehydration, sun and jellyfish are usually bigger issues than cold." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- SWIM LAB ----------
  // Illustrative model: drag = ½ρ·CdA·v² with CdA = 0.06 m² (a typical adult freestyle order of magnitude);
  // reference 70 kg swimmer, volume 72 L with full lungs / 67.5 L after a full exhale.
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("sw-speed")) return;
    let dir = "against", rho = 1000, vol = 72;
    const CDA = 0.06, MASS = 70;
    function fmtTime(t) {
      if (!isFinite(t)) return "never";
      if (t < 3600) return (t / 60).toFixed(1) + " min";
      const h = Math.floor(t / 3600), m = Math.round((t - h * 3600) / 60);
      return h + " h " + String(m).padStart(2, "0") + " min";
    }
    function update() {
      const v = +$("sw-speed").value, d = +$("sw-dist").value, c = +$("sw-current").value;
      $("sw-speed-o").textContent = v.toFixed(2) + " m/s";
      $("sw-dist-o").textContent = d >= 1000 ? (d / 1000).toFixed(1) + " km" : d + " m";
      $("sw-current-o").textContent = c === 0 ? "none" : c.toFixed(2) + " m/s";
      const drag = 0.5 * rho * CDA * v * v;
      $("sw-drag").textContent = drag.toFixed(1) + " N";
      $("sw-power").textContent = Math.round(drag * v) + " W";
      $("sw-power2").textContent = Math.round(drag * v * 8) + " W";
      let g, aim = "—", drift = "—";
      if (dir === "with") g = v + c;
      else if (dir === "against") g = v - c;
      else {
        if (c >= v) { g = 0; aim = "can't hold the line"; }
        else { g = Math.sqrt(v * v - c * c); aim = (Math.asin(c / v) * 180 / Math.PI).toFixed(0) + "° upstream"; }
        drift = Math.round(c * d / v) + " m";
      }
      $("sw-aim").textContent = aim;
      $("sw-drift").textContent = drift;
      if (g <= 0) {
        $("sw-ground").textContent = dir === "against" ? "going backwards" : "0 m/s";
        $("sw-ground").style.color = "#ff8a70";
        $("sw-time").textContent = "never";
        $("sw-bar").style.width = "100%";
      } else {
        $("sw-ground").textContent = g.toFixed(2) + " m/s";
        $("sw-ground").style.color = "#fff";
        const t = d / g;
        $("sw-time").textContent = fmtTime(t);
        $("sw-bar").style.width = Math.min(100, t / 7200 * 100).toFixed(0) + "%";
      }
      const net = vol * rho / 1000 - MASS;
      $("sw-float").textContent = (net >= 0 ? "+" : "−") + Math.abs(net).toFixed(1) + " kg";
      $("sw-float-s").textContent = net >= 0 ? "floats · Ch 2" : "sinks slowly · Ch 2";
    }
    ["sw-speed", "sw-dist", "sw-current"].forEach(id => $(id).addEventListener("input", update));
    function seg(id, fn) {
      document.querySelectorAll("#" + id + " button").forEach(b => b.addEventListener("click", () => {
        fn(b);
        document.querySelectorAll("#" + id + " button").forEach(x => x.setAttribute("aria-pressed", x === b ? "true" : "false"));
        update();
      }));
    }
    seg("sw-dir", b => { dir = b.dataset.dir; });
    seg("sw-water", b => { rho = +b.dataset.rho; });
    seg("sw-lungs", b => { vol = +b.dataset.vol; });
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
