// Kinetic: mountaineering page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "mountaineering",
    v1: "Physics: nailed it 🏔️",
    b1: "You've got the physics of the mountains. Skim the chapters for anything you missed, then scroll to “Where to train” for courses at your level. Knowing the science is a great start; it isn't the same as the rope, snow, ice and judgement skills a mountaineering institute teaches on the mountain.",
    b2: "You have the basics. Fill the gaps below before your first trek or course, especially thin air and acclimatisation: they're the chapters that keep you and your team safe.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to train at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, a mountaineering course or a substitute for training at a recognised institute with qualified instructors. Go up slowly, never sleep higher with symptoms of altitude sickness, descend if they get worse, and get a medical check before any high-altitude trek or course."
  };
  const CHAPTERS = {
    "ch-air":       "Ch 1 · Thin air: pressure & oxygen",
    "ch-acclim":    "Ch 2 · Acclimatisation & altitude illness",
    "ch-cold":      "Ch 3 · Cold, wind chill & frostbite",
    "ch-load":      "Ch 4 · Load, height & energy",
    "ch-slip":      "Ch 5 · Slips on snow & self-arrest",
    "ch-avalanche": "Ch 6 · Snow slopes & avalanches"
  };
  const QUESTIONS = [
    { ch: "ch-air",
      q: "At 5,000 m, what share of the air is oxygen?",
      o: ["Still about 21%", "About 10%", "About 50%", "About 5%"], a: 0,
      e: "The mix doesn't change: oxygen is 20.95% of the air at every height. What falls is the total pressure, so each breath holds fewer oxygen molecules." },
    { ch: "ch-air",
      q: "The air pressure at about 4,450 m is 58.1 kPa. What's the oxygen partial pressure?",
      o: ["58.1 kPa", "About 12.2 kPa", "About 21.2 kPa", "About 2.9 kPa"], a: 1,
      e: "PO₂ = 0.2095 × 58.1 ≈ 12.2 kPa, about 57% of the 21.2 kPa at sea level." },
    { ch: "ch-air",
      q: "According to the CDC, the oxygen pressure you breathe in at about 3,050 m is what share of the sea-level value?",
      o: ["About 95%", "About 33%", "About 69%", "About 10%"], a: 2,
      e: "The CDC gives 69% at about 3,050 m (10,000 ft), and says arriving there quickly can drop blood oxygen saturation to 88–91%." },
    { ch: "ch-acclim",
      q: "Once you're above 3,000 m, by how much should your sleeping altitude rise each day, according to the Wilderness Medical Society guidance the CDC quotes?",
      o: ["1,500 m", "1,000 m", "As much as you feel like", "No more than 500 m"], a: 3,
      e: "No more than 500 m a day in sleeping altitude above 3,000 m, plus an extra night for every 1,000 m gained." },
    { ch: "ch-acclim",
      q: "You have a mild headache and nausea on arriving at a higher camp. What should you do?",
      o: ["Don't go higher to sleep until the symptoms have gone; descend if they get worse", "Climb higher to acclimatise faster", "Ignore it: it's just tiredness", "Exercise hard to warm up"], a: 0,
      e: "Those are AMS symptoms. The CDC's rules: never ascend to sleep with symptoms, however mild, and descend if they get worse despite rest or treatment." },
    { ch: "ch-acclim",
      q: "A very fit marathon runner and an unfit friend fly straight to 3,500 m. Who's less likely to get altitude sickness?",
      o: ["The runner, because fitness protects you", "Neither: the CDC says training and fitness don't affect the risk", "The unfit friend", "Whoever eats more"], a: 1,
      e: "Fitness doesn't protect against altitude illness; time to acclimatise does. Fit people sometimes push higher, faster, and get sick." },
    { ch: "ch-cold",
      q: "It's 25 °C at sea level. Using the standard lapse rate of 6.5 °C per 1,000 m, about how cold is it at 5,000 m?",
      o: ["About 18.5 °C", "About 0 °C", "About −7.5 °C", "About −32.5 °C"], a: 2,
      e: "25 − 6.5 × 5 = −7.5 °C. Real weather varies, but every kilometre up is roughly 6.5 °C colder." },
    { ch: "ch-cold",
      q: "The air is −7.5 °C with a 30 km/h wind. Roughly what does the wind chill index say it feels like on bare skin?",
      o: ["−7.5 °C", "+5 °C", "−40 °C", "About −16 °C"], a: 3,
      e: "WC = 13.12 + 0.6215T − 11.37V^0.16 + 0.3965T·V^0.16 ≈ −16 °C. Wind strips heat from skin faster." },
    { ch: "ch-cold",
      q: "According to the US National Weather Service, can you get frostbite when the air is 3 °C but the wind chill is −2 °C?",
      o: ["No: frostbite needs the actual air temperature below freezing, though you can still get hypothermia", "Yes, always", "Only in the sun", "Only above 5,000 m"], a: 0,
      e: "Wind chill can't cool skin below the air temperature. Frostbite needs air below 0 °C; cold and wet can still cause hypothermia." },
    { ch: "ch-load",
      q: "A climber and pack weigh 85 kg together. About how much lifting work does gaining 1,000 m take?",
      o: ["About 85 kJ", "About 834 kJ", "About 8.5 kJ", "About 83,400 kJ"], a: 1,
      e: "W = m g h = 85 × 9.81 × 1000 ≈ 834 kJ. At 20% muscle efficiency the body burns about five times that: roughly 1,000 kcal." },
    { ch: "ch-load",
      q: "Why does a heavier pack make a climb so much harder?",
      o: ["The air is thinner with a pack", "It changes the slope", "Every extra kilo has to be lifted through the full height: work = m g h", "It doesn't make a difference"], a: 2,
      e: "Going from a 0 kg to a 15 kg pack raises the lifting energy for 1,000 m from about 821 to 996 kcal in our example: pack light." },
    { ch: "ch-slip",
      q: "On a slope at angle θ with friction coefficient μ, what is a sliding climber's acceleration down the slope?",
      o: ["g", "μ g", "g cos θ", "g (sin θ − μ cos θ)"], a: 3,
      e: "Gravity along the slope is g sin θ; friction holds back μ g cos θ. On a 30° slope of hard snow (μ = 0.1): 9.81 × (0.5 − 0.087) ≈ 4.06 m/s²." },
    { ch: "ch-slip",
      q: "Why must self-arrest with an ice axe happen immediately after a slip on hard snow?",
      o: ["Because speed builds fast: on a 30° icy slope you'd be doing about 46 km/h after 20 m", "Because the axe gets cold", "Because snow gets softer lower down", "It doesn't matter when"], a: 0,
      e: "v = √(2 a d) = √(2 × 4.06 × 20) ≈ 12.7 m/s ≈ 46 km/h. The earlier you stop, the easier it is." },
    { ch: "ch-avalanche",
      q: "According to Avalanche.org, on what slope angles do most slab avalanches start?",
      o: ["Below 15°", "Between 30° and 50°", "Only on vertical cliffs", "Only on flat glaciers"], a: 1,
      e: "A Swiss dataset of over 1,000 avalanches found 96% released on 30–50° slopes, most on 34–45°. They can run out onto much gentler ground below." },
    { ch: "ch-avalanche",
      q: "A slab's weight pulls on the weak layer beneath it with shear stress τ = ρ g d sin θ. What happens as the slope gets steeper?",
      o: ["The stress falls", "Nothing changes", "The stress rises, so a weak layer is more likely to fail", "The snow gets lighter"], a: 2,
      e: "sin θ grows with the angle: for a 0.5 m slab at 200 kg/m³, about 490 Pa at 30° and 604 Pa at 38°." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- ALTITUDE LAB ----------
  // International Standard Atmosphere: P = 101.325 × (1 − 2.25577e-5 × h)^5.25588 kPa. Oxygen partial pressure = 0.2095 × P.
  // Air temperature falls 6.5 °C per 1,000 m (standard lapse rate) from your sea-level temperature (illustrative: real weather varies).
  // Wind chill (NWS / Environment Canada index, metric): 13.12 + 0.6215T − 11.37V^0.16 + 0.3965T·V^0.16; defined only for T ≤ 10 °C and V ≥ 5 km/h.
  // Energy to climb 1,000 m: (70 kg body + load) × 9.81 × 1000 ÷ 0.20 muscle efficiency (illustrative), in kcal (÷ 4184).
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("mt-alt")) return;
    const BODY = 70, EFF = 0.20;
    const deg = t => (t < 0 ? "−" : "") + Math.abs(t).toFixed(1) + " °C";
    function update() {
      const h = +$("mt-alt").value, t0 = +$("mt-t0").value, v = +$("mt-wind").value, load = +$("mt-load").value;
      $("mt-alt-o").textContent = h.toLocaleString("en-IN") + " m";
      $("mt-t0-o").textContent = t0 + " °C";
      $("mt-wind-o").textContent = v + " km/h";
      $("mt-load-o").textContent = load + " kg";
      const p = 101.325 * Math.pow(1 - 2.25577e-5 * h, 5.25588);
      const t = t0 - 6.5 * h / 1000;
      $("mt-p").textContent = p.toFixed(1) + " kPa";
      $("mt-o2").textContent = (0.2095 * p).toFixed(1) + " kPa";
      $("mt-pct").textContent = Math.round(100 * p / 101.325) + "%";
      $("mt-t").textContent = deg(t);
      if (t <= 10 && v >= 5) {
        const k = Math.pow(v, 0.16), wc = 13.12 + 0.6215 * t - 11.37 * k + 0.3965 * t * k;
        $("mt-wc").textContent = (Math.round(wc) < 0 ? "−" : "") + Math.abs(Math.round(wc)) + " °C";
      } else $("mt-wc").textContent = "not defined";
      const kcal = (BODY + load) * 9.81 * 1000 / EFF / 4184;
      $("mt-e").textContent = Math.round(kcal).toLocaleString("en-IN") + " kcal";
      $("mt-bar").style.width = Math.round(100 * p / 101.325) + "%";
    }
    ["mt-alt", "mt-t0", "mt-wind", "mt-load"].forEach(id => $(id).addEventListener("input", update));
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
