// Kinetic: paragliding page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "paragliding",
    v1: "Physics: nailed it 🪂",
    b1: "You've got the physics. Skim the chapters for what you missed, then scroll to “Where to go” to find training at your level. Knowing the physics is a great start; it is not the same as being trained to fly.",
    b2: "You have the basics. Fill the gaps below before your next flight or course, and the briefings will make a lot more sense.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to fly at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, a pilot rating or a fitness-to-fly assessment, and a high score does not qualify you to fly. Flying a paraglider solo requires training and a rating from a qualified instructor at a recognised school (for example an APPI, BHPA or USHPA school, or one recognised by the Aero Club of India or Paragliding Association of India), plus any registration your state requires. As a passenger, fly only with a registered tandem pilot."
  };
  const CHAPTERS = {
    "ch-lift":     "Ch 1 · Lift, drag & the wing",
    "ch-glide":    "Ch 2 · Glide ratio, sink & wind",
    "ch-thermals": "Ch 3 · Thermals & ridge lift",
    "ch-loading":  "Ch 4 · Wing loading & altitude",
    "ch-stall":    "Ch 5 · Stalls, collapses & turns",
    "ch-weather":  "Ch 6 · Weather & micro-meteorology"
  };
  const QUESTIONS = [
    { ch: "ch-lift",
      q: "A paraglider has no engine. What actually keeps it flying?",
      o: ["Hot air trapped inside the cells", "It is always descending through the air; gravity pulls it forward along a shallow slope and the moving air over the wing makes lift", "The pilot's weight pulls the wing open like a parachute that floats", "Static electricity between the fabric and the air"], a: 1,
      e: "A paraglider is a glider: relative to the air around it, it always goes down a gentle slope. Gravity provides the 'push', and the airflow over the curved, inflated wing produces lift that almost balances your weight. Climbing only happens when the air itself is rising faster than you sink." },
    { ch: "ch-lift",
      q: "Lift grows with airspeed. If you fly 20% faster at the same angle of attack, lift becomes roughly…",
      o: ["20% larger", "The same", "About 44% larger", "Twice as large"], a: 2,
      e: "Lift = ½ × air density × speed² × wing area × lift coefficient. Speed is squared: 1.2² = 1.44, so about 44% more lift. That's why small speed changes matter so much near the ground." },
    { ch: "ch-glide",
      q: "Your wing's glide ratio is 8.5 in still air. You launch 1,000 m above the landing field. About how far can you glide in still air?",
      o: ["850 m", "8.5 km", "85 km", "1 km"], a: 1,
      e: "Glide ratio is distance forward per metre of height lost: 1,000 m × 8.5 = 8,500 m. A thousand metres of height buys you about 8.5 km, if the air is neither rising nor sinking and there's no wind." },
    { ch: "ch-glide",
      q: "Same wing (trim speed about 37 km/h), but now there's a 15 km/h headwind. What happens to your glide over the ground?",
      o: ["Nothing changes; glide ratio is a property of the wing", "It improves, because headwind gives more lift", "It roughly halves to about 5:1, because ground speed drops to 22 km/h while you still sink at the same rate", "You will stop moving forward completely"], a: 2,
      e: "Your sink rate through the air doesn't care about wind, but your ground speed does: 37 − 15 = 22 km/h. Ground glide ≈ 22 ÷ 4.4 km/h of sink ≈ 5. A tailwind does the opposite (≈ 12:1). Pilots plan landings into wind for exactly this reason." },
    { ch: "ch-glide",
      q: "Your vario reads −1.2 m/s at trim speed. How long does a 1,000 m descent take in calm air?",
      o: ["About 14 minutes", "About 4 minutes", "About 1 hour", "About 83 seconds"], a: 0,
      e: "Time = height ÷ sink rate = 1,000 ÷ 1.2 ≈ 830 s ≈ 14 minutes. Every minute longer than that came from rising air you found." },
    { ch: "ch-thermals",
      q: "What is a thermal?",
      o: ["A warm wind blowing horizontally along a valley", "A cold downdraft under clouds", "Heat radiated by the sun onto your wing", "A rising bubble or column of air that the sun has warmed at the ground, lighter than the air around it"], a: 3,
      e: "Sun-heated ground warms the air touching it. That air is less dense than its surroundings, so it rises (buoyancy, the same physics as a hot-air balloon). Circle inside a column rising at 3 m/s while your wing sinks at 1.1 m/s and you climb at about 1.9 m/s." },
    { ch: "ch-thermals",
      q: "The ground temperature is 30 °C and the dew point is 14 °C. Using the pilot's rule of thumb (about 125 m per °C of spread), where should cumulus cloud bases form?",
      o: ["About 200 m above ground", "About 2,000 m above ground", "About 16 km up", "At ground level (fog)"], a: 1,
      e: "Spread = 30 − 14 = 16 °C. 16 × 125 m = 2,000 m. Rising air cools at about 10 °C per km while its dew point falls only about 2 °C per km, so they meet roughly 125 m higher for every degree of spread." },
    { ch: "ch-thermals",
      q: "Ridge (dynamic) lift is strongest where?",
      o: ["Upwind of the ridge, in front of the face, where wind blowing onto the slope is deflected upwards", "Directly behind the ridge, in its shelter", "Far above the ridge, at cloud base", "Only at night"], a: 0,
      e: "Wind hitting a slope is forced up. A 18 km/h (5 m/s) wind on a 30° slope has an upward component of about 5 × sin 30° = 2.5 m/s near the face. Behind (lee of) the ridge the air tumbles down in rotor: one of the most dangerous places to be." },
    { ch: "ch-loading",
      q: "You fly the same wing model in two sizes, at the same total weight. On the smaller wing (higher wing loading) you will…",
      o: ["Fly slower and sink less", "Have a much better glide ratio", "Be unable to launch", "Fly faster and sink faster, with roughly the same glide ratio"], a: 3,
      e: "Higher wing loading means the wing must fly faster to make enough lift. Speed scales with the square root of the loading. To first order the glide ratio barely changes, but everything (speed, sink, reactions) happens faster." },
    { ch: "ch-loading",
      q: "You take off at Billing, about 2,400 m above sea level. Compared with a sea-level site, your true airspeed at trim is…",
      o: ["About 12% higher, because thinner air needs more speed to make the same lift", "The same", "About 12% lower", "Twice as high"], a: 0,
      e: "Air density at 2,400 m is about 0.97 kg/m³ vs 1.225 at sea level. To make the same lift you need √(1.225/0.97) ≈ 1.13× the speed. Your instruments may read the same 'feel', but you cover ground and land faster up high." },
    { ch: "ch-stall",
      q: "What causes a paraglider to stall?",
      o: ["Flying too fast", "The angle of attack gets too high (usually from too much brake), the airflow separates from the top of the wing and lift collapses", "Flying through a cloud", "Releasing the brakes fully"], a: 1,
      e: "A wing stalls at a critical angle of attack, not at a speed you can read off a dial. Pulling the brakes deep raises the angle of attack; past the limit the flow separates and the wing falls back behind you. That's why schools drill smooth, measured brake inputs." },
    { ch: "ch-stall",
      q: "In a steady 60° banked turn, roughly how many g's are you and the wing pulling?",
      o: ["1 g", "1.4 g", "2 g", "6 g"], a: 2,
      e: "Load factor = 1 ÷ cos(bank). cos 60° = 0.5, so 2 g. Your wing has to make twice your weight in lift, sink rises steeply, and the stall speed goes up by √2 ≈ 1.41×. Spiral dives can go well past this." },
    { ch: "ch-stall",
      q: "What is an SIV course?",
      o: ["A tandem joyride over water", "A meteorology exam", "A course to repack your reserve parachute", "Simulation d'Incident en Vol: instructor-led training of collapses, stalls and recoveries, usually over water"], a: 3,
      e: "SIV teaches you, under radio guidance and with a rescue boat below, how your wing behaves when things go wrong and how to recover. Himachal Pradesh's 2025 amendment to its Aero Sports Rules made a safety (SIV) course mandatory for tandem pilots." },
    { ch: "ch-weather",
      q: "Why do pilots avoid flying near a rapidly growing cumulonimbus cloud?",
      o: ["Its updraft can be strong enough to suck a paraglider up into the cloud faster than it can descend, with turbulence, icing and lightning", "It blocks the view of the landing field", "It only brings light rain, which makes the wing heavy", "Its shadow cools the ground and stops all thermals"], a: 0,
      e: "Storm-cloud updrafts can exceed the best descent methods of a paraglider. Add gust fronts that spread tens of kilometres outward. The rule: if towers are building, land early." },
    { ch: "ch-weather",
      q: "Wind is 15 km/h at take-off height but only 5 km/h at the landing field. What is this effect, and why does it matter?",
      o: ["Venturi; it makes landing faster", "Wind gradient: friction slows air near the ground, so on final approach your airspeed can drop as you descend into slower air. Keep a bit of extra speed close to the ground", "Rotor; it only happens behind buildings", "Sea breeze; it only happens at the coast"], a: 1,
      e: "Ground friction slows the lowest layers of air. As you sink into slower-moving air on final, the headwind component drops and you can lose airspeed. Instructors teach a stable approach without deep brake until the flare." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- GLIDE LAB ----------
  // Illustrative model: EN-A-style wing, trim 37 km/h at 95 kg all-up at sea level; glide ratio user-set.
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("gl-height")) return;
    let alt = 0;
    function rho(h) { const T = 288.15 - 0.0065 * h; return 1.225 * Math.pow(T / 288.15, 4.2559); }
    function fmt(x, d) { return x.toFixed(d); }
    function update() {
      const H = +$("gl-height").value, wind = +$("gl-wind").value, LD = +$("gl-ld").value, W = +$("gl-weight").value, bank = +$("gl-bank").value;
      $("gl-height-o").textContent = H + " m";
      $("gl-wind-o").textContent = wind === 0 ? "calm" : (wind < 0 ? (-wind) + " km/h head" : wind + " km/h tail");
      $("gl-ld-o").textContent = fmt(LD, 1) + " : 1";
      $("gl-weight-o").textContent = W + " kg";
      $("gl-bank-o").textContent = bank + "°";
      const dens = Math.sqrt(1.225 / rho(alt));
      const n = 1 / Math.cos(bank * Math.PI / 180);
      const tas = 37 * Math.sqrt(W / 95) * dens;              // km/h, straight flight
      const sink = tas / 3.6 / LD;                             // m/s, straight flight
      const sinkTurn = sink * Math.pow(n, 1.5);
      const gs = tas + wind;
      const t = H / sink;                                      // s
      $("gl-tas").textContent = fmt(tas, 1) + " km/h";
      $("gl-sink").textContent = "−" + fmt(sink, 2) + " m/s";
      $("gl-time").textContent = fmt(t / 60, 1) + " min";
      $("gl-still").textContent = fmt(H * LD / 1000, 1) + " km";
      $("gl-gs").textContent = fmt(gs, 1) + " km/h";
      if (gs <= 0) {
        $("gl-ground").textContent = "going backwards";
        $("gl-ground").style.color = "#ff8a70";
        $("gl-gglide").textContent = "n/a";
        $("gl-bar").style.width = "0%";
      } else {
        const dist = gs / 3.6 * t / 1000;
        $("gl-ground").textContent = fmt(dist, 1) + " km";
        $("gl-ground").style.color = "#fff";
        $("gl-gglide").textContent = fmt(gs / 3.6 / sink, 1) + " : 1";
        $("gl-bar").style.width = Math.min(100, dist / 20 * 100).toFixed(0) + "%";
      }
      $("gl-n").textContent = fmt(n, 2) + " g";
      $("gl-sinkturn").textContent = "−" + fmt(sinkTurn, 2) + " m/s";
      $("gl-stall").textContent = "×" + fmt(Math.sqrt(n), 2);
    }
    ["gl-height", "gl-wind", "gl-ld", "gl-weight", "gl-bank"].forEach(id => $(id).addEventListener("input", update));
    document.querySelectorAll("#gl-alt button").forEach(b => b.addEventListener("click", () => {
      alt = +b.dataset.alt;
      document.querySelectorAll("#gl-alt button").forEach(x => x.setAttribute("aria-pressed", x === b ? "true" : "false"));
      update();
    }));
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
