// Kinetic: surfing page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "surfing",
    v1: "Physics: nailed it 🏄",
    b1: "You've got the physics of waves and boards. Skim the chapters for anything you missed, then scroll to “Where to go” for surf schools, contests and instructor courses at your level. Knowing the science is a great start; it isn't the same as reading a real ocean.",
    b2: "You have the basics. Fill the gaps below before your next session, especially rip currents and breaking waves: they're the chapters that keep you safe in the water.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to surf at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, a surf level or a lifesaving qualification, and a high score does not mean you're ready for any particular wave. Learn with an ISA-certified instructor, ideally at a school accredited by the Surfing Federation of India; be able to swim confidently; ask about rips and conditions before you paddle out; and follow lifeguards, flags and local advice."
  };
  const CHAPTERS = {
    "ch-swell":    "Ch 1 · Swell: how waves travel",
    "ch-breaking": "Ch 2 · Shoaling & breaking",
    "ch-board":    "Ch 3 · Buoyancy & board volume",
    "ch-ride":     "Ch 4 · Paddling, catching & riding",
    "ch-rips":     "Ch 5 · Rip currents",
    "ch-energy":   "Ch 6 · Wave energy & impact"
  };
  const QUESTIONS = [
    { ch: "ch-swell",
      q: "A forecast shows swell with an 8-second period. Roughly how long is each wave (crest to crest) out in deep water?",
      o: ["About 10 m", "About 30 m", "About 100 m", "About 1 km"], a: 2,
      e: "Deep-water wavelength L = gT² ÷ 2π ≈ 1.56 × T² metres. For T = 8 s: 1.56 × 64 ≈ 100 m. Longer-period swell has much longer, faster waves." },
    { ch: "ch-swell",
      q: "Why do surfers get excited about long-period swell (say 12 s or more) rather than short-period wind chop?",
      o: ["It carries more energy, travels faster and arrives as cleaner, more organised waves", "It's always smaller and safer", "It only happens at night", "It doesn't break"], a: 0,
      e: "Long-period swell has travelled from distant storms, sorting itself into regular sets. For the same height it carries more power (power ∝ H² × T), so it breaks with more push. More push also means more risk for beginners." },
    { ch: "ch-swell",
      q: "In deep water, swell energy travels at the 'group speed'. How does that compare with the speed of individual wave crests?",
      o: ["It's twice as fast", "It's about half as fast", "It's the same", "It's ten times slower"], a: 1,
      e: "In deep water the group speed is half the crest speed. For an 8 s swell, crests move at about 12.5 m/s but the energy travels at about 6.2 m/s (22 km/h): a 1,000 km journey takes about 44 hours." },
    { ch: "ch-breaking",
      q: "As a wave moves into shallow water, its speed is about √(g × depth). What happens as the water gets shallower?",
      o: ["The wave speeds up and gets shorter", "Nothing changes", "The wave turns around", "The wave slows down, gets shorter and grows taller until it breaks"], a: 3,
      e: "Slowing down squeezes the wave's energy into a shorter, taller shape (shoaling). When the height becomes too large for the depth, the crest outruns the base and the wave breaks." },
    { ch: "ch-breaking",
      q: "A common rule of thumb says a wave breaks when its height is about 0.78 × the water depth. Roughly how deep is the water where a 1 m wave breaks?",
      o: ["0.3 m", "About 1.3 m", "About 5 m", "About 10 m"], a: 1,
      e: "Depth ≈ H ÷ 0.78 = 1 ÷ 0.78 ≈ 1.3 m. That's why the impact zone can be shallow: wipe out head-first and you may hit the bottom. Fall flat, and cover your head when you come up." },
    { ch: "ch-board",
      q: "A surfboard has a volume of 80 litres. Roughly how much weight could it hold up if pushed completely under seawater?",
      o: ["About 82 kg", "About 8 kg", "About 800 kg", "About 0.8 kg"], a: 0,
      e: "Archimedes: the upward force equals the weight of water displaced. 80 L of seawater (≈ 1.025 kg per litre) weighs about 82 kg. In practice you want plenty of floatation left over, so the board sits high and paddles fast." },
    { ch: "ch-board",
      q: "Why do surf schools start beginners on big, thick foam ('soft-top') boards?",
      o: ["They look better in photos", "They're faster on big waves", "Extra volume and width give stability and float, making paddling and standing up easier, and soft decks hurt less in a collision", "They're the only boards allowed"], a: 2,
      e: "More volume means you float higher and paddle faster with less effort; a wider board is more stable when you pop up. The soft deck and fins also reduce injuries when you and the board collide." },
    { ch: "ch-ride",
      q: "To catch an unbroken wave, what do you need to do?",
      o: ["Stand up before the wave arrives", "Wait until the wave has passed", "Swim underneath it", "Paddle hard enough that you're moving with the wave as it lifts you, so gravity can take over"], a: 3,
      e: "The wave lifts the back of the board and tilts you down its face. If you're already moving, gravity pulls you down the slope and you start planing. Too slow, and the wave passes under you." },
    { ch: "ch-ride",
      q: "Dropping 1.5 m down a wave face, ignoring friction, about what speed could you gain?",
      o: ["About 5.4 m/s (≈ 20 km/h)", "About 1 m/s", "About 15 m/s", "About 50 m/s"], a: 0,
      e: "Energy conservation: v = √(2gh) = √(2 × 9.81 × 1.5) ≈ 5.4 m/s. That speed is what you then use for turns along the face." },
    { ch: "ch-rips",
      q: "You're being pulled out to sea in a rip current. What's the safest thing to do?",
      o: ["Swim hard straight back to the beach", "Stay calm, keep hold of your board if you have one, and swim or paddle parallel to the shore until you're out of the current, then head in at an angle", "Dive to the bottom", "Take off your leash and let the board go"], a: 1,
      e: "Rips are usually narrow channels. Fighting one head-on exhausts even strong swimmers. Go sideways out of the channel, signal for help if you need it, and come back in where waves are breaking." },
    { ch: "ch-rips",
      q: "According to the US National Weather Service, channel rip currents typically flow at 1–2 feet per second, but how fast can they reach?",
      o: ["About 1 foot per second", "Never more than walking pace", "Up to about 8 feet per second (≈ 2.4 m/s)", "Over 50 feet per second"], a: 2,
      e: "Up to 8 ft/s, about 2.4 m/s: faster than an Olympic swimmer, as NOAA puts it. Even a typical 0.5 m/s rip is hard to stand against at waist depth." },
    { ch: "ch-rips",
      q: "Where do rip currents tend to form?",
      o: ["Where water brought in by breaking waves flows back out through gaps in sandbars or along piers, groynes and rocks", "Only in rivers", "Only far offshore", "Only during a full moon"], a: 0,
      e: "Breaking waves push water towards the beach; it has to get back out somewhere. It funnels through deeper channels between sandbars or along structures. A dark, calmer-looking gap in the breaking waves is often a rip." },
    { ch: "ch-energy",
      q: "Wave energy is proportional to height squared. A 2 m wave carries how much energy compared with a 1 m wave (same period)?",
      o: ["The same", "Twice as much", "Eight times as much", "Four times as much"], a: 3,
      e: "E = ⅛ ρ g H² per square metre of sea. Doubling H gives 2² = 4 times the energy. That's why waves just a little bigger than you're used to can feel far more powerful." },
    { ch: "ch-energy",
      q: "Why do surf schools insist on a leash and on keeping your board away from other people?",
      o: ["Leashes make you faster", "A loose board pushed by whitewater becomes a fast, heavy projectile that can injure you or others", "It's only a fashion choice", "Boards sink without leashes"], a: 1,
      e: "A board moving at whitewater speeds carries a lot of momentum. The leash keeps it near you (and stops it hitting swimmers), and you learn to cover your head and keep the board between you and the wave, never between you and other people." },
    { ch: "ch-energy",
      q: "Roughly how much power does a 1 m, 8-second swell carry for every metre of wave crest, using P ≈ ρg²H²T ÷ 64π?",
      o: ["About 4 W", "About 40 W", "About 4 kW", "About 4 MW"], a: 2,
      e: "1025 × 9.81² × 1² × 8 ÷ (64π) ≈ 3,900 W per metre of crest, about 4 kW. A 2 m, 12-second swell carries about 24 kW per metre: six times more." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- WAVE LAB ----------
  // Linear (Airy) wave theory, deep water: L = gT²/2π, c = gT/2π, group speed c/2.
  // Breaking: H ≈ 0.78 d (rule of thumb); speed at breaking ≈ √(g d). Power per metre of crest P = ρ g² H² T / 64π (ρ = 1025 kg/m³).
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("sf-T")) return;
    const g = 9.81, rho = 1025;
    let dist = 1000;
    function update() {
      const T = +$("sf-T").value, H = +$("sf-H").value;
      $("sf-T-o").textContent = T + " s";
      $("sf-H-o").textContent = H.toFixed(1) + " m";
      const L = g * T * T / (2 * Math.PI), c = g * T / (2 * Math.PI), cg = c / 2;
      $("sf-L").textContent = Math.round(L) + " m";
      $("sf-c").textContent = c.toFixed(1) + " m/s";
      $("sf-cg").textContent = (cg * 3.6).toFixed(1) + " km/h";
      $("sf-eta").textContent = (dist * 1000 / cg / 3600).toFixed(1) + " h";
      $("sf-eta-s").textContent = "Ch 1 · " + dist.toLocaleString("en-IN") + " km at group speed";
      const db = H / 0.78;
      $("sf-db").textContent = db.toFixed(2) + " m";
      $("sf-cb").textContent = Math.sqrt(g * db).toFixed(1) + " m/s";
      const P = rho * g * g * H * H * T / (64 * Math.PI);
      $("sf-P").textContent = (P / 1000).toFixed(1) + " kW/m";
      $("sf-E").textContent = (H * H).toFixed(2) + " ×";
      $("sf-bar").style.width = Math.min(100, P / 30000 * 100).toFixed(0) + "%";
    }
    ["sf-T", "sf-H"].forEach(id => $(id).addEventListener("input", update));
    document.querySelectorAll("#sf-dist button").forEach(b => b.addEventListener("click", () => {
      dist = +b.dataset.km;
      document.querySelectorAll("#sf-dist button").forEach(x => x.setAttribute("aria-pressed", x === b ? "true" : "false"));
      update();
    }));
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
