// Kinetic: archery page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "archery",
    v1: "Physics: nailed it 🏹",
    b1: "You've got the physics of the bow and arrow. Skim the chapters for anything you missed, then scroll to “Where to shoot” for coaching, competitions and academies at your level. Knowing the science is a great start; it isn't the same as form, consistency or range discipline.",
    b2: "You have the basics. Fill the gaps below before your next session, especially aiming and range safety: they're the chapters that tighten your groups and keep everyone safe.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to shoot at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, a coaching assessment or a judgement of your readiness to compete. Shoot only at a supervised range, follow the range officer's commands, never draw a bow with anyone in front of the shooting line, and learn with a qualified coach on equipment suited to you."
  };
  const CHAPTERS = {
    "ch-bow":    "Ch 1 · How a bow stores energy",
    "ch-flight": "Ch 2 · Arrow flight & gravity",
    "ch-spine":  "Ch 3 · Spine, the archer's paradox & fletching",
    "ch-aim":    "Ch 4 · Aiming, angles & scoring",
    "ch-body":   "Ch 5 · Holding, breathing & let-off",
    "ch-wind":   "Ch 6 · Wind, drag & range safety"
  };
  const QUESTIONS = [
    { ch: "ch-bow",
      q: "Where does the energy that launches an arrow come from?",
      o: ["The arrow's own weight", "Your draw bends the limbs, which store it as elastic energy like a spring and give it back to the string", "Heat in the bowstring", "Gravity pulling the arrow forward"], a: 1,
      e: "Drawing the bow does work on the limbs: force × distance. The bent limbs store that as elastic energy, and on release they snap back, driving the string and the arrow. Some energy stays in the limbs and string as vibration and noise." },
    { ch: "ch-bow",
      q: "A bow's draw weight is 40 lb. About what force is that at full draw?",
      o: ["About 178 N", "About 40 N", "About 18 N", "About 400 N"], a: 0,
      e: "1 lb-force ≈ 4.45 N, so 40 lb ≈ 178 N: like holding an 18 kg bag on three fingers. Beginners usually start on much lighter bows." },
    { ch: "ch-bow",
      q: "Shooting the same bow, you switch from a 20 g arrow to a 25 g arrow. What happens?",
      o: ["The arrow flies faster", "Exactly the same speed", "The arrow flies slower, carrying roughly the same energy", "The arrow carries no energy"], a: 2,
      e: "The bow gives the arrow roughly the same energy either way (½ m v²). A heavier arrow therefore flies slower: in our Arrow Lab, about 51 m/s instead of 57 m/s. Heavier arrows are steadier in wind but drop more." },
    { ch: "ch-flight",
      q: "An arrow leaves the bow at about 57 m/s. Ignoring drag, how long does it take to reach a target at 70 m?",
      o: ["About 0.12 s", "About 12 s", "About 0.5 s", "About 1.2 s"], a: 3,
      e: "t = distance ÷ speed = 70 ÷ 57 ≈ 1.23 s. Real arrows slow down a little from air drag, so the true flight is slightly longer." },
    { ch: "ch-flight",
      q: "If that arrow were launched perfectly level, about how far would gravity pull it down by 70 m?",
      o: ["About 7 m", "About 7 cm", "About 70 cm", "Not at all"], a: 0,
      e: "Drop = ½ g t² = ½ × 9.81 × 1.23² ≈ 7.4 m. That's why archers aim with the arrow pointing upward, about 6° here, so it arcs down onto the target." },
    { ch: "ch-flight",
      q: "Why does your sight need a different setting for 30 m and 70 m?",
      o: ["Because the wind is different", "Because the arrows are different", "The drop grows with flight time squared, so longer distances need a bigger launch angle", "Because the target is smaller at 70 m"], a: 2,
      e: "Drop goes with t², and t grows with distance. In our lab, the drop if shot level is about 1.4 m at 30 m but 7.4 m at 70 m. Moving the sight down raises the bow arm and the launch angle." },
    { ch: "ch-spine",
      q: "What is the 'archer's paradox'?",
      o: ["Arrows fly straight through the riser", "The arrow flexes and snakes around the bow as it leaves, yet still flies true towards the target", "Arrows fly further when shot more slowly", "Heavier bows shoot slower"], a: 1,
      e: "The string pushes the back of the arrow while the front is beside the riser, so the shaft bends and oscillates as it clears the bow. An arrow with the right stiffness (spine) for the bow recovers and flies straight." },
    { ch: "ch-spine",
      q: "Why do arrows have fletching (vanes or feathers) at the back?",
      o: ["Decoration only", "To make arrows heavier at the front", "To spin the target", "Drag at the back creates a restoring torque that keeps the point facing forward"], a: 3,
      e: "Like the feathers on a dart, fletching puts the centre of drag behind the centre of mass. If the arrow yaws, the extra drag at the tail swings it back in line. Angled vanes also spin it, averaging out small flaws." },
    { ch: "ch-aim",
      q: "The recurve 10-ring is 12.2 cm across, shot from 70 m. About what angle does it cover from the shooting line?",
      o: ["About 0.1°", "About 1°", "About 10°", "About 0.001°"], a: 0,
      e: "Angle ≈ 0.122 ÷ 70 ≈ 0.00174 rad ≈ 0.1°. To land in the 10 from the middle, your arrow's direction has to be within about ±0.05°." },
    { ch: "ch-aim",
      q: "On the World Archery five-colour target, which rings score 10 and 9?",
      o: ["The white rings", "The yellow (gold) rings", "The blue rings", "The red rings"], a: 1,
      e: "Yellow scores 10 and 9, red 8 and 7, blue 6 and 5, black 4 and 3, white 2 and 1; a miss scores 0. The recurve face at 70 m is 122 cm across." },
    { ch: "ch-aim",
      q: "Your sight pin is 0.8 m from your eye. If your aim drifts so the pin moves 1 mm off centre, roughly how far does the arrow land off centre at 70 m?",
      o: ["About 0.9 mm", "About 90 cm", "About 9 cm", "About 9 m"], a: 2,
      e: "Similar triangles: 1 mm × (70 ÷ 0.8) ≈ 88 mm ≈ 9 cm. That's most of the 12.2 cm 10-ring: a tiny wobble at the bow becomes a big miss at the target." },
    { ch: "ch-body",
      q: "A 60 lb compound bow has 80% let-off. Roughly what do you hold at full draw?",
      o: ["About 12 lb (about 53 N)", "The full 60 lb", "About 48 lb", "Nothing at all"], a: 0,
      e: "Cams reduce the holding weight at full draw: 20% of 60 lb = 12 lb ≈ 53 N. A recurve has no let-off, so its full draw weight is what you hold while aiming." },
    { ch: "ch-body",
      q: "Why do archers aim and release during a pause in breathing?",
      o: ["Breathing makes the arrow heavier", "It's only a tradition", "Chest and shoulder movement shifts the bow arm; a still hold means a smaller aiming wobble", "Holding your breath makes the bow stronger"], a: 2,
      e: "From Ch 4, a millimetre at the bow is centimetres at the target. A settled breath, then a steady hold and a clean release, keeps that wobble small. Holding too long makes you shake, so let down and start again." },
    { ch: "ch-wind",
      q: "Why must nobody be forward of the shooting line while anyone is shooting?",
      o: ["It's just tradition", "An arrow carries about 30 J and can fly far past the target, so the area downrange must be clear", "To keep the targets clean", "So the judges can see"], a: 1,
      e: "A 20 g arrow at 57 m/s carries about 33 J, enough to cause serious injury. Ranges use a shooting line, a safety zone behind the targets and whistle commands: you only go forward to collect arrows when everyone has stopped." },
    { ch: "ch-wind",
      q: "Which arrow is pushed sideways most by a crosswind?",
      o: ["A heavy, fast arrow", "All arrows equally", "None: arrows ignore wind", "A light, slower arrow that spends longer in the air"], a: 3,
      e: "Wind pushes on the arrow for its whole flight. A light arrow is accelerated more by the same push, and a slow arrow is exposed for longer, so both drift further. Archers 'aim off' into the wind." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- ARROW LAB ----------
  // Stored energy ≈ ½ × draw force × power stroke (linear-spring approximation; power stroke = draw length − 8.75 in brace height).
  // 75% of it goes into the arrow (illustrative). Flight ignores air drag: t = d/v, drop if shot level = ½gt², launch angle = ½·asin(gd/v²).
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("ar-w")) return;
    const g = 9.81, eff = 0.75, brace = 8.75;
    let d = 70;
    function update() {
      const lb = +$("ar-w").value, dl = +$("ar-dl").value, m = +$("ar-m").value / 1000;
      $("ar-w-o").textContent = lb + " lb";
      $("ar-dl-o").textContent = dl + " in";
      $("ar-m-o").textContent = Math.round(m * 1000) + " g";
      const F = lb * 4.44822, ps = (dl - brace) * 0.0254, E = 0.5 * F * ps, ke = eff * E, v = Math.sqrt(2 * ke / m);
      $("ar-e").textContent = E.toFixed(1) + " J";
      $("ar-v").textContent = v.toFixed(1) + " m/s";
      $("ar-ke").textContent = ke.toFixed(1) + " J";
      const t = d / v;
      $("ar-t").textContent = t.toFixed(2) + " s";
      $("ar-drop").textContent = (0.5 * g * t * t).toFixed(2) + " m";
      const s = g * d / (v * v);
      $("ar-ang").textContent = s <= 1 ? (0.5 * Math.asin(s) * 180 / Math.PI).toFixed(1) + "°" : "out of range";
      $("ar-bar").style.width = Math.min(100, v / 80 * 100).toFixed(0) + "%";
    }
    ["ar-w", "ar-dl", "ar-m"].forEach(id => $(id).addEventListener("input", update));
    document.querySelectorAll("#ar-d button").forEach(b => b.addEventListener("click", () => {
      d = +b.dataset.d;
      document.querySelectorAll("#ar-d button").forEach(x => x.setAttribute("aria-pressed", x === b ? "true" : "false"));
      update();
    }));
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
