// Kinetic: horse-riding page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "horse-riding",
    v1: "Physics: nailed it 🐎",
    b1: "You've got the physics of balance, gaits, the bounce and the jump. Skim the chapters for anything you missed, then scroll to “Where to ride” for your next step. Knowing the science helps, but riding is learned in the saddle, with a coach and a well-schooled horse.",
    b2: "You have the basics. Fill the gaps below before your next lesson, especially balance and the bounce: they're the chapters that explain what your coach keeps telling you about your seat.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to ride at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification: it is not a riding level, a BHS Stage or an EFI qualification. Learn with a qualified coach at an established riding school, wear a properly fastened riding helmet every time you ride, and follow your coach's decisions about which horse, pace and fence suit you."
  };
  const CHAPTERS = {
    "ch-balance": "Ch 1 · Your centre of mass over a moving base",
    "ch-gaits":   "Ch 2 · Gaits & footfall patterns",
    "ch-shock":   "Ch 3 · Shock absorption, posture & following the motion",
    "ch-jump":    "Ch 4 · The physics of jumping",
    "ch-aids":    "Ch 5 · Aids, communication & horse senses",
    "ch-falls":   "Ch 6 · Falls & safety: helmets and body protectors"
  };
  const QUESTIONS = [
    { ch: "ch-balance",
      q: "What must stay above your base of support for you to sit in balance without gripping?",
      o: ["Your centre of mass", "Your hands", "The horse's head", "Your heels only"], a: 0,
      e: "Balance means your centre of mass is over your base (seat bones, thighs and stirrups). On a horse that base moves, so you keep adjusting." },
    { ch: "ch-balance",
      q: "You canter at 5 m/s on a circle of radius 10 m. About how far should you lean into the turn?",
      o: ["0°", "About 45°", "About 14°", "About 2°"], a: 2,
      e: "tan φ = v² ÷ (r g) = 25 ÷ 98.1 ≈ 0.255, so φ ≈ 14.3°." },
    { ch: "ch-balance",
      q: "The horse suddenly speeds up underneath you. Which way does your body tend to go if you don't adjust?",
      o: ["Forward", "Backward, because the base accelerates out from under you", "Sideways", "Nowhere: you move with the horse automatically"], a: 1,
      e: "Your body tends to keep its speed (inertia) while the saddle accelerates, so you're left behind. Leaning forward by tan φ = a ÷ g keeps you balanced." },
    { ch: "ch-gaits",
      q: "How many beats per stride does the trot have?",
      o: ["Four", "Three", "One", "Two: diagonal pairs land together"], a: 3,
      e: "LH lands with RF, then RH with LF: two beats, with a possible moment in the air between them." },
    { ch: "ch-gaits",
      q: "On the right lead, which is the footfall order of the canter?",
      o: ["LF, RF, LH, RH", "LH, then RH and LF together, then RF, then a moment in the air", "All four feet together", "LH, LF, RH, RF evenly spaced"], a: 1,
      e: "Three beats: the outside hind, the diagonal pair, then the leading foreleg (RF), followed by suspension." },
    { ch: "ch-gaits",
      q: "In the 2007 study of Icelandic horses, canter and gallop speeds overlapped. So what defines a gait?",
      o: ["Its footfall pattern", "Its speed", "The rider's position", "The horse's breed"], a: 0,
      e: "Gaits are defined by the order and timing of footfalls. In gallop the diagonal pair of the canter splits, giving four beats." },
    { ch: "ch-shock",
      q: "In a model where the saddle moves up and down ±5 cm at 2.4 bounces per second, its peak downward acceleration is about 1.16 g. What happens to a stiff rider?",
      o: ["Nothing", "They sink deeper into the saddle", "They feel lighter but never move", "The saddle drops away faster than gravity can pull them after it, so they lift off and bounce"], a: 3,
      e: "If the saddle's downward acceleration exceeds g, a rigid rider separates from it. Supple joints let the body follow instead." },
    { ch: "ch-shock",
      q: "Why does rising trot feel smoother than sitting trot?",
      o: ["The horse slows down", "The saddle stops moving", "The rider rises on one beat and sits on the next, meeting only every other bounce", "It removes gravity"], a: 2,
      e: "Trot has two bounces per stride. Rising on one and sitting on the other halves the impacts the rider absorbs." },
    { ch: "ch-jump",
      q: "Once all four feet have left the ground over a fence, what decides the path of the horse's centre of mass?",
      o: ["The rider's hands", "Only the speed and angle at take-off (plus gravity)", "How high the horse tucks its legs", "The rider leaning back"], a: 1,
      e: "In the air, gravity is the only big outside force, so the centre of mass follows a parabola set at take-off. Tucking changes the body's shape, not the arc." },
    { ch: "ch-jump",
      q: "A horse takes off at 6 m/s at 30°. About how much does its centre of mass rise?",
      o: ["About 4.6 m", "About 1.8 m", "About 0.46 m", "About 0.05 m"], a: 2,
      e: "v sin θ = 3.0 m/s; (3.0)² ÷ (2 × 9.81) ≈ 0.46 m." },
    { ch: "ch-jump",
      q: "For the top of the arc to be over the fence, where should the horse take off?",
      o: ["Half the flight distance before the fence", "Right at the base of the fence", "As far away as possible", "It doesn't matter"], a: 0,
      e: "A parabola peaks halfway. At 6 m/s and 30° the flight is about 3.18 m, so take-off is about 1.59 m before the fence." },
    { ch: "ch-aids",
      q: "According to the ISES training principles, when should rein or leg pressure be released?",
      o: ["After a fixed count of ten", "Never", "Only when the lesson ends", "At the onset of the correct response"], a: 3,
      e: "Releasing the pressure as the horse starts to respond tells it that was the right answer. Light signals before pressure teach it to answer lightly." },
    { ch: "ch-aids",
      q: "Where are a horse's small blind spots, according to UC Davis?",
      o: ["Directly below the nose, in front of the forehead and directly behind", "To the left and right", "Only above the horse", "Horses have no blind spots"], a: 0,
      e: "The panoramic view reaches about 350°, but there are small blind spots below the nose, in front of the forehead and directly behind. Approach where the horse can see you." },
    { ch: "ch-falls",
      q: "Ignoring forward speed, about how fast is a rider's head moving when it hits the ground after falling from 2.4 m?",
      o: ["About 2.4 m/s", "About 6.9 m/s (25 km/h)", "About 24 m/s", "About 0.7 m/s"], a: 1,
      e: "v = √(2 g h) = √(2 × 9.81 × 2.4) ≈ 6.9 m/s, about 25 km/h." },
    { ch: "ch-falls",
      q: "What does the EFI require of anyone jumping a horse?",
      o: ["A body protector only", "Nothing specific", "Gloves", "A properly fastened helmet with a three-point retention harness"], a: 3,
      e: "The EFI's Technical Guidelines (Article 209) make it compulsory; protective headgear is also mandatory while riding on the show grounds." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- GAIT & JUMP LAB ----------
  // Gaits: footfall orders from Robilliard et al. 2007 (J Exp Biol 210:187), right lead for canter and gallop; dot positions are schematic.
  // Jump: horse's centre of mass as a drag-free projectile from 1.25 m at take-off; the tucked body's lowest point passes 0.6 m below it.
  // rise = (v sin θ)² ÷ 2g, time = 2 v sin θ ÷ g, flight = v² sin 2θ ÷ g, take-off distance = flight ÷ 2, clearance = 1.25 + rise − (h + 0.6).
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("hr-h")) return;
    const G = 9.81, Y0 = 1.25, TUCK = 0.6;
    const GAITS = {
      walk:   { beats: "4 beats", seq: "LH → LF → RH → RF", susp: "None", feet: "2 to 4", dots: { LH: [0], LF: [25], RH: [50], RF: [75] }, air: null },
      trot:   { beats: "2 beats", seq: "LH + RF → RH + LF", susp: "Possible, between the diagonal pairs", feet: "0 to 2", dots: { LH: [5], RF: [5], RH: [55], LF: [55] }, air: [[38, 50], [88, 100]] },
      canter: { beats: "3 beats", seq: "LH → RH + LF → RF", susp: "Yes, after the leading foreleg (RF)", feet: "0 to 3", dots: { LH: [5], RH: [30], LF: [30], RF: [55] }, air: [[78, 100]] },
      gallop: { beats: "4 beats", seq: "LH → RH → LF → RF", susp: "Yes, after the leading foreleg (RF)", feet: "0 to 3", dots: { LH: [5], RH: [20], LF: [42], RF: [57] }, air: [[80, 100]] }
    };
    function gait(g) {
      const d = GAITS[g];
      document.querySelectorAll("#hr-gait button").forEach(b => b.setAttribute("aria-pressed", b.dataset.g === g ? "true" : "false"));
      $("hr-beats").textContent = d.beats; $("hr-seq").textContent = d.seq; $("hr-susp").textContent = d.susp; $("hr-feet").textContent = d.feet;
      $("hr-strip").innerHTML = ["LH", "LF", "RH", "RF"].map(leg =>
        '<div class="lane"><span>' + leg + '</span><div class="track">' +
        (d.air || []).map(a => '<span class="air" style="left:' + a[0] + '%;width:' + (a[1] - a[0]) + '%"></span>').join("") +
        (d.dots[leg] || []).map(x => '<span class="dot" style="left:calc(6px + ' + x + '% * 0.9)"></span>').join("") +
        '</div></div>').join("");
    }
    function jump() {
      const h = +$("hr-h").value, v = +$("hr-v").value, a = +$("hr-a").value, r = a * Math.PI / 180;
      $("hr-h-o").textContent = h.toFixed(2) + " m";
      $("hr-v-o").textContent = v.toFixed(1) + " m/s (" + Math.round(v * 60) + " m/min)";
      $("hr-a-o").textContent = a + "°";
      const vy = v * Math.sin(r), rise = vy * vy / (2 * G), t = 2 * vy / G, d = v * v * Math.sin(2 * r) / G;
      const clear = Math.round((Y0 + rise - (h + TUCK)) * 100);
      $("hr-rise").textContent = rise.toFixed(2) + " m";
      $("hr-time").textContent = t.toFixed(2) + " s";
      $("hr-dist").textContent = d.toFixed(2) + " m";
      $("hr-take").textContent = (d / 2).toFixed(2) + " m";
      $("hr-clear").textContent = clear >= 0 ? "clears by " + clear + " cm" : "hits the rail (" + (-clear) + " cm short)";
      $("hr-land").textContent = vy.toFixed(1) + " m/s";
    }
    document.querySelectorAll("#hr-gait button").forEach(b => b.addEventListener("click", () => gait(b.dataset.g)));
    ["hr-h", "hr-v", "hr-a"].forEach(id => $(id).addEventListener("input", jump));
    gait("walk"); jump();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
