// Kinetic: bungee-zipline page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "bungee-zipline",
    v1: "Physics: nailed it 🪢",
    b1: "You've got the physics of the fall, the cord and the cable. Skim the chapters for anything you missed, then scroll to “Where to jump” for your next step. Knowing the science is a great start; the safety of every jump or ride still rests on the operator's crew, equipment and standards.",
    b2: "You have the basics. Fill the gaps below before your first jump or zip, especially the cord and the brakes: they're the chapters that explain why the crew weighs you and checks every link.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to jump or zip at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification: there is no recreational certification for bungee or zip-line participants. Jump or ride only with an operator that follows recognised standards and has trained jump masters or guides, let them check your weight and harness, declare any medical condition, and follow the crew's briefing and decisions."
  };
  const CHAPTERS = {
    "ch-fall":   "Ch 1 · Free fall: the first few seconds",
    "ch-cord":   "Ch 2 · Hooke's law & elastic energy",
    "ch-gforce": "Ch 3 · Peak g, rebound & damping",
    "ch-length": "Ch 4 · Cord length vs jump height",
    "ch-zip":    "Ch 5 · Zip lines: slope, sag, friction & drag",
    "ch-brake":  "Ch 6 · Brakes, trolleys & harness load paths"
  };
  const QUESTIONS = [
    { ch: "ch-fall",
      q: "A bungee cord is 20 m long. Ignoring air drag, about how long do you free-fall before it starts to stretch?",
      o: ["About 2 s", "About 20 s", "About 0.2 s", "About 9.8 s"], a: 0,
      e: "t = √(2L/g) = √(2 × 20 ÷ 9.81) ≈ 2.02 s." },
    { ch: "ch-fall",
      q: "How fast are you falling (no drag) when that 20 m cord goes tight?",
      o: ["About 20 km/h", "About 71 km/h", "About 200 km/h", "About 7 km/h"], a: 1,
      e: "v = √(2gL) = √(2 × 9.81 × 20) ≈ 19.8 m/s, about 71 km/h." },
    { ch: "ch-cord",
      q: "An ideal cord stores elastic energy E = ½ k x². If it stretches twice as far, the stored energy…",
      o: ["Doubles", "Halves", "Stays the same", "Becomes four times as big"], a: 3,
      e: "Energy grows with the square of the stretch: (2x)² = 4x², so four times the energy." },
    { ch: "ch-cord",
      q: "At the lowest point of a jump you've stopped for an instant. Which energy balance gives the maximum stretch x of a cord of length L?",
      o: ["m g L = k x", "½ m v² = k x", "m g (L + x) = ½ k x²", "m g = ½ k x"], a: 2,
      e: "All the height you lost, L + x, has become stretch energy: m g (L + x) = ½ k x². For 70 kg, 20 m and k = 100 N/m, x ≈ 24.8 m." },
    { ch: "ch-cord",
      q: "Real bungee cords are bundles of rubber strands. How do they differ from an ideal Hooke's-law spring?",
      o: ["They don't stretch", "They get stronger with every jump", "They obey Hooke's law exactly", "Their stiffness changes as they stretch, and they turn some energy into heat each time"], a: 3,
      e: "Rubber is non-linear and loses energy as heat on each stretch. That's why India's guidelines ask operators to record each cord's shelf life, store it away from UV light and inspect it regularly." },
    { ch: "ch-gforce",
      q: "A 70 kg jumper on a 20 m cord with k = 100 N/m stretches it 24.8 m. About how hard does the cord pull at the bottom, compared with their weight?",
      o: ["About 1 ×", "About 3.6 ×", "About 10 ×", "About 0.5 ×"], a: 1,
      e: "k x = 100 × 24.8 ≈ 2,480 N; their weight is 70 × 9.81 ≈ 687 N; 2,480 ÷ 687 ≈ 3.6." },
    { ch: "ch-gforce",
      q: "When are you moving fastest during a bungee jump?",
      o: ["Just as the cord goes tight", "At the very bottom", "A few metres after the cord goes tight, where its pull equals your weight", "On the platform"], a: 2,
      e: "You keep speeding up until the pull k x equals m g: 6.9 m into the stretch in our example, at about 77 km/h compared with 71 km/h when the cord went tight." },
    { ch: "ch-gforce",
      q: "Why does each rebound rise less high than the one before?",
      o: ["Gravity gets weaker", "The cord gets longer", "You get heavier", "The rubber and the air turn some energy into heat (damping)"], a: 3,
      e: "With no losses you'd fly back to the platform. Damping takes a share on every bounce until you hang still where the pull equals your weight." },
    { ch: "ch-length",
      q: "Same cord, same 60 m platform: a 110 kg jumper replaces a 70 kg one. What happens?",
      o: ["They stop at the same point", "They stop higher up", "They stretch the cord further and go about 9 m lower", "Nothing: weight doesn't matter"], a: 2,
      e: "The stretch grows from 24.8 m to 34.2 m, so the room left falls from 15.2 m to 5.8 m. That's why operators weigh every jumper and set weight limits." },
    { ch: "ch-length",
      q: "An operator swaps to a cord of the same rubber that is twice as long. What happens to its stiffness k?",
      o: ["It halves, so the stretch doubles but the peak pull stays the same", "It doubles", "It stays the same", "It becomes zero"], a: 0,
      e: "k = E A ÷ L, so a cord twice as long is half as stiff. The stretch is always the same fraction of the length, and the peak pull doesn't change." },
    { ch: "ch-zip",
      q: "On a zip line, which force drives you along the cable?",
      o: ["Air drag", "The cable's tension", "Friction in the trolley", "The part of gravity along the slope, m g sin θ"], a: 3,
      e: "Gravity along the slope pulls you; trolley friction and air drag hold you back. You reach top speed when they balance." },
    { ch: "ch-zip",
      q: "Why do heavier riders arrive faster on the same zip line?",
      o: ["They have more drag", "Gravity's pull grows with mass but air drag doesn't, so their top speed is higher", "They push off harder", "They don't: everyone arrives at the same speed"], a: 1,
      e: "Top speed grows with √m. At 6° in our model: 53 km/h for 70 kg, 66 km/h for 110 kg. That's one reason zip lines have maximum weights." },
    { ch: "ch-zip",
      q: "A 300 m zip line holds a 100 kg rider at mid-span. If the sag is halved from 9 m to 4.5 m, the cable tension…",
      o: ["Halves", "Stays the same", "Roughly doubles, from about 8 kN to 16 kN", "Falls to zero"], a: 2,
      e: "T ≈ W L ÷ (4 s): a tighter line (smaller sag) needs far more tension to hold the same weight." },
    { ch: "ch-brake",
      q: "According to the European standard EN 15567-1, what must always be in place on a zip line?",
      o: ["A passive braking system", "A rider who brakes by hand", "Nothing, if the line is short", "A second rider"], a: 0,
      e: "A passive brake (working without anyone acting) must always be there, plus a primary brake in the arrival area and an emergency brake where a primary-brake failure could cause serious injury." },
    { ch: "ch-brake",
      q: "Stopping from 14.7 m/s (53 km/h) in 5 m means an average deceleration of about…",
      o: ["0.2 g", "2.2 g", "22 g", "10 g"], a: 1,
      e: "a = v² ÷ (2d) = 14.7² ÷ 10 ≈ 21.7 m/s², about 2.2 g. A longer braking distance means a gentler stop." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- BUNGEE & ZIP LAB ----------
  // Bungee: free fall (no drag) for the cord length L: t = √(2L/g), v = √(2gL). Ideal Hooke's-law cord, energy conserved:
  // m g (L + x) = ½ k x²  →  x = [m g + √((m g)² + 2 k m g L)] ÷ k. Peak pull = k x ÷ (m g). Room left = platform − (L + x).
  // Zip line: straight slope θ, top speed when m g (sin θ − μ cos θ) = ½ ρ CdA v², with μ = 0.01, CdA = 0.5 m², ρ = 1.2 kg/m³ (illustrative).
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("bz-m")) return;
    const G = 9.81, MU = 0.01, CDA = 0.5, RHO = 1.2;
    function update() {
      const m = +$("bz-m").value, L = +$("bz-L").value, k = +$("bz-k").value, H = +$("bz-H").value, th = +$("bz-th").value;
      $("bz-m-o").textContent = m + " kg";
      $("bz-L-o").textContent = L + " m";
      $("bz-k-o").textContent = k + " N/m";
      $("bz-H-o").textContent = H + " m";
      $("bz-th-o").textContent = th + "°";
      const W = m * G, x = (W + Math.sqrt(W * W + 2 * k * W * L)) / k, low = L + x, room = H - low;
      $("bz-t").textContent = Math.sqrt(2 * L / G).toFixed(2) + " s";
      $("bz-v").textContent = Math.round(Math.sqrt(2 * G * L) * 3.6) + " km/h";
      $("bz-x").textContent = x.toFixed(1) + " m";
      $("bz-c").textContent = room > 0 ? room.toFixed(1) + " m" : "none: hits the ground";
      $("bz-g").textContent = (k * x / W).toFixed(1) + " × body weight";
      const r = Math.PI / 180 * th, s = Math.sin(r) - MU * Math.cos(r);
      $("bz-zip").textContent = s > 0 ? Math.round(Math.sqrt(2 * m * G * s / (RHO * CDA)) * 3.6) + " km/h" : "doesn't move";
      $("bz-bar").style.width = Math.min(100, Math.round(100 * low / H)) + "%";
    }
    ["bz-m", "bz-L", "bz-k", "bz-H", "bz-th"].forEach(id => $(id).addEventListener("input", update));
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
