// Kinetic: shooting page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "shooting",
    v1: "Physics: nailed it 🎯",
    b1: "You've got the physics of the shot. Skim the chapters for anything you missed, then scroll to “Where to train” for supervised ranges, competitions and courses at your level. Knowing the science is a great start; it isn't the same as a steady hold, a clean trigger or range discipline.",
    b2: "You have the basics. Fill the gaps below before your next session, especially angles and range safety: they're the chapters that tighten your groups and keep everyone safe.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to train at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, a coaching assessment or legal advice. Shoot only at a supervised range, follow the range officer's commands, keep every gun pointed downrange with its safety flag in when not shooting, and learn with a qualified coach. Licensing questions go to your club, your state rifle association or the licensing authority."
  };
  const CHAPTERS = {
    "ch-flight":  "Ch 1 · Pellet flight & gravity",
    "ch-recoil":  "Ch 2 · Recoil & momentum",
    "ch-aim":     "Ch 3 · Angles, wobble & the 10-ring",
    "ch-breath":  "Ch 4 · Breathing, heartbeat & the hold",
    "ch-trigger": "Ch 5 · Trigger control & follow-through",
    "ch-safety":  "Ch 6 · Range safety, rules & the law"
  };
  const QUESTIONS = [
    { ch: "ch-flight",
      q: "A pellet leaves the barrel at 175 m/s. Ignoring drag, how long does it take to reach a target 10 m away?",
      o: ["About 0.6 s", "About 57 milliseconds", "About 5.7 s", "About 0.6 milliseconds"], a: 1,
      e: "t = distance ÷ speed = 10 ÷ 175 ≈ 0.057 s, or 57 ms: about a third of a blink. Drag slows the pellet a little, so the real time is slightly longer." },
    { ch: "ch-flight",
      q: "During that 57 ms flight, about how far does gravity pull the pellet down?",
      o: ["About 16 mm", "About 16 cm", "About 1.6 m", "Not at all: pellets fly perfectly straight"], a: 0,
      e: "Drop = ½ g t² = ½ × 9.81 × 0.057² ≈ 0.016 m = 16 mm. Everything falls at the same rate, however fast it moves sideways." },
    { ch: "ch-flight",
      q: "So why don't shooters see that 16 mm drop on the target?",
      o: ["Air pushes pellets upward", "Pellets are too light to fall", "The sights are set (zeroed) for the target distance, so the drop is built into the aim", "Gravity doesn't act indoors"], a: 2,
      e: "The sights are adjusted so that, at the target distance, the pellet's curved path meets the point of aim. The drop is still there; the sight setting has already allowed for it." },
    { ch: "ch-recoil",
      q: "Why does a gun move backward when it fires?",
      o: ["Air resistance pushes it", "Gravity pulls it back", "The target pushes back", "Momentum is conserved: the pellet gets forward momentum, so the gun gets the same amount backward"], a: 3,
      e: "Before the shot, total momentum is zero. Afterwards the pellet carries m v forward, so the gun carries M V = m v backward. That's recoil." },
    { ch: "ch-recoil",
      q: "A 0.5 g pellet leaves at 175 m/s from a 5 kg rifle. Roughly how fast does the rifle recoil?",
      o: ["About 1.75 cm/s", "About 17.5 m/s", "About 1.75 m/s", "It doesn't move at all"], a: 0,
      e: "V = m v ÷ M = 0.0005 × 175 ÷ 5 = 0.0175 m/s ≈ 1.75 cm/s. Its recoil energy is 10,000 times smaller than the pellet's, the same ratio as the masses." },
    { ch: "ch-recoil",
      q: "The same pellet is fired from a 1 kg pistol instead of the 5 kg rifle. What happens to the recoil speed?",
      o: ["It's the same", "It's five times slower", "It's about five times faster: the same momentum is shared with a lighter gun", "There's no recoil from a pistol"], a: 2,
      e: "Same momentum, one-fifth the mass, so five times the speed: about 8.75 cm/s. Heavier guns move less, one reason target rifles are heavy." },
    { ch: "ch-aim",
      q: "On the ISSF 10 m air rifle target, how big is the 10-ring?",
      o: ["About 5 cm", "A 0.5 mm dot", "About 5 mm", "About 1 cm"], a: 1,
      e: "The 10-ring is a white dot 0.5 mm across. Each ring is 5 mm wider than the last, out to 45.5 mm for the 1-ring. The air pistol 10-ring is 11.5 mm." },
    { ch: "ch-aim",
      q: "Your aim wobbles by 0.4 milliradians. About how far off centre does the shot land at 10 m?",
      o: ["About 4 cm", "About 0.4 mm", "About 40 mm", "About 4 mm"], a: 3,
      e: "At 10 m, 1 mrad = 10 mm, so 0.4 mrad = 4 mm. On the rifle target that's a 9; on the bigger pistol target it's still a 10." },
    { ch: "ch-aim",
      q: "Why can a shot whose centre misses the 0.5 mm dot still score a 10?",
      o: ["A shot scores the highest ring any part of its hole touches, and the 4.5 mm pellet hole only needs to touch the dot", "Judges round up", "Electronic targets ignore misses", "It can't: the centre must hit the dot"], a: 0,
      e: "ISSF scoring counts the higher ring if any part of the shot hole touches it. With a 4.5 mm pellet, the centre can be up to 0.25 + 2.25 = 2.5 mm from the middle and still score 10." },
    { ch: "ch-breath",
      q: "Why do shooters take the shot in a natural pause in their breathing?",
      o: ["It makes the pellet faster", "Breathing moves the chest and shoulders, and the gun with them; the pause is the stillest moment", "It's only a tradition", "So they can hear the commands"], a: 1,
      e: "From Ch 3, a tenth of a milliradian is a millimetre at 10 m. Breathing moves the whole upper body, so shooters breathe out, settle into the natural pause and shoot there." },
    { ch: "ch-breath",
      q: "ISSF 10 m air rifle qualification is 60 shots in 75 minutes. What's the average time per shot?",
      o: ["About 7.5 s", "About 15 s", "About 75 s", "About 7.5 minutes"], a: 2,
      e: "75 × 60 ÷ 60 = 75 s per shot on average. If the hold isn't settling, there's time to lower the gun, breathe and start again." },
    { ch: "ch-trigger",
      q: "What does 'follow-through' mean in shooting?",
      o: ["Keeping your position and aim steady through the shot and a moment after, until the pellet has left", "Reloading as fast as possible", "Walking to the target after shooting", "Pulling the trigger harder"], a: 0,
      e: "For a few milliseconds after the trigger breaks, the pellet is still in the barrel. Anything that moves the gun then goes into the shot, so shooters keep the aim and position until well after it's gone." },
    { ch: "ch-trigger",
      q: "A trigger jerk rotates the gun by 0.8 mrad before the pellet leaves. What happens at 10 m?",
      o: ["Nothing", "It moves the shot about 0.8 mm", "It moves the shot about 8 mm: a rifle 10 becomes a 7", "It moves the shot about 80 cm"], a: 2,
      e: "0.8 mrad × 10 m = 8 mm. The rifle 8-ring reaches only 7.5 mm (with the pellet's radius), so the shot scores 7. A smooth press keeps the hold undisturbed." },
    { ch: "ch-safety",
      q: "On an ISSF range, what are safety flags for?",
      o: ["Decoration", "Bright flags inserted in rifles and pistols to show they're unloaded", "To show the wind", "To mark the targets"], a: 1,
      e: "ISSF rules require fluorescent safety flags in rifles and pistols except when shooting is authorised. For air guns the flag runs the full length of the barrel, so anyone can see it's empty." },
    { ch: "ch-safety",
      q: "When may you load a gun on an ISSF range?",
      o: ["Whenever you're ready", "Before walking to the firing line", "While the targets are being changed", "Only on the firing point, pointing downrange, after the range official's LOAD or START command"], a: 3,
      e: "Guns are loaded only on the firing point after LOAD or START, the action is closed only when pointing downrange, and nobody handles guns while anyone is forward of the firing line." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- HOLD & SCORE LAB ----------
  // 10 m event, 0.5 g pellet (illustrative), no drag. Off-centre = wobble (mrad) × 10 m.
  // Ring n radius = r10 + (10 − n) × step (ISSF: rifle 10-ring 0.5 mm, rings +5 mm; pistol 10-ring 11.5 mm, rings +16 mm).
  // A shot scores the highest ring its 4.5 mm hole touches (pellet radius 2.25 mm). Recoil: M V = m v.
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("sh-wob")) return;
    const g = 9.81, m = 0.0005, d = 10, pr = 2.25;
    const T = { rifle: [0.25, 2.5], pistol: [5.75, 8] };
    let ev = "rifle";
    function ring(off) {
      const [r10, st] = T[ev];
      for (let n = 10; n >= 1; n--) if (off <= r10 + (10 - n) * st + pr + 1e-9) return n;
      return 0;
    }
    function update() {
      const w = +$("sh-wob").value, v = +$("sh-v").value, M = +$("sh-gm").value;
      $("sh-wob-o").textContent = w.toFixed(1) + " mrad";
      $("sh-v-o").textContent = v + " m/s";
      $("sh-gm-o").textContent = M.toFixed(1) + " kg";
      const off = w * d, n = ring(off), t = d / v;
      $("sh-off").textContent = off.toFixed(1) + " mm";
      $("sh-ring").textContent = n ? String(n) : "miss";
      $("sh-t").textContent = Math.round(t * 1000) + " ms";
      $("sh-drop").textContent = (0.5 * g * t * t * 1000).toFixed(1) + " mm";
      $("sh-ke").textContent = (0.5 * m * v * v).toFixed(1) + " J";
      $("sh-rv").textContent = (m * v / M * 100).toFixed(2) + " cm/s";
      $("sh-bar").style.width = (n * 10) + "%";
    }
    ["sh-wob", "sh-v", "sh-gm"].forEach(id => $(id).addEventListener("input", update));
    document.querySelectorAll("#sh-ev button").forEach(b => b.addEventListener("click", () => {
      ev = b.dataset.ev;
      document.querySelectorAll("#sh-ev button").forEach(x => x.setAttribute("aria-pressed", x === b ? "true" : "false"));
      update();
    }));
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
