// Kinetic: sailing page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "sailing",
    v1: "Physics: nailed it ⛵",
    b1: "You've got the physics of sailing. Skim the chapters for anything you missed, then scroll to “Where to sail” for courses and clubs at your level. Knowing the science is a great start; it isn't the same as the boat handling, capsize and safety skills an instructor teaches on the water.",
    b2: "You have the basics. Fill the gaps below before your first course, especially apparent wind and heeling: they're the chapters that keep the boat moving and upright.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to sail at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, a sailing course or a substitute for training with a qualified instructor. Always wear a buoyancy aid, check the forecast before you go out, and learn capsize recovery with an instructor before you sail on your own."
  };
  const CHAPTERS = {
    "ch-lift":     "Ch 1 · How a sail makes lift",
    "ch-apparent": "Ch 2 · Apparent wind",
    "ch-points":   "Ch 3 · Points of sail, tacking & gybing",
    "ch-board":    "Ch 4 · Centreboard, keel & sideways slip",
    "ch-heel":     "Ch 5 · Heeling, hiking & capsize",
    "ch-planing":  "Ch 6 · Hull speed, planing & the boats"
  };
  const QUESTIONS = [
    { ch: "ch-lift",
      q: "The wind speed doubles from 6 to 12 knots. Same sail, same angle: what happens to the sail force?",
      o: ["It's about 4 times as big", "It doubles", "It stays the same", "It halves"], a: 0,
      e: "Force grows with the square of the wind speed (F = ½ρV²AC_L): 2² = 4. Our worked example goes from 41 N to 163 N on a 7 m² sail." },
    { ch: "ch-lift",
      q: "Sailing upwind, how does a sail make its force?",
      o: ["The wind simply pushes on the back of the sail", "Like a wing: it turns the airflow, with lower pressure on the curved leeward side", "Air on both sides must meet at the back at the same time", "The mast blocks the wind"], a: 1,
      e: "A sail at a small angle bends the airflow. That needs a pressure difference across it, lower on the leeward side, and that difference is the lift. There's no rule that the two airstreams meet up again." },
    { ch: "ch-lift",
      q: "At 12 knots the air's dynamic pressure (½ρV²) is about 23 Pa. With a lift coefficient of 1.0, what force does a 10 m² sail make?",
      o: ["About 23 N", "About 2.3 N", "About 233 N", "About 2,330 N"], a: 2,
      e: "F = 23.3 Pa × 10 m² × 1.0 ≈ 233 N, roughly the weight of a 24 kg bag." },
    { ch: "ch-apparent",
      q: "True wind 8 knots from directly abeam (90°), boat speed 6 knots. What's the apparent wind speed?",
      o: ["14 kn", "2 kn", "8 kn", "10 kn"], a: 3,
      e: "At 90° the true wind and your headwind are at right angles: √(8² + 6²) = √100 = 10 kn, from about 53° off the bow." },
    { ch: "ch-apparent",
      q: "As a boat speeds up on a beam reach, which way does the apparent wind move?",
      o: ["Forward, towards the bow", "Aft, towards the stern", "It doesn't change", "It swings to the other side"], a: 0,
      e: "Your own headwind adds to the true wind and pulls the apparent wind forward. In the worked example it moves from 90° to 67° at 5 kn. You trim the sails in as you accelerate." },
    { ch: "ch-apparent",
      q: "Why does the wind feel weaker when you turn and sail downwind?",
      o: ["The wind always drops near the shore", "You're moving with the wind, so your boat speed is subtracted from it", "The sail blocks it", "Water slows the wind"], a: 1,
      e: "Downwind, your speed takes away from the true wind; upwind it adds. Same wind, very different feel." },
    { ch: "ch-points",
      q: "What is the no-go zone?",
      o: ["Directly downwind", "Any course with the wind abeam", "A sector either side of where the wind comes from, where the sails can't drive the boat", "Any wind above 20 knots"], a: 2,
      e: "Point too close to the wind and the drive (F × sin of the apparent angle) disappears: the sails flap and the boat stops, 'in irons'. Our examples use 45° either side." },
    { ch: "ch-points",
      q: "A mark is 1 km directly upwind. Tacking at 45° to the wind, about how far do you sail?",
      o: ["1 km", "0.71 km", "2 km", "About 1.41 km"], a: 3,
      e: "Distance = 1 ÷ cos 45° ≈ 1.41 km, whether you do it in two long legs or many short ones." },
    { ch: "ch-points",
      q: "What's the difference between a tack and a gybe?",
      o: ["In a tack the bow turns through the wind; in a gybe the stern does, and the boom swings across fast", "They're the same thing", "A tack is downwind and a gybe is upwind", "A gybe means stopping head to wind"], a: 0,
      e: "Tacking turns the bow through the wind (upwind); gybing turns the stern through it (downwind), and the boom comes across quickly, so the crew ducks and the helm controls it." },
    { ch: "ch-board",
      q: "Why can a centreboard much smaller than the sail resist the sail's sideways pull?",
      o: ["Because it's heavy", "Water is about 840 times denser than air, so a small board makes a big force once the boat is moving", "It drags along the bottom", "It stops all leeway completely"], a: 1,
      e: "Force grows with density × speed²: water at 5 kn gives about 3,391 Pa, against about 27 Pa for air at 13 kn. A little leeway sets the board at a small angle so it can make lift." },
    { ch: "ch-board",
      q: "A dinghy has stopped head-to-wind. Why does it slide sideways when the sail fills again?",
      o: ["The sail is too big", "The rudder is on the wrong side", "With little boat speed the board can't make enough sideways force; it grows with speed squared", "The boat is too light"], a: 2,
      e: "At 1 kn our 0.25 m² board makes only about 10 N; at 5 kn about 254 N. Build speed before pointing high again." },
    { ch: "ch-heel",
      q: "A heeling force of 244 N acts 2.5 m above the board. How much crew weight, sitting 1 m out, balances it?",
      o: ["About 24 kg", "About 244 kg", "About 6 kg", "About 62 kg"], a: 3,
      e: "Heeling moment = 244 × 2.5 = 610 N·m. Weight = 610 ÷ (9.81 × 1) ≈ 62 kg. Sit further out (or trapeze) and you need less." },
    { ch: "ch-heel",
      q: "A gust hits and the dinghy heels too far. Which helps?",
      o: ["Ease the sheet and hike out harder", "Pull the sail in tighter and sit in the middle", "Move the crew to the leeward side", "Pull the centreboard fully up"], a: 0,
      e: "Easing the sheet spills wind and cuts the heeling force; hiking adds righting moment. Sheeting in or moving weight to leeward makes a capsize more likely." },
    { ch: "ch-planing",
      q: "Using hull speed ≈ 2.43 × √(waterline in metres) knots, what's the hull speed of a 4 m waterline?",
      o: ["About 2.4 kn", "About 4.9 kn", "About 9.7 kn", "About 16 kn"], a: 1,
      e: "2.43 × √4 = 2.43 × 2 ≈ 4.9 kn. At that speed the bow wave is as long as the boat." },
    { ch: "ch-planing",
      q: "What lets a light racing dinghy go faster than its hull speed?",
      o: ["A heavier keel", "A heavier crew", "Planing: with enough power it climbs its bow wave and skims on the surface", "Raising the sails higher"], a: 2,
      e: "A light hull with enough power can lift onto the water's surface instead of pushing through it. That's why racing dinghies and skiffs are built light." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- WIND & SAIL LAB ----------
  // Apparent wind = true wind + headwind from the boat's own speed (vector sum):
  //   AWS = sqrt(TWS² + BS² + 2·TWS·BS·cos TWA);  AWA = acos((TWS·cos TWA + BS) / AWS)
  // Sail force (lift only, illustrative): F = ½ · 1.225 · (AWS in m/s)² · area · CL (CL = 1.0), at right angles to the apparent wind.
  // Drive = F · sin AWA; heeling force = F · cos AWA. Heeling moment = heel × 2.5 m; crew weight to balance at 1 m out = moment ÷ (9.81 × 1 m).
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("sl-tws")) return;
    const KN = 0.514444, RHO = 1.225, CL = 1.0, LEVER = 2.5, ARM = 1.0, G = 9.81, R = Math.PI / 180;
    function update() {
      const tws = +$("sl-tws").value, twa = +$("sl-twa").value, bs = +$("sl-bs").value, area = +$("sl-area").value;
      $("sl-tws-o").textContent = tws + " kn";
      $("sl-twa-o").textContent = twa + "°";
      $("sl-bs-o").textContent = bs.toFixed(1) + " kn";
      $("sl-area-o").textContent = area.toFixed(1) + " m²";
      const aws = Math.sqrt(tws * tws + bs * bs + 2 * tws * bs * Math.cos(twa * R));
      const awa = Math.acos(Math.min(1, Math.max(-1, (tws * Math.cos(twa * R) + bs) / aws))) / R;
      const f = 0.5 * RHO * Math.pow(aws * KN, 2) * area * CL;
      const drive = f * Math.sin(awa * R), heel = f * Math.cos(awa * R);
      const kg = heel * LEVER / (G * ARM);
      $("sl-aws").textContent = aws.toFixed(1) + " kn";
      $("sl-awa").textContent = Math.round(awa) + "°";
      $("sl-f").textContent = Math.round(f) + " N";
      $("sl-drive").textContent = Math.round(drive) + " N";
      $("sl-heel").textContent = Math.round(heel) + " N";
      $("sl-hike").textContent = Math.round(kg) + " kg";
      $("sl-bar").style.width = Math.round(100 * Math.sin(awa * R)) + "%";
    }
    ["sl-tws", "sl-twa", "sl-bs", "sl-area"].forEach(id => $(id).addEventListener("input", update));
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
