// Kinetic: freediving page script (generated by kinetic-tools/build/build.py)
(function () {
  const PAGE = {
    key: "freediving",
    v1: "Physics: nailed it 🫧",
    b1: "You've got the physics of freediving. Skim the chapters for anything you missed, then scroll to “Where to freedive” for courses at your level. Knowing the science is a great start; it isn't the same as the breathing, equalisation, buddy and rescue skills an instructor teaches in the water.",
    b2: "You have the basics. Fill the gaps below before your first course, especially oxygen, CO₂ and blackout: they're the chapters that keep you and your buddy safe.",
    b3: "No shame in that: this is exactly what the chapters are for. Read the ones linked below, then take the challenge again.",
    whereLabel: "Where to freedive at my level →",
    disclaimer: "<strong>Self-check only.</strong> This quiz is a learning aid. It is not a certification, a freediving course or a substitute for training with a qualified instructor. Never freedive alone: dive only with a trained buddy who watches every dive, don't hyperventilate, and follow your course's depth limits and the school's medical rules."
  };
  const CHAPTERS = {
    "ch-reflex":   "Ch 1 · The dive reflex",
    "ch-gases":    "Ch 2 · Oxygen, CO₂ & the urge to breathe",
    "ch-blackout": "Ch 3 · Hypoxia & blackout",
    "ch-boyle":    "Ch 4 · Boyle's law & lung squeeze",
    "ch-equalise": "Ch 5 · Equalisation",
    "ch-buoyancy": "Ch 6 · Buoyancy, freefall & the disciplines"
  };
  const QUESTIONS = [
    { ch: "ch-reflex",
      q: "Which of these is part of the mammalian dive reflex?",
      o: ["A slower heart rate and narrowed blood vessels in the limbs", "A faster heart rate", "Wider blood vessels in the skin", "Stronger urge to breathe"], a: 0,
      e: "Holding your breath (more so with a cold, wet face) slows the heart through the vagus nerve and narrows blood vessels in the limbs and gut, keeping oxygen-rich blood for the heart and brain." },
    { ch: "ch-reflex",
      q: "Why does a slower heart rate help during a breath-hold?",
      o: ["It makes you lighter", "It cuts the body's oxygen use, saving oxygen for the heart and brain", "It equalises your ears", "It removes CO₂"], a: 1,
      e: "Less blood pumped to muscles and organs that can wait means oxygen stores last longer. The spleen can also squeeze out extra red blood cells." },
    { ch: "ch-gases",
      q: "What mainly drives the urge to breathe during a breath-hold?",
      o: ["Falling oxygen", "Cold water", "Rising carbon dioxide (CO₂)", "Water pressure on the chest"], a: 2,
      e: "CO₂ is a strong breathing stimulus; low oxygen is a much weaker one. That's why the urge is a safety alarm, not a fuel gauge." },
    { ch: "ch-gases",
      q: "Why is hyperventilating before a freedive dangerous?",
      o: ["It fills your lungs with water", "It makes you sink", "It raises CO₂ too fast", "It lowers CO₂, so the urge to breathe comes late and oxygen can run out first"], a: 3,
      e: "DAN: hyperventilation is any breathing that drops CO₂. With the CO₂ alarm delayed, you can become dangerously hypoxic without warning. Breathe normally before the final breath." },
    { ch: "ch-gases",
      q: "Your lungs hold about 0.66 L of usable oxygen and you use 0.25 L per minute. About how long does it last?",
      o: ["About 2.6 minutes", "About 26 minutes", "About 16 seconds", "About 10 minutes"], a: 0,
      e: "0.66 ÷ 0.25 ≈ 2.6 min (illustrative). Blood and muscle hold more oxygen, and the dive reflex slows its use, but the budget is always limited." },
    { ch: "ch-blackout",
      q: "Your lungs hold 10% oxygen at 30 m (4 bar). What's the oxygen partial pressure there, and at the surface?",
      o: ["0.10 bar, then 0.40 bar", "0.40 bar, then 0.10 bar", "0.40 bar at both", "0.04 bar, then 0.01 bar"], a: 1,
      e: "Partial pressure = fraction × total pressure: 0.10 × 4 = 0.40 bar at 30 m, but only 0.10 × 1 = 0.10 bar at the surface. Ascending cuts it to a quarter." },
    { ch: "ch-blackout",
      q: "According to a DAN article, where do almost all freediving blackouts happen?",
      o: ["At the deepest point", "On the way down", "At the surface or within about 5 m (16 ft) of it", "On the boat"], a: 2,
      e: "Oxygen partial pressure falls fastest near the surface on the way up. DAN also notes most problems happen in the last third of the ascent." },
    { ch: "ch-blackout",
      q: "Why should your buddy keep watching you for a while after you surface?",
      o: ["To count your dives", "To check your mask", "Because they're bored", "A blackout can still happen at the surface as oxygen keeps falling"], a: 3,
      e: "Oxygen already in your blood keeps being used for a few seconds after your first breaths. Recovery breathing and a buddy within reach are the safety net." },
    { ch: "ch-boyle",
      q: "Your lungs hold 6 L at the surface. Using Boyle's law, what's their volume at 20 m (3 bar)?",
      o: ["2 L", "3 L", "18 L", "6 L"], a: 0,
      e: "P × V stays constant: 6 L × 1 bar = V × 3 bar, so V = 2 L, a third of the surface volume." },
    { ch: "ch-boyle",
      q: "About what is the total pressure at 30 m in the sea?",
      o: ["1 bar", "4 bar", "3 bar", "30 bar"], a: 1,
      e: "Every 10 m of sea water adds about 1 bar to the 1 bar of air above: 1 + 3 = 4 bar." },
    { ch: "ch-boyle",
      q: "What helps protect a deep freediver's lungs once they're squeezed below their usual empty-lung volume?",
      o: ["A thicker wetsuit", "Breathing out at depth", "The blood shift: blood moves into the chest and fills some of the space", "Nothing: lungs can't go below it"], a: 2,
      e: "Physiologists describe a 'blood shift' into the chest that limits the effect of compression. Push too hard and lung squeeze (bleeding in the lungs) can still happen." },
    { ch: "ch-equalise",
      q: "Between which depths does the air in your ears and mask change volume most, in proportion?",
      o: ["30 to 40 m", "20 to 30 m", "10 to 20 m", "0 to 10 m"], a: 3,
      e: "0 → 10 m halves the volume (−50%); 10 → 20 m is −33%; 20 → 30 m −25%; 30 → 40 m −20%. Equalise early and often near the surface." },
    { ch: "ch-equalise",
      q: "What is the Frenzel technique?",
      o: ["Using the tongue and throat as a piston to push air into the ears, with the airway to the lungs closed", "Blowing hard against a pinched nose with the chest muscles", "Swallowing water", "Holding your breath longer"], a: 0,
      e: "Frenzel uses a small amount of air in the mouth and nose, so it still works head-down and when the lungs are compressed. AIDA teaches it in the AIDA3 course." },
    { ch: "ch-buoyancy",
      q: "Why does a freediver start to sink without kicking below a certain depth?",
      o: ["Water gets heavier", "Lungs and wetsuit compress, displacing less water, so buoyancy falls below weight", "The weight belt gets heavier", "Gravity increases with depth"], a: 1,
      e: "Below the neutral depth the diver is negatively buoyant and can 'freefall', saving oxygen. On the way up, the same physics means swimming hardest at the start." },
    { ch: "ch-buoyancy",
      q: "In which discipline does the freediver pull down and up the dive line by hand?",
      o: ["Static apnea (STA)", "Dynamic (DYN)", "Free immersion (FIM)", "Constant weight (CWT)"], a: 2,
      e: "AIDA defines FIM as pulling on the rope down and up. STA is a breath-hold at the surface; DYN is horizontal distance; CWT uses fins under your own power." }
  ];

  // ---------- QUIZ RENDER ----------
  const list = document.getElementById("quiz-list");
  const dots = document.getElementById("quiz-dots");
  const prog = document.getElementById("quiz-progress");
  const progLabel = document.getElementById("quiz-progress-label");
  const warn = document.getElementById("quiz-warn");
  const resultBox = document.getElementById("quiz-result");
  let graded = false;

  function esc(s) { return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

  QUESTIONS.forEach((item, i) => {
    const n = i + 1;
    const div = document.createElement("div");
    div.className = "q";
    div.id = "q" + n;
    div.dataset.index = i;
    div.innerHTML =
      `<span class="qtag">${esc(CHAPTERS[item.ch].split(" · ")[1])}</span>` +
      `<span class="qnum">Question ${n} / ${QUESTIONS.length}</span>` +
      `<h3>${esc(item.q)}</h3>` +
      `<div class="opts" role="radiogroup" aria-label="Question ${n}">` +
      item.o.map((opt, j) =>
        `<label class="opt"><input type="radio" name="q${n}" value="${j}"><span>${esc(opt)}</span><span class="mark"></span></label>`
      ).join("") +
      `</div><div class="explain" aria-live="polite"></div>`;
    list.appendChild(div);

    const d = document.createElement("a");
    d.href = "#q" + n; d.textContent = n; d.id = "dot" + n;
    d.setAttribute("aria-label", "Go to question " + n);
    dots.appendChild(d);
  });

  function answeredCount() {
    return QUESTIONS.filter((_, i) => document.querySelector(`input[name="q${i + 1}"]:checked`)).length;
  }
  function updateProgress() {
    const c = answeredCount();
    prog.style.width = (c / QUESTIONS.length * 100) + "%";
    progLabel.textContent = `${c} of ${QUESTIONS.length} answered`;
  }

  list.addEventListener("change", (ev) => {
    if (graded || ev.target.type !== "radio") return;
    const q = ev.target.closest(".q");
    q.querySelectorAll(".opt").forEach(l => l.classList.toggle("sel", l.querySelector("input").checked));
    document.getElementById("dot" + (+q.dataset.index + 1)).classList.add("answered");
    updateProgress();
    warn.style.display = "none";
  });

  function grade() {
    const unanswered = QUESTIONS.length - answeredCount();
    if (unanswered > 0 && !document.getElementById("quiz-submit").dataset.confirmed) {
      warn.textContent = `${unanswered} question${unanswered > 1 ? "s" : ""} unanswered. They'll count as wrong. Press submit again to score anyway.`;
      warn.style.display = "block";
      document.getElementById("quiz-submit").dataset.confirmed = "1";
      return;
    }
    graded = true;
    let score = 0;
    const wrongChapters = new Map();
    QUESTIONS.forEach((item, i) => {
      const n = i + 1;
      const qEl = document.getElementById("q" + n);
      const picked = document.querySelector(`input[name="q${n}"]:checked`);
      const pickedIdx = picked ? +picked.value : -1;
      const right = pickedIdx === item.a;
      if (right) score++;
      else wrongChapters.set(item.ch, (wrongChapters.get(item.ch) || []).concat(n));
      qEl.classList.add("graded", right ? "right" : (picked ? "wrong" : "skipped"));
      qEl.querySelectorAll("input").forEach(inp => inp.disabled = true);
      qEl.querySelectorAll(".opt").forEach((lab, j) => {
        if (j === item.a) { lab.classList.add("correct"); lab.querySelector(".mark").textContent = "✓ correct"; }
        else if (j === pickedIdx) { lab.classList.add("incorrect"); lab.querySelector(".mark").textContent = "✗ your pick"; }
      });
      const ex = qEl.querySelector(".explain");
      ex.innerHTML = `<span class="verdict">${right ? "Correct." : (picked ? "Not quite." : "Skipped.")}</span> ${esc(item.e)}` +
        (right ? "" : `<br><a class="chlink" href="#${item.ch}" data-wrong-link="${item.ch}">Read ${esc(CHAPTERS[item.ch])} →</a>`);
      const dot = document.getElementById("dot" + n);
      dot.classList.remove("answered"); dot.classList.add(right ? "right" : "wrong");
    });

    const pct = score / QUESTIONS.length;
    let lvl, title, blurb;
    if (pct >= 0.8) { lvl = "lvl-ready"; title = PAGE.v1; blurb = PAGE.b1; }
    else if (pct >= 0.55) { lvl = "lvl-close"; title = "Nearly there. Brush up on a couple of chapters"; blurb = PAGE.b2; }
    else { lvl = "lvl-brush"; title = "Brush up first"; blurb = PAGE.b3; }

    resultBox.className = "result show " + lvl;
    const chItems = [...wrongChapters.entries()].map(([ch, qs]) =>
      `<li><a href="#${ch}" data-summary-link="${ch}">${esc(CHAPTERS[ch])}</a> <span class="small">(question${qs.length > 1 ? "s" : ""} ${qs.join(", ")})</span></li>`).join("");
    resultBox.innerHTML =
      `<div class="score" id="quiz-score">${score}<small> / ${QUESTIONS.length}</small></div>` +
      `<h3 id="quiz-verdict">${title}</h3><p>${blurb}</p>` +
      `<div class="result-note" id="quiz-disclaimer" role="note">${PAGE.disclaimer}</div>` +
      (chItems ? `<strong>Chapters to read:</strong><ul id="quiz-revisit">${chItems}</ul>` : `<p><strong>Perfect score.</strong> The chapters still have the worked numbers if you want to go deeper.</p>`) +
      `<div class="actions"><button class="btn btn-ghost" type="button" id="quiz-retake">↺ Retake the challenge</button><a class="btn btn-ghost" href="#where">${PAGE.whereLabel}</a></div>`;
    document.getElementById("quiz-retake").addEventListener("click", resetQuiz);
    document.getElementById("quiz-submit").style.display = "none";
    warn.style.display = "none";
    resultBox.scrollIntoView({ behavior: "smooth", block: "start" });
    try { localStorage.setItem("kinetic-" + PAGE.key + "-last", JSON.stringify({ score, of: QUESTIONS.length, at: Date.now() })); } catch (e) {}
  }

  function resetQuiz() {
    graded = false;
    resultBox.className = "result"; resultBox.innerHTML = "";
    document.querySelectorAll(".q").forEach(q => {
      q.className = "q";
      q.querySelector(".explain").innerHTML = "";
      q.querySelectorAll("input").forEach(i => { i.checked = false; i.disabled = false; });
      q.querySelectorAll(".opt").forEach(l => { l.className = "opt"; l.querySelector(".mark").textContent = ""; });
    });
    document.querySelectorAll("#quiz-dots a").forEach(d => d.className = "");
    const sub = document.getElementById("quiz-submit");
    sub.style.display = ""; delete sub.dataset.confirmed;
    updateProgress();
    document.getElementById("q1").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  document.getElementById("quiz-submit").addEventListener("click", grade);
  document.getElementById("quiz-reset").addEventListener("click", resetQuiz);
  updateProgress();

  // Expose for automated tests
  window.KINETIC_QUIZ = { QUESTIONS, CHAPTERS, grade, resetQuiz };


  // ---------- DEPTH & BREATH LAB ----------
  // Sea water: P = 1 + d/10 bar. Boyle: V = V0 / P. Residual volume fixed at 1.5 L (illustrative).
  // Lung O2 partial pressure = fraction × P (×101.3 kPa/bar), and the same gas at the surface = fraction × 1 bar.
  // Buoyancy (kg): 1.025 × (lung L + suit gas L, both ÷ P) − lead − 2.2 kg (body without air, illustrative).
  (function () {
    const $ = id => document.getElementById(id);
    if (!$("fd-d")) return;
    const RV = 1.5, BODY = 2.2, RHO = 1.025, KPA = 101.325;
    let suit = 3;
    const f1 = n => n.toFixed(1);
    function update() {
      const d = +$("fd-d").value, v0 = +$("fd-v").value, lead = +$("fd-lead").value, fo2 = +$("fd-o2").value;
      $("fd-d-o").textContent = d + " m";
      $("fd-v-o").textContent = f1(v0) + " L";
      $("fd-lead-o").textContent = lead + " kg";
      $("fd-o2-o").textContent = fo2 + "%";
      const P = 1 + d / 10, v = v0 / P;
      const rvd = (v0 / RV - 1) * 10;
      const b = RHO * (v0 + suit) / P - lead - BODY;
      const pn = RHO * (v0 + suit) / (lead + BODY), dn = (pn - 1) * 10;
      $("fd-p").textContent = f1(P) + " bar";
      $("fd-vol").textContent = f1(v) + " L";
      $("fd-vol-s").textContent = "Ch 4 · " + Math.round(100 / P) + "% of surface volume";
      $("fd-rv").textContent = Math.round(rvd) + " m";
      $("fd-o2d").textContent = f1(fo2 / 100 * P * KPA) + " → " + f1(fo2 / 100 * KPA) + " kPa";
      $("fd-b").textContent = (b >= 0 ? "+" : "−") + Math.abs(b).toFixed(1) + " kg" + (Math.abs(b) < 0.05 ? " (neutral)" : b > 0 ? " (floats)" : " (sinks)");
      $("fd-n").textContent = dn <= 0 ? "sinks from the surface" : Math.round(dn) + " m";
      $("fd-bar").style.width = Math.min(100, 100 / P) + "%";
    }
    ["fd-d", "fd-v", "fd-lead", "fd-o2"].forEach(id => $(id).addEventListener("input", update));
    document.querySelectorAll("#fd-suit button").forEach(btn => btn.addEventListener("click", () => {
      suit = +btn.dataset.l;
      document.querySelectorAll("#fd-suit button").forEach(x => x.setAttribute("aria-pressed", x === btn ? "true" : "false"));
      update();
    }));
    update();
  })();

  // ---------- LEVEL TABS ----------
  const tabs = document.querySelectorAll(".lvl-tabs button");
  tabs.forEach(btn => btn.addEventListener("click", () => {
    tabs.forEach(b => b.setAttribute("aria-selected", b === btn ? "true" : "false"));
    document.querySelectorAll(".lvl-panel").forEach(p => p.classList.toggle("show", p.id === btn.getAttribute("aria-controls")));
  }));

  // ---------- STICKY NAV ACTIVE STATE ----------
  const navLinks = [...document.querySelectorAll(".sectionnav a")];
  const targets = navLinks.map(a => document.querySelector(a.getAttribute("href"))).filter(Boolean);
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => {
        if (en.isIntersecting) {
          navLinks.forEach(a => a.classList.toggle("active", a.getAttribute("href") === "#" + en.target.id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    targets.forEach(t => io.observe(t));
  }

  // ---------- MOBILE NAV: edge fades + keep the active link in view ----------
  (function () {
    const snav = document.querySelector(".sectionnav");
    if (!snav) return;
    const fades = () => {
      const max = snav.scrollWidth - snav.clientWidth;
      snav.classList.toggle("fade-l", max > 4 && snav.scrollLeft > 4);
      snav.classList.toggle("fade-r", max > 4 && snav.scrollLeft < max - 4);
    };
    snav.addEventListener("scroll", fades, { passive: true });
    window.addEventListener("resize", fades);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(fades);
    fades();
    const keep = () => {
      const a = snav.querySelector("a.active");
      if (!a || snav.scrollWidth <= snav.clientWidth + 4) return;
      const r = a.getBoundingClientRect(), n = snav.getBoundingClientRect();
      if (r.left < n.left + 16 || r.right > n.right - 40) snav.scrollBy({ left: r.left - n.left - 20, behavior: "smooth" });
    };
    if ("MutationObserver" in window) {
      const mo = new MutationObserver(keep);
      snav.querySelectorAll("a").forEach(a => mo.observe(a, { attributes: true, attributeFilter: ["class"] }));
    }
  })();
})();
